# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.srcs/sources_1/bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_us_2/byotee_extclk_axi_interconnect_0_imp_auto_us_2.xci
# IP: The module: 'byotee_extclk_axi_interconnect_0_imp_auto_us_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.gen/sources_1/bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_us_2/byotee_extclk_axi_interconnect_0_imp_auto_us_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'byotee_extclk_axi_interconnect_0_imp_auto_us_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.gen/sources_1/bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_us_2/byotee_extclk_axi_interconnect_0_imp_auto_us_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'byotee_extclk_axi_interconnect_0_imp_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.srcs/sources_1/bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_us_2/byotee_extclk_axi_interconnect_0_imp_auto_us_2.xci
# IP: The module: 'byotee_extclk_axi_interconnect_0_imp_auto_us_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.gen/sources_1/bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_us_2/byotee_extclk_axi_interconnect_0_imp_auto_us_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'byotee_extclk_axi_interconnect_0_imp_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.gen/sources_1/bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_us_2/byotee_extclk_axi_interconnect_0_imp_auto_us_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'byotee_extclk_axi_interconnect_0_imp_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
