set_property SRC_FILE_INFO {cfile:/home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.srcs/constraints_tutorial/imports/new/OSDZU3_Tutorial_IO_Standards.xdc rfile:../../../OSDZU3_Ref_Design.srcs/constraints_tutorial/imports/new/OSDZU3_Tutorial_IO_Standards.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.srcs/constraints_tutorial/imports/new/osdzu3_package_pins.tcl rfile:../../../OSDZU3_Ref_Design.srcs/constraints_tutorial/imports/new/osdzu3_package_pins.tcl id:2 unmanaged:yes} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {dip_switches_8bits_tri_io[*]}]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:NONE read:READ} [current_design]
tclapp::octavo::osdzu3::set_osdzu3_package_pin E7 [get_ports {leds_8bits_tri_io[0]}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:NONE read:READ} [current_design]
tclapp::octavo::osdzu3::set_osdzu3_package_pin F7 [get_ports {leds_8bits_tri_io[1]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:NONE read:READ} [current_design]
tclapp::octavo::osdzu3::set_osdzu3_package_pin A4 [get_ports {leds_8bits_tri_io[2]}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:NONE read:READ} [current_design]
tclapp::octavo::osdzu3::set_osdzu3_package_pin B4 [get_ports {leds_8bits_tri_io[3]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:NONE read:READ} [current_design]
tclapp::octavo::osdzu3::set_osdzu3_package_pin C10 [get_ports {leds_8bits_tri_io[4]}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:NONE read:READ} [current_design]
tclapp::octavo::osdzu3::set_osdzu3_package_pin D10 [get_ports {leds_8bits_tri_io[5]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:NONE read:READ} [current_design]
tclapp::octavo::osdzu3::set_osdzu3_package_pin C8 [get_ports {leds_8bits_tri_io[6]}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:NONE read:READ} [current_design]
tclapp::octavo::osdzu3::set_osdzu3_package_pin D8 [get_ports {leds_8bits_tri_io[7]}]
