-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_mix_0_0_v_mix_422_to_444_true_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    srcLayer1Yuv422_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    srcLayer1Yuv422_empty_n : IN STD_LOGIC;
    srcLayer1Yuv422_read : OUT STD_LOGIC;
    srcLayer1Yuv422_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer1Yuv422_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    layerEnableFlag : IN STD_LOGIC_VECTOR (0 downto 0);
    srcLayer1Yuv_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    srcLayer1Yuv_full_n : IN STD_LOGIC;
    srcLayer1Yuv_write : OUT STD_LOGIC;
    srcLayer1Yuv_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    srcLayer1Yuv_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of design_1_v_mix_0_0_v_mix_422_to_444_true_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000101";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layerEnableFlag_read_read_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal layerEnableFlag_read_reg_238 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal width_read_reg_242 : STD_LOGIC_VECTOR (15 downto 0);
    signal height_read_reg_247 : STD_LOGIC_VECTOR (15 downto 0);
    signal loopWidth_fu_162_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal loopWidth_reg_258 : STD_LOGIC_VECTOR (15 downto 0);
    signal cmp28336_fu_168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp28336_reg_345 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_0_0_0_0207_2_lcssa417_load_reg_353 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_0_0_0_0_0207_3_lcssa420_load_reg_358 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0207_4_lcssa423_load_reg_363 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_start : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_done : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_idle : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_ready : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_srcLayer1Yuv422_read : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_srcLayer1Yuv_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_srcLayer1Yuv_write : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0199355390_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0199355390_out_o_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0200353387_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0200353387_out_o_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0_2384_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0_2384_out_o_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0205_2381_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0205_2381_out_o_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0_1374_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0_1374_out_o_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0205_1367_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0205_1367_out_o_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0206358363_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0206358363_out_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_4362_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_4362_out_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_3361_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_3361_out_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_2360_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_2360_out_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_1359_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_1359_out_o_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0199354_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0199354_out_o_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0200352_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0200352_out_o_ap_vld : STD_LOGIC;
    signal grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_0_0_0199355388_lcssa450_fu_112 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0200353385_lcssa447_fu_108 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0_2382_lcssa444_fu_104 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0205_2379_lcssa441_fu_100 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0_1372_lcssa435_fu_96 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0205_1365_lcssa429_fu_92 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0207_4_lcssa423_fu_84 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0207_3_lcssa420_fu_80 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0207_2_lcssa417_fu_76 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0207_1_lcssa412_fu_72 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0199355_lcssa407_fu_64 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0200353_lcssa404_fu_60 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal y_9_fu_56 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln159_fu_191_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln159_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_0_0206358_lcssa409_fu_68 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln159_fu_222_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0206358_lcssa364426_fu_88 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zext_ln159_fu_182_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_mix_0_0_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        srcLayer1Yuv422_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        srcLayer1Yuv422_empty_n : IN STD_LOGIC;
        srcLayer1Yuv422_read : OUT STD_LOGIC;
        srcLayer1Yuv422_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer1Yuv422_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer1Yuv_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        srcLayer1Yuv_full_n : IN STD_LOGIC;
        srcLayer1Yuv_write : OUT STD_LOGIC;
        srcLayer1Yuv_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        srcLayer1Yuv_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        p_0_0_0206358_lcssa364426 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0207_4_lcssa423 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0207_3_lcssa420 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0207_2_lcssa417 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0206358_lcssa409 : IN STD_LOGIC_VECTOR (7 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
        width : IN STD_LOGIC_VECTOR (15 downto 0);
        p_0_0_0199355390_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0199355390_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0199355390_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0200353387_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0200353387_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0200353387_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0_2384_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0_2384_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0_2384_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0205_2381_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0205_2381_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0205_2381_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0_1374_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0_1374_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0_1374_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0205_1367_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0205_1367_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0205_1367_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0206358363_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0206358363_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0207_4362_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0207_4362_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0207_3361_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0207_3361_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0207_2360_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0207_2360_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0207_1359_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0207_1359_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0207_1359_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0199354_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0199354_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0199354_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0200352_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0200352_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0200352_out_o_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134 : component design_1_v_mix_0_0_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_start,
        ap_done => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_done,
        ap_idle => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_idle,
        ap_ready => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_ready,
        srcLayer1Yuv422_dout => srcLayer1Yuv422_dout,
        srcLayer1Yuv422_empty_n => srcLayer1Yuv422_empty_n,
        srcLayer1Yuv422_read => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_srcLayer1Yuv422_read,
        srcLayer1Yuv422_num_data_valid => ap_const_lv3_0,
        srcLayer1Yuv422_fifo_cap => ap_const_lv3_0,
        srcLayer1Yuv_din => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_srcLayer1Yuv_din,
        srcLayer1Yuv_full_n => srcLayer1Yuv_full_n,
        srcLayer1Yuv_write => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_srcLayer1Yuv_write,
        srcLayer1Yuv_num_data_valid => srcLayer1Yuv_num_data_valid,
        srcLayer1Yuv_fifo_cap => srcLayer1Yuv_fifo_cap,
        p_0_0_0206358_lcssa364426 => p_0_0_0206358_lcssa364426_fu_88,
        p_0_0_0_0_0207_4_lcssa423 => p_0_0_0_0_0207_4_lcssa423_load_reg_363,
        p_0_0_0_0_0207_3_lcssa420 => p_0_0_0_0_0207_3_lcssa420_load_reg_358,
        p_0_0_0_0_0207_2_lcssa417 => p_0_0_0_0_0207_2_lcssa417_load_reg_353,
        p_0_0_0206358_lcssa409 => p_0_0_0206358_lcssa409_fu_68,
        loopWidth => loopWidth_reg_258,
        width => width_read_reg_242,
        p_0_0_0199355390_out_i => p_0_0_0199355388_lcssa450_fu_112,
        p_0_0_0199355390_out_o => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0199355390_out_o,
        p_0_0_0199355390_out_o_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0199355390_out_o_ap_vld,
        p_0_0_0200353387_out_i => p_0_0_0200353385_lcssa447_fu_108,
        p_0_0_0200353387_out_o => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0200353387_out_o,
        p_0_0_0200353387_out_o_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0200353387_out_o_ap_vld,
        p_0_0_0_0_0_2384_out_i => p_0_0_0_0_0_2382_lcssa444_fu_104,
        p_0_0_0_0_0_2384_out_o => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0_2384_out_o,
        p_0_0_0_0_0_2384_out_o_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0_2384_out_o_ap_vld,
        p_0_0_0_0_0205_2381_out_i => p_0_0_0_0_0205_2379_lcssa441_fu_100,
        p_0_0_0_0_0205_2381_out_o => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0205_2381_out_o,
        p_0_0_0_0_0205_2381_out_o_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0205_2381_out_o_ap_vld,
        p_0_0_0_0_0_1374_out_i => p_0_0_0_0_0_1372_lcssa435_fu_96,
        p_0_0_0_0_0_1374_out_o => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0_1374_out_o,
        p_0_0_0_0_0_1374_out_o_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0_1374_out_o_ap_vld,
        p_0_0_0_0_0205_1367_out_i => p_0_0_0_0_0205_1365_lcssa429_fu_92,
        p_0_0_0_0_0205_1367_out_o => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0205_1367_out_o,
        p_0_0_0_0_0205_1367_out_o_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0205_1367_out_o_ap_vld,
        p_0_0_0206358363_out => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0206358363_out,
        p_0_0_0206358363_out_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0206358363_out_ap_vld,
        p_0_0_0_0_0207_4362_out => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_4362_out,
        p_0_0_0_0_0207_4362_out_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_4362_out_ap_vld,
        p_0_0_0_0_0207_3361_out => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_3361_out,
        p_0_0_0_0_0207_3361_out_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_3361_out_ap_vld,
        p_0_0_0_0_0207_2360_out => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_2360_out,
        p_0_0_0_0_0207_2360_out_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_2360_out_ap_vld,
        p_0_0_0_0_0207_1359_out_i => p_0_0_0_0_0207_1_lcssa412_fu_72,
        p_0_0_0_0_0207_1359_out_o => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_1359_out_o,
        p_0_0_0_0_0207_1359_out_o_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_1359_out_o_ap_vld,
        p_0_0_0199354_out_i => p_0_0_0199355_lcssa407_fu_64,
        p_0_0_0199354_out_o => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0199354_out_o,
        p_0_0_0199354_out_o_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0199354_out_o_ap_vld,
        p_0_0_0200352_out_i => p_0_0_0200353_lcssa404_fu_60,
        p_0_0_0200352_out_o => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0200352_out_o,
        p_0_0_0200352_out_o_ap_vld => grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0200352_out_o_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and ((layerEnableFlag_read_reg_238 = ap_const_lv1_0) or (icmp_ln159_fu_186_p2 = ap_const_lv1_0)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_ready = ap_const_logic_1)) then 
                    grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_9_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (layerEnableFlag_read_read_fu_116_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_9_fu_56 <= ap_const_lv15_0;
            elsif (((layerEnableFlag_read_reg_238 = ap_const_lv1_1) and (icmp_ln159_fu_186_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_9_fu_56 <= add_ln159_fu_191_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                cmp28336_reg_345 <= cmp28336_fu_168_p2;
                height_read_reg_247 <= height;
                layerEnableFlag_read_reg_238 <= layerEnableFlag;
                loopWidth_reg_258 <= loopWidth_fu_162_p2;
                width_read_reg_242 <= width;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0199355390_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0199355388_lcssa450_fu_112 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0199355390_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0199354_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0199355_lcssa407_fu_64 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0199354_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0200353387_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0200353385_lcssa447_fu_108 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0200353387_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0200352_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0200353_lcssa404_fu_60 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0200352_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                p_0_0_0206358_lcssa364426_fu_88 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0206358363_out;
                p_0_0_0206358_lcssa409_fu_68 <= select_ln159_fu_222_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0205_1367_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0205_1365_lcssa429_fu_92 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0205_1367_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0205_2381_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0205_2379_lcssa441_fu_100 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0205_2381_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_1359_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0207_1_lcssa412_fu_72 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_1359_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_2360_out_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0207_2_lcssa417_fu_76 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_2360_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                p_0_0_0_0_0207_2_lcssa417_load_reg_353 <= p_0_0_0_0_0207_2_lcssa417_fu_76;
                p_0_0_0_0_0207_3_lcssa420_load_reg_358 <= p_0_0_0_0_0207_3_lcssa420_fu_80;
                p_0_0_0_0_0207_4_lcssa423_load_reg_363 <= p_0_0_0_0_0207_4_lcssa423_fu_84;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_3361_out_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0207_3_lcssa420_fu_80 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_3361_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_4362_out_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0207_4_lcssa423_fu_84 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0207_4362_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0_1374_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0_1372_lcssa435_fu_96 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0_1374_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0_2384_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0_2382_lcssa444_fu_104 <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0_0_0_2384_out_o;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layerEnableFlag_read_reg_238, ap_block_state1, ap_CS_fsm_state2, grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_done, ap_CS_fsm_state4, icmp_ln159_fu_186_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((layerEnableFlag_read_reg_238 = ap_const_lv1_0) or (icmp_ln159_fu_186_p2 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln159_fu_191_p2 <= std_logic_vector(unsigned(y_9_fu_56) + unsigned(ap_const_lv15_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_done)
    begin
        if ((grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layerEnableFlag_read_reg_238, ap_CS_fsm_state2, icmp_ln159_fu_186_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((layerEnableFlag_read_reg_238 = ap_const_lv1_0) or (icmp_ln159_fu_186_p2 = ap_const_lv1_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    cmp28336_fu_168_p2 <= "1" when (signed(loopWidth_fu_162_p2) > signed(ap_const_lv16_0)) else "0";
    grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_start <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_ap_start_reg;
    icmp_ln159_fu_186_p2 <= "1" when (signed(zext_ln159_fu_182_p1) < signed(height_read_reg_247)) else "0";

    internal_ap_ready_assign_proc : process(layerEnableFlag_read_reg_238, ap_CS_fsm_state2, icmp_ln159_fu_186_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((layerEnableFlag_read_reg_238 = ap_const_lv1_0) or (icmp_ln159_fu_186_p2 = ap_const_lv1_0)))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    layerEnableFlag_read_read_fu_116_p2 <= layerEnableFlag;
    loopWidth_fu_162_p2 <= std_logic_vector(unsigned(width) + unsigned(ap_const_lv16_5));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln159_fu_222_p3 <= 
        grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_p_0_0_0206358363_out when (cmp28336_reg_345(0) = '1') else 
        p_0_0_0206358_lcssa409_fu_68;
    srcLayer1Yuv422_read <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_srcLayer1Yuv422_read;
    srcLayer1Yuv_din <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_srcLayer1Yuv_din;
    srcLayer1Yuv_write <= grp_v_mix_422_to_444_true_Pipeline_VITIS_LOOP_161_2_fu_134_srcLayer1Yuv_write;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln159_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_9_fu_56),16));
end behav;
