-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_frmbuf_rd_0_0_MultiPixStream2AXIvideo is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    img_empty_n : IN STD_LOGIC;
    img_read : OUT STD_LOGIC;
    img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC;
    m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    Height_val : IN STD_LOGIC_VECTOR (11 downto 0);
    WidthOut_val : IN STD_LOGIC_VECTOR (11 downto 0);
    colorFormat_val : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of design_1_v_frmbuf_rd_0_0_MultiPixStream2AXIvideo is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal grp_reg_unsigned_short_s_fu_137_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal rows_reg_229 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_reg_unsigned_short_s_fu_143_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal cols_reg_234 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal sub_fu_158_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_reg_239 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal thr_or17_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal thr_or17_reg_244 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal icmp_ln458_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln458_reg_249 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal and_ln458_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln458_reg_257 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_start : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_done : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_idle : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_ready : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_img_read : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TREADY : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_reg_unsigned_short_s_fu_137_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_137_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_137_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_137_ap_ready : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_143_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_143_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_143_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_143_ap_ready : STD_LOGIC;
    signal sof_reg_100 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln458_1_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m_axis_video_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal m_axis_video_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal m_axis_video_TUSER_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal m_axis_video_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal m_axis_video_TID_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal m_axis_video_TDEST_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_block_state1_ignore_call10 : BOOLEAN;
    signal ap_block_state1_ignore_call11 : BOOLEAN;
    signal i_fu_78 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal i_2_fu_196_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln439_fu_154_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal cmp45_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp47_fu_170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_frmbuf_rd_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_empty_n : IN STD_LOGIC;
        img_read : OUT STD_LOGIC;
        img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        m_axis_video_TREADY : IN STD_LOGIC;
        sof : IN STD_LOGIC_VECTOR (0 downto 0);
        cols : IN STD_LOGIC_VECTOR (11 downto 0);
        sub : IN STD_LOGIC_VECTOR (12 downto 0);
        thr_or17 : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axis_video_TVALID : OUT STD_LOGIC;
        m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component design_1_v_frmbuf_rd_0_0_reg_unsigned_short_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        d : IN STD_LOGIC_VECTOR (11 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;



begin
    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112 : component design_1_v_frmbuf_rd_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_start,
        ap_done => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_done,
        ap_idle => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_idle,
        ap_ready => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_ready,
        img_dout => img_dout,
        img_empty_n => img_empty_n,
        img_read => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_img_read,
        img_num_data_valid => ap_const_lv3_0,
        img_fifo_cap => ap_const_lv3_0,
        m_axis_video_TREADY => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TREADY,
        sof => sof_reg_100,
        cols => cols_reg_234,
        sub => sub_reg_239,
        thr_or17 => thr_or17_reg_244,
        m_axis_video_TDATA => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TDATA,
        m_axis_video_TVALID => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID,
        m_axis_video_TKEEP => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TKEEP,
        m_axis_video_TSTRB => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TSTRB,
        m_axis_video_TUSER => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TUSER,
        m_axis_video_TLAST => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TLAST,
        m_axis_video_TID => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TID,
        m_axis_video_TDEST => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TDEST);

    grp_reg_unsigned_short_s_fu_137 : component design_1_v_frmbuf_rd_0_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_137_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_137_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_137_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_137_ap_ready,
        d => Height_val,
        ap_return => grp_reg_unsigned_short_s_fu_137_ap_return);

    grp_reg_unsigned_short_s_fu_143 : component design_1_v_frmbuf_rd_0_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_143_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_143_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_143_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_143_ap_ready,
        d => WidthOut_val,
        ap_return => grp_reg_unsigned_short_s_fu_143_ap_return);





    and_ln458_reg_257_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                and_ln458_reg_257 <= ap_const_lv1_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    and_ln458_reg_257 <= and_ln458_fu_202_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln458_1_fu_191_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    cols_reg_234_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                cols_reg_234 <= ap_const_lv12_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    cols_reg_234 <= grp_reg_unsigned_short_s_fu_143_ap_return;
                end if; 
            end if;
        end if;
    end process;


    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln458_1_fu_191_p2 = ap_const_lv1_0))) then 
                    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_ready = ap_const_logic_1)) then 
                    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_78_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                i_fu_78 <= ap_const_lv12_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    i_fu_78 <= ap_const_lv12_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln458_1_fu_191_p2 = ap_const_lv1_0))) then 
                    i_fu_78 <= i_2_fu_196_p2;
                end if; 
            end if;
        end if;
    end process;


    icmp_ln458_reg_249_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                icmp_ln458_reg_249 <= ap_const_lv1_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    icmp_ln458_reg_249 <= icmp_ln458_fu_182_p2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_TDATA_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_TDATA_reg <= ap_const_lv32_0;
            else
                if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    m_axis_video_TDATA_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TDATA;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_TDEST_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_TDEST_reg <= ap_const_lv1_0;
            else
                if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    m_axis_video_TDEST_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TDEST;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_TID_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_TID_reg <= ap_const_lv1_0;
            else
                if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    m_axis_video_TID_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TID;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_TKEEP_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_TKEEP_reg <= ap_const_lv4_0;
            else
                if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    m_axis_video_TKEEP_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TKEEP;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_TLAST_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_TLAST_reg <= ap_const_lv1_0;
            else
                if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    m_axis_video_TLAST_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TLAST;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_TSTRB_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_TSTRB_reg <= ap_const_lv4_0;
            else
                if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    m_axis_video_TSTRB_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TSTRB;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_TUSER_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_TUSER_reg <= ap_const_lv1_0;
            else
                if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    m_axis_video_TUSER_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TUSER;
                end if; 
            end if;
        end if;
    end process;


    rows_reg_229_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                rows_reg_229 <= ap_const_lv12_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    rows_reg_229 <= grp_reg_unsigned_short_s_fu_137_ap_return;
                end if; 
            end if;
        end if;
    end process;


    sof_reg_100_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                sof_reg_100 <= ap_const_lv1_0;
            else
                if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    sof_reg_100 <= and_ln458_reg_257;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    sof_reg_100 <= ap_const_lv1_1;
                end if; 
            end if;
        end if;
    end process;


    sub_reg_239_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                sub_reg_239 <= ap_const_lv13_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    sub_reg_239 <= sub_fu_158_p2;
                end if; 
            end if;
        end if;
    end process;


    thr_or17_reg_244_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                thr_or17_reg_244 <= ap_const_lv1_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    thr_or17_reg_244 <= thr_or17_fu_176_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state3, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_done, ap_CS_fsm_state4, icmp_ln458_1_fu_191_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln458_1_fu_191_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    and_ln458_fu_202_p2 <= (sof_reg_100 and icmp_ln458_reg_249);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_done)
    begin
        if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call10_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call10 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call11_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call11 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, icmp_ln458_1_fu_191_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln458_1_fu_191_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln458_1_fu_191_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln458_1_fu_191_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cmp45_fu_164_p2 <= "1" when (colorFormat_val = ap_const_lv3_1) else "0";
    cmp47_fu_170_p2 <= "1" when (colorFormat_val = ap_const_lv3_6) else "0";
    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_start <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_ap_start_reg;
    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TREADY <= (m_axis_video_TREADY and ap_CS_fsm_state4);

    grp_reg_unsigned_short_s_fu_137_ap_start_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ap_block_state1_ignore_call10)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_state1_ignore_call10) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_reg_unsigned_short_s_fu_137_ap_start <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_137_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_reg_unsigned_short_s_fu_143_ap_start_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ap_block_state1_ignore_call11)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_state1_ignore_call11) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_reg_unsigned_short_s_fu_143_ap_start <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_143_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_196_p2 <= std_logic_vector(unsigned(i_fu_78) + unsigned(ap_const_lv12_1));
    icmp_ln458_1_fu_191_p2 <= "1" when (i_fu_78 = rows_reg_229) else "0";
    icmp_ln458_fu_182_p2 <= "1" when (grp_reg_unsigned_short_s_fu_143_ap_return = ap_const_lv12_0) else "0";
    img_read <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_img_read;

    m_axis_video_TDATA_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TDATA, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID, ap_CS_fsm_state4, m_axis_video_TDATA_reg)
    begin
        if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axis_video_TDATA <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TDATA;
        else 
            m_axis_video_TDATA <= m_axis_video_TDATA_reg;
        end if; 
    end process;


    m_axis_video_TDEST_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TDEST, ap_CS_fsm_state4, m_axis_video_TDEST_reg)
    begin
        if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axis_video_TDEST <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TDEST;
        else 
            m_axis_video_TDEST <= m_axis_video_TDEST_reg;
        end if; 
    end process;


    m_axis_video_TID_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TID, ap_CS_fsm_state4, m_axis_video_TID_reg)
    begin
        if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axis_video_TID <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TID;
        else 
            m_axis_video_TID <= m_axis_video_TID_reg;
        end if; 
    end process;


    m_axis_video_TKEEP_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TKEEP, ap_CS_fsm_state4, m_axis_video_TKEEP_reg)
    begin
        if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axis_video_TKEEP <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TKEEP;
        else 
            m_axis_video_TKEEP <= m_axis_video_TKEEP_reg;
        end if; 
    end process;


    m_axis_video_TLAST_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TLAST, ap_CS_fsm_state4, m_axis_video_TLAST_reg)
    begin
        if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axis_video_TLAST <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TLAST;
        else 
            m_axis_video_TLAST <= m_axis_video_TLAST_reg;
        end if; 
    end process;


    m_axis_video_TSTRB_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TSTRB, ap_CS_fsm_state4, m_axis_video_TSTRB_reg)
    begin
        if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axis_video_TSTRB <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TSTRB;
        else 
            m_axis_video_TSTRB <= m_axis_video_TSTRB_reg;
        end if; 
    end process;


    m_axis_video_TUSER_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TUSER, ap_CS_fsm_state4, m_axis_video_TUSER_reg)
    begin
        if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axis_video_TUSER <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TUSER;
        else 
            m_axis_video_TUSER <= m_axis_video_TUSER_reg;
        end if; 
    end process;

    m_axis_video_TVALID <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_460_2_fu_112_m_axis_video_TVALID;
    sub_fu_158_p2 <= std_logic_vector(unsigned(zext_ln439_fu_154_p1) + unsigned(ap_const_lv13_1FFF));
    thr_or17_fu_176_p2 <= (cmp47_fu_170_p2 or cmp45_fu_164_p2);
    zext_ln439_fu_154_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_reg_unsigned_short_s_fu_143_ap_return),13));
end behav;
