-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_mix_0_0_AXIvideo2MultiPixStream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    s_axis_video2_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    s_axis_video2_TVALID : IN STD_LOGIC;
    s_axis_video2_TREADY : OUT STD_LOGIC;
    s_axis_video2_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    s_axis_video2_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    s_axis_video2_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video2_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video2_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    srcLayer2_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    srcLayer2_full_n : IN STD_LOGIC;
    srcLayer2_write : OUT STD_LOGIC;
    srcLayer2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerHeight_2_val : IN STD_LOGIC_VECTOR (11 downto 0);
    HwReg_layerWidth_2_val : IN STD_LOGIC_VECTOR (11 downto 0);
    HwReg_layerEnableFlag_2_val : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of design_1_v_mix_0_0_AXIvideo2MultiPixStream is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal HwReg_layerEnableFlag_2_val_read_read_fu_112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal HwReg_layerEnableFlag_2_val_read_reg_437 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_reg_unsigned_short_s_fu_211_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal rows_reg_441 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_reg_unsigned_short_s_fu_217_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal cols_reg_446 : STD_LOGIC_VECTOR (11 downto 0);
    signal cmp10403_i_i_fu_269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp10403_i_i_reg_469 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal xor_ln3436_fu_274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln3436_reg_474 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln3436_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln3436_reg_485 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal select_ln3436_fu_354_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln3436_reg_496 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_s_axis_video2_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_data_i_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_data_i_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_last_i_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_last_i_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_srcLayer2_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_srcLayer2_write : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_s_axis_video2_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_eol_i_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_eol_i_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_axi_data_18_i_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_axi_data_18_i_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_s_axis_video2_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_data_19_i_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_data_19_i_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_last_23_i_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_last_23_i_out_ap_vld : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_211_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_211_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_211_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_211_ap_ready : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_211_ap_ce : STD_LOGIC;
    signal ap_block_state1_ignore_call13 : BOOLEAN;
    signal grp_reg_unsigned_short_s_fu_217_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_217_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_217_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_217_ap_ready : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_217_ap_ce : STD_LOGIC;
    signal ap_block_state1_ignore_call14 : BOOLEAN;
    signal sof_reg_118 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal axi_last_reg_130 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal axi_data_fu_92 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln3387_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal axi_last_23_i_loc_fu_76 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_96 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal i_8_fu_288_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_mix_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video2_TVALID : IN STD_LOGIC;
        s_axis_video2_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        s_axis_video2_TREADY : OUT STD_LOGIC;
        s_axis_video2_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video2_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video2_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video2_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video2_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_i_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        axi_data_i_out_ap_vld : OUT STD_LOGIC;
        axi_last_i_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        axi_last_i_out_ap_vld : OUT STD_LOGIC );
    end component;


    component design_1_v_mix_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video2_TVALID : IN STD_LOGIC;
        srcLayer2_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        srcLayer2_full_n : IN STD_LOGIC;
        srcLayer2_write : OUT STD_LOGIC;
        srcLayer2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        sof_10_i : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_last_21_i : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_17_i : IN STD_LOGIC_VECTOR (23 downto 0);
        cols_i : IN STD_LOGIC_VECTOR (11 downto 0);
        s_axis_video2_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        s_axis_video2_TREADY : OUT STD_LOGIC;
        s_axis_video2_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video2_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video2_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video2_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video2_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        eol_i_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        eol_i_out_ap_vld : OUT STD_LOGIC;
        axi_data_18_i_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        axi_data_18_i_out_ap_vld : OUT STD_LOGIC );
    end component;


    component design_1_v_mix_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video2_TVALID : IN STD_LOGIC;
        axi_data_18_i_reload : IN STD_LOGIC_VECTOR (23 downto 0);
        select_ln3436_i : IN STD_LOGIC_VECTOR (0 downto 0);
        eol_i_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video2_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        s_axis_video2_TREADY : OUT STD_LOGIC;
        s_axis_video2_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video2_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video2_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video2_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video2_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_19_i_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        axi_data_19_i_out_ap_vld : OUT STD_LOGIC;
        axi_last_23_i_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        axi_last_23_i_out_ap_vld : OUT STD_LOGIC );
    end component;


    component design_1_v_mix_0_0_reg_unsigned_short_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        d : IN STD_LOGIC_VECTOR (11 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;



begin
    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140 : component design_1_v_mix_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_ready,
        s_axis_video2_TVALID => s_axis_video2_TVALID,
        s_axis_video2_TDATA => s_axis_video2_TDATA,
        s_axis_video2_TREADY => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_s_axis_video2_TREADY,
        s_axis_video2_TKEEP => s_axis_video2_TKEEP,
        s_axis_video2_TSTRB => s_axis_video2_TSTRB,
        s_axis_video2_TUSER => s_axis_video2_TUSER,
        s_axis_video2_TLAST => s_axis_video2_TLAST,
        s_axis_video2_TID => s_axis_video2_TID,
        s_axis_video2_TDEST => s_axis_video2_TDEST,
        axi_data_i_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_data_i_out,
        axi_data_i_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_data_i_out_ap_vld,
        axi_last_i_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_last_i_out,
        axi_last_i_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_last_i_out_ap_vld);

    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160 : component design_1_v_mix_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_ready,
        s_axis_video2_TVALID => s_axis_video2_TVALID,
        srcLayer2_din => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_srcLayer2_din,
        srcLayer2_full_n => srcLayer2_full_n,
        srcLayer2_write => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_srcLayer2_write,
        srcLayer2_num_data_valid => ap_const_lv3_0,
        srcLayer2_fifo_cap => ap_const_lv3_0,
        sof_10_i => sof_reg_118,
        axi_last_21_i => axi_last_reg_130,
        axi_data_17_i => axi_data_fu_92,
        cols_i => cols_reg_446,
        s_axis_video2_TDATA => s_axis_video2_TDATA,
        s_axis_video2_TREADY => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_s_axis_video2_TREADY,
        s_axis_video2_TKEEP => s_axis_video2_TKEEP,
        s_axis_video2_TSTRB => s_axis_video2_TSTRB,
        s_axis_video2_TUSER => s_axis_video2_TUSER,
        s_axis_video2_TLAST => s_axis_video2_TLAST,
        s_axis_video2_TID => s_axis_video2_TID,
        s_axis_video2_TDEST => s_axis_video2_TDEST,
        eol_i_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_eol_i_out,
        eol_i_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_eol_i_out_ap_vld,
        axi_data_18_i_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_axi_data_18_i_out,
        axi_data_18_i_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_axi_data_18_i_out_ap_vld);

    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188 : component design_1_v_mix_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_ready,
        s_axis_video2_TVALID => s_axis_video2_TVALID,
        axi_data_18_i_reload => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_axi_data_18_i_out,
        select_ln3436_i => select_ln3436_reg_496,
        eol_i_reload => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_eol_i_out,
        s_axis_video2_TDATA => s_axis_video2_TDATA,
        s_axis_video2_TREADY => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_s_axis_video2_TREADY,
        s_axis_video2_TKEEP => s_axis_video2_TKEEP,
        s_axis_video2_TSTRB => s_axis_video2_TSTRB,
        s_axis_video2_TUSER => s_axis_video2_TUSER,
        s_axis_video2_TLAST => s_axis_video2_TLAST,
        s_axis_video2_TID => s_axis_video2_TID,
        s_axis_video2_TDEST => s_axis_video2_TDEST,
        axi_data_19_i_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_data_19_i_out,
        axi_data_19_i_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_data_19_i_out_ap_vld,
        axi_last_23_i_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_last_23_i_out,
        axi_last_23_i_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_last_23_i_out_ap_vld);

    grp_reg_unsigned_short_s_fu_211 : component design_1_v_mix_0_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_211_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_211_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_211_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_211_ap_ready,
        ap_ce => grp_reg_unsigned_short_s_fu_211_ap_ce,
        d => HwReg_layerHeight_2_val,
        ap_return => grp_reg_unsigned_short_s_fu_211_ap_return);

    grp_reg_unsigned_short_s_fu_217 : component design_1_v_mix_0_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_217_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_217_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_217_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_217_ap_ready,
        ap_ce => grp_reg_unsigned_short_s_fu_217_ap_ce,
        d => HwReg_layerWidth_2_val,
        ap_return => grp_reg_unsigned_short_s_fu_217_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and ((ap_const_lv1_0 = HwReg_layerEnableFlag_2_val_read_reg_437) or (icmp_ln3387_fu_283_p2 = ap_const_lv1_1)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_lv1_1 = HwReg_layerEnableFlag_2_val_read_read_fu_112_p2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln3387_fu_283_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = HwReg_layerEnableFlag_2_val_read_reg_437) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axi_data_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_data_19_i_out_ap_vld = ap_const_logic_1))) then 
                axi_data_fu_92 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_data_19_i_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_data_i_out_ap_vld = ap_const_logic_1))) then 
                axi_data_fu_92 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_data_i_out;
            end if; 
        end if;
    end process;

    axi_last_reg_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                axi_last_reg_130 <= axi_last_23_i_loc_fu_76;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                axi_last_reg_130 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_last_i_out;
            end if; 
        end if;
    end process;

    i_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = HwReg_layerEnableFlag_2_val_read_read_fu_112_p2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_fu_96 <= ap_const_lv12_0;
            elsif (((icmp_ln3387_fu_283_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = HwReg_layerEnableFlag_2_val_read_reg_437) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i_fu_96 <= i_8_fu_288_p2;
            end if; 
        end if;
    end process;

    sof_reg_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                sof_reg_118 <= and_ln3436_reg_485;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                sof_reg_118 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                HwReg_layerEnableFlag_2_val_read_reg_437 <= HwReg_layerEnableFlag_2_val;
                cols_reg_446 <= grp_reg_unsigned_short_s_fu_217_ap_return;
                rows_reg_441 <= grp_reg_unsigned_short_s_fu_211_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                and_ln3436_reg_485 <= and_ln3436_fu_298_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_last_23_i_out_ap_vld = ap_const_logic_1))) then
                axi_last_23_i_loc_fu_76 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_last_23_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                cmp10403_i_i_reg_469 <= cmp10403_i_i_fu_269_p2;
                xor_ln3436_reg_474 <= xor_ln3436_fu_274_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                select_ln3436_reg_496 <= select_ln3436_fu_354_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, HwReg_layerEnableFlag_2_val_read_read_fu_112_p2, HwReg_layerEnableFlag_2_val_read_reg_437, ap_CS_fsm_state2, ap_CS_fsm_state5, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_done, grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_done, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_done, ap_CS_fsm_state3, icmp_ln3387_fu_283_p2, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_lv1_0 = HwReg_layerEnableFlag_2_val_read_read_fu_112_p2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and ((ap_const_lv1_0 = HwReg_layerEnableFlag_2_val_read_reg_437) or (icmp_ln3387_fu_283_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    HwReg_layerEnableFlag_2_val_read_read_fu_112_p2 <= HwReg_layerEnableFlag_2_val;
    and_ln3436_fu_298_p2 <= (xor_ln3436_reg_474 and sof_reg_118);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call13_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call13 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call14_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call14 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, HwReg_layerEnableFlag_2_val_read_reg_437, ap_CS_fsm_state5, icmp_ln3387_fu_283_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and ((ap_const_lv1_0 = HwReg_layerEnableFlag_2_val_read_reg_437) or (icmp_ln3387_fu_283_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    cmp10403_i_i_fu_269_p2 <= "0" when (cols_reg_446 = ap_const_lv12_0) else "1";
    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start_reg;
    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start_reg;
    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start_reg;

    grp_reg_unsigned_short_s_fu_211_ap_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state1_ignore_call13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_state1_ignore_call13) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_reg_unsigned_short_s_fu_211_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_211_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_reg_unsigned_short_s_fu_211_ap_start_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ap_block_state1_ignore_call13)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_state1_ignore_call13) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_reg_unsigned_short_s_fu_211_ap_start <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_211_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_reg_unsigned_short_s_fu_217_ap_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state1_ignore_call14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_state1_ignore_call14) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_reg_unsigned_short_s_fu_217_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_217_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_reg_unsigned_short_s_fu_217_ap_start_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ap_block_state1_ignore_call14)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_state1_ignore_call14) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_reg_unsigned_short_s_fu_217_ap_start <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_217_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    i_8_fu_288_p2 <= std_logic_vector(unsigned(i_fu_96) + unsigned(ap_const_lv12_1));
    icmp_ln3387_fu_283_p2 <= "1" when (i_fu_96 = rows_reg_441) else "0";

    internal_ap_ready_assign_proc : process(HwReg_layerEnableFlag_2_val_read_reg_437, ap_CS_fsm_state5, icmp_ln3387_fu_283_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and ((ap_const_lv1_0 = HwReg_layerEnableFlag_2_val_read_reg_437) or (icmp_ln3387_fu_283_p2 = ap_const_lv1_1)))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    s_axis_video2_TREADY_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_s_axis_video2_TREADY, grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_s_axis_video2_TREADY, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_s_axis_video2_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            s_axis_video2_TREADY <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_s_axis_video2_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            s_axis_video2_TREADY <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_s_axis_video2_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            s_axis_video2_TREADY <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_s_axis_video2_TREADY;
        else 
            s_axis_video2_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    select_ln3436_fu_354_p3 <= 
        grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_eol_i_out when (cmp10403_i_i_reg_469(0) = '1') else 
        axi_last_reg_130;
    srcLayer2_din <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_srcLayer2_din;
    srcLayer2_write <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_srcLayer2_write;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln3436_fu_274_p2 <= (cmp10403_i_i_fu_269_p2 xor ap_const_lv1_1);
end behav;
