#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XAXIPMON_NUM_INSTANCES 2

/* Definitions for peripheral PERF_MONITOR_OCM */
#define XPAR_PERF_MONITOR_OCM_COMPATIBLE "xlnx,axi-perf-monitor"
#define XPAR_PERF_MONITOR_OCM_BASEADDR 0xffa00000
#define XPAR_PERF_MONITOR_OCM_HIGHADDR 0xffa0ffff
#define XPAR_PERF_MONITOR_OCM_GLOBAL_COUNT_WIDTH 0x20
#define XPAR_PERF_MONITOR_OCM_METRICS_SAMPLE_COUNT_WIDTH 0x20
#define XPAR_PERF_MONITOR_OCM_ENABLE_EVENT_COUNT 0x1
#define XPAR_PERF_MONITOR_OCM_NUM_MONITOR_SLOTS 0x1
#define XPAR_PERF_MONITOR_OCM_NUM_OF_COUNTERS 0x3
#define XPAR_PERF_MONITOR_OCM_HAVE_SAMPLED_METRIC_CNT 0x1
#define XPAR_PERF_MONITOR_OCM_ENABLE_EVENT_LOG 0x0
#define XPAR_PERF_MONITOR_OCM_FIFO_AXIS_DEPTH 0x20
#define XPAR_PERF_MONITOR_OCM_FIFO_AXIS_TDATA_WIDTH 0x38
#define XPAR_PERF_MONITOR_OCM_FIFO_AXIS_TID_WIDTH 0x1
#define XPAR_PERF_MONITOR_OCM_METRIC_COUNT_SCALE 0x1
#define XPAR_PERF_MONITOR_OCM_ENABLE_ADVANCED 0x1
#define XPAR_PERF_MONITOR_OCM_ENABLE_PROFILE 0x0
#define XPAR_PERF_MONITOR_OCM_ENABLE_TRACE 0x0
#define XPAR_PERF_MONITOR_OCM_ENABLE_32BIT_FILTER_ID 0x1
#define XPAR_PERF_MONITOR_OCM_INTERRUPTS 0x4019

/* Canonical definitions for peripheral PERF_MONITOR_OCM */
#define XPAR_XAXIPMON_0_BASEADDR 0xffa00000
#define XPAR_XAXIPMON_0_HIGHADDR 0xffa0ffff
#define XPAR_XAXIPMON_0_COMPATIBLE "xlnx,axi-perf-monitor"
#define XPAR_XAXIPMON_0_ENABLE_EVENT_COUNT 0x1
#define XPAR_XAXIPMON_0_ENABLE_EVENT_LOG 0x0
#define XPAR_XAXIPMON_0_ENABLE_ADVANCED 0x1
#define XPAR_XAXIPMON_0_ENABLE_PROFILE 0x0
#define XPAR_XAXIPMON_0_ENABLE_TRACE 0x0
#define XPAR_XAXIPMON_0_ENABLE_32BIT_FILTER_ID 0x1
#define XPAR_XAXIPMON_0_FIFO_AXIS_DEPTH 0x20
#define XPAR_XAXIPMON_0_FIFO_AXIS_TDATA_WIDTH 0x38
#define XPAR_XAXIPMON_0_FIFO_AXIS_TID_WIDTH 0x1
#define XPAR_XAXIPMON_0_GLOBAL_COUNT_WIDTH 0x20
#define XPAR_XAXIPMON_0_HAVE_SAMPLED_METRIC_CNT 0x1
#define XPAR_XAXIPMON_0_INTERRUPTS 0x4019
#define XPAR_XAXIPMON_0_METRICS_SAMPLE_COUNT_WIDTH 0x20
#define XPAR_XAXIPMON_0_METRIC_COUNT_SCALE 0x1
#define XPAR_XAXIPMON_0_NUM_MONITOR_SLOTS 0x1
#define XPAR_XAXIPMON_0_NUM_OF_COUNTERS 0x3

/* Definitions for peripheral PERF_MONITOR_LPD */
#define XPAR_PERF_MONITOR_LPD_COMPATIBLE "xlnx,axi-perf-monitor"
#define XPAR_PERF_MONITOR_LPD_BASEADDR 0xffa10000
#define XPAR_PERF_MONITOR_LPD_HIGHADDR 0xffa1ffff
#define XPAR_PERF_MONITOR_LPD_GLOBAL_COUNT_WIDTH 0x20
#define XPAR_PERF_MONITOR_LPD_METRICS_SAMPLE_COUNT_WIDTH 0x20
#define XPAR_PERF_MONITOR_LPD_ENABLE_EVENT_COUNT 0x1
#define XPAR_PERF_MONITOR_LPD_NUM_MONITOR_SLOTS 0x1
#define XPAR_PERF_MONITOR_LPD_NUM_OF_COUNTERS 0x3
#define XPAR_PERF_MONITOR_LPD_HAVE_SAMPLED_METRIC_CNT 0x1
#define XPAR_PERF_MONITOR_LPD_ENABLE_EVENT_LOG 0x0
#define XPAR_PERF_MONITOR_LPD_FIFO_AXIS_DEPTH 0x20
#define XPAR_PERF_MONITOR_LPD_FIFO_AXIS_TDATA_WIDTH 0x38
#define XPAR_PERF_MONITOR_LPD_FIFO_AXIS_TID_WIDTH 0x1
#define XPAR_PERF_MONITOR_LPD_METRIC_COUNT_SCALE 0x1
#define XPAR_PERF_MONITOR_LPD_ENABLE_ADVANCED 0x1
#define XPAR_PERF_MONITOR_LPD_ENABLE_PROFILE 0x0
#define XPAR_PERF_MONITOR_LPD_ENABLE_TRACE 0x0
#define XPAR_PERF_MONITOR_LPD_ENABLE_32BIT_FILTER_ID 0x1
#define XPAR_PERF_MONITOR_LPD_INTERRUPTS 0x4019

/* Canonical definitions for peripheral PERF_MONITOR_LPD */
#define XPAR_XAXIPMON_1_BASEADDR 0xffa10000
#define XPAR_XAXIPMON_1_HIGHADDR 0xffa1ffff
#define XPAR_XAXIPMON_1_COMPATIBLE "xlnx,axi-perf-monitor"
#define XPAR_XAXIPMON_1_ENABLE_EVENT_COUNT 0x1
#define XPAR_XAXIPMON_1_ENABLE_EVENT_LOG 0x0
#define XPAR_XAXIPMON_1_ENABLE_ADVANCED 0x1
#define XPAR_XAXIPMON_1_ENABLE_PROFILE 0x0
#define XPAR_XAXIPMON_1_ENABLE_TRACE 0x0
#define XPAR_XAXIPMON_1_ENABLE_32BIT_FILTER_ID 0x1
#define XPAR_XAXIPMON_1_FIFO_AXIS_DEPTH 0x20
#define XPAR_XAXIPMON_1_FIFO_AXIS_TDATA_WIDTH 0x38
#define XPAR_XAXIPMON_1_FIFO_AXIS_TID_WIDTH 0x1
#define XPAR_XAXIPMON_1_GLOBAL_COUNT_WIDTH 0x20
#define XPAR_XAXIPMON_1_HAVE_SAMPLED_METRIC_CNT 0x1
#define XPAR_XAXIPMON_1_INTERRUPTS 0x4019
#define XPAR_XAXIPMON_1_METRICS_SAMPLE_COUNT_WIDTH 0x20
#define XPAR_XAXIPMON_1_METRIC_COUNT_SCALE 0x1
#define XPAR_XAXIPMON_1_NUM_MONITOR_SLOTS 0x1
#define XPAR_XAXIPMON_1_NUM_OF_COUNTERS 0x3

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x90000000
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x9001ffff
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 0x20
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 0x2

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_XBRAM_0_BASEADDR 0x90000000
#define XPAR_XBRAM_0_HIGHADDR 0x9001ffff
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_XBRAM_0_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_XBRAM_0_FAULT_INJECT 0x0
#define XPAR_XBRAM_0_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_WRITE_ACCESS 0x2

#define XPAR_XCLOCKPS_NUM_INSTANCES 1

/* Definitions for peripheral PSU_CRL_APB */
#define XPAR_PSU_CRL_APB_COMPATIBLE "xlnx,psu-crl-apb-1.0"
#define XPAR_PSU_CRL_APB_BASEADDR 0xff5e0000
#define XPAR_PSU_CRL_APB_HIGHADDR 0xff85ffff
#define XPAR_PSU_CRL_APB_BASEADDR_1 0xff5e0000
#define XPAR_PSU_CRL_APB_BASEADDR_2 0xff800000

/* Canonical definitions for peripheral PSU_CRL_APB */
#define XPAR_XCLOCKPS_0_BASEADDR 0xff5e0000
#define XPAR_XCLOCKPS_0_HIGHADDR 0xff85ffff
#define XPAR_XCLOCKPS_0_COMPATIBLE "xlnx,psu-crl-apb-1.0"

#define XPAR_XCSUDMA_NUM_INSTANCES 1

/* Definitions for peripheral CSUDMA_0 */
#define XPAR_CSUDMA_0_COMPATIBLE "xlnx,zynqmp-csudma-1.0"
#define XPAR_CSUDMA_0_BASEADDR 0xffc80000
#define XPAR_CSUDMA_0_HIGHADDR 0xffcbffff
#define XPAR_CSUDMA_0_DMA_TYPE 0x0
#define XPAR_CSUDMA_0_INTERRUPTS 0x4056

/* Canonical definitions for peripheral CSUDMA_0 */
#define XPAR_XCSUDMA_0_BASEADDR 0xffc80000
#define XPAR_XCSUDMA_0_HIGHADDR 0xffcbffff
#define XPAR_XCSUDMA_0_COMPATIBLE "xlnx,zynqmp-csudma-1.0"
#define XPAR_XCSUDMA_0_DMA_TYPE 0x0
#define XPAR_XCSUDMA_0_INTERRUPTS 0x4056

#define XPAR_XEMACPS_NUM_INSTANCES 1

/* Definitions for peripheral GEM3 */
#define XPAR_GEM3_COMPATIBLE "xlnx,zynqmp-gem"
#define XPAR_GEM3_BASEADDR 0xff0e0000
#define XPAR_GEM3_HIGHADDR 0xff0e0fff
#define XPAR_GEM3_INTERRUPTS 0x403f
#define XPAR_GEM3_INTERRUPTS_1 0x403f
#define XPAR_GEM3_PHY_MODE "rgmii-id"

/* Canonical definitions for peripheral GEM3 */
#define XPAR_XEMACPS_0_BASEADDR 0xff0e0000
#define XPAR_XEMACPS_0_HIGHADDR 0xff0e0fff
#define XPAR_XEMACPS_0_COMPATIBLE "xlnx,zynqmp-gem"
#define XPAR_XEMACPS_0_INTERRUPTS 0x403f
#define XPAR_XEMACPS_0_PHY_MODE "rgmii-id"

#define XPAR_XGPIO_NUM_INSTANCES 2

/* Definitions for peripheral AXI_GPIO_1 */
#define XPAR_AXI_GPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_1_BASEADDR 0x80000000
#define XPAR_AXI_GPIO_1_HIGHADDR 0x8000ffff
#define XPAR_AXI_GPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_1_IS_DUAL 0x0
#define XPAR_AXI_GPIO_1_GPIO_WIDTH 0x8

/* Canonical definitions for peripheral AXI_GPIO_1 */
#define XPAR_XGPIO_0_BASEADDR 0x80000000
#define XPAR_XGPIO_0_HIGHADDR 0x8000ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x8
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x0

/* Definitions for peripheral PL_PS_INTR */
#define XPAR_PL_PS_INTR_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_PL_PS_INTR_BASEADDR 0x80020000
#define XPAR_PL_PS_INTR_HIGHADDR 0x8002ffff
#define XPAR_PL_PS_INTR_INTERRUPT_PRESENT 0x0
#define XPAR_PL_PS_INTR_IS_DUAL 0x0
#define XPAR_PL_PS_INTR_GPIO_WIDTH 0x1

/* Canonical definitions for peripheral PL_PS_INTR */
#define XPAR_XGPIO_1_BASEADDR 0x80020000
#define XPAR_XGPIO_1_HIGHADDR 0x8002ffff
#define XPAR_XGPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_1_GPIO_WIDTH 0x1
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x0

#define XPAR_XGPIOPS_NUM_INSTANCES 1

/* Definitions for peripheral GPIO */
#define XPAR_GPIO_COMPATIBLE "xlnx,zynqmp-gpio-1.0"
#define XPAR_GPIO_BASEADDR 0xff0a0000
#define XPAR_GPIO_HIGHADDR 0xff0a0fff
#define XPAR_GPIO_INTERRUPTS 0x4010

/* Canonical definitions for peripheral GPIO */
#define XPAR_XGPIOPS_0_BASEADDR 0xff0a0000
#define XPAR_XGPIOPS_0_HIGHADDR 0xff0a0fff
#define XPAR_XGPIOPS_0_COMPATIBLE "xlnx,zynqmp-gpio-1.0"
#define XPAR_XGPIOPS_0_INTERRUPTS 0x4010

#define XPAR_XIICPS_NUM_INSTANCES 1

/* Definitions for peripheral I2C1 */
#define XPAR_I2C1_COMPATIBLE "cdns,i2c-r1p14"
#define XPAR_I2C1_BASEADDR 0xff030000
#define XPAR_I2C1_HIGHADDR 0xff030fff
#define XPAR_I2C1_CLOCK_FREQ 0x5f5dd19
#define XPAR_I2C1_INTERRUPTS 0x4012
#define XPAR_I2C1_CLOCKS 0x3e

/* Canonical definitions for peripheral I2C1 */
#define XPAR_XIICPS_0_BASEADDR 0xff030000
#define XPAR_XIICPS_0_HIGHADDR 0xff030fff
#define XPAR_XIICPS_0_COMPATIBLE "cdns,i2c-r1p14"
#define XPAR_XIICPS_0_CLOCK_FREQ 0x5f5dd19
#define XPAR_XIICPS_0_CLOCKS 0x3e
#define XPAR_XIICPS_0_INTERRUPTS 0x4012

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_INTC_0 */
#define XPAR_AXI_INTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_AXI_INTC_0_BASEADDR 0x80010000
#define XPAR_AXI_INTC_0_HIGHADDR 0x8001ffff
#define XPAR_AXI_INTC_0_KIND_OF_INTR 0x0
#define XPAR_AXI_INTC_0_IS_FAST 0x0
#define XPAR_AXI_INTC_0_IVAR_RST_VAL 0x10
#define XPAR_AXI_INTC_0_NUM_INTR_INPUTS 0x1
#define XPAR_AXI_INTC_0_ADDR_WIDTH 0x20
#define XPAR_AXI_INTC_0_NUM_SW_INTR 0x0
#define XPAR_AXI_INTC_0_HAS_IVR 0x0
#define XPAR_AXI_INTC_0_HAS_CIE 0x0
#define XPAR_AXI_INTC_0_HAS_SIE 0x0
#define XPAR_AXI_INTC_0_HAS_IPR 0x1

/* Canonical definitions for peripheral AXI_INTC_0 */
#define XPAR_XINTC_0_BASEADDR 0x80010000
#define XPAR_XINTC_0_HIGHADDR 0x8001ffff
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_HAS_IVR 0x0
#define XPAR_XINTC_0_HAS_CIE 0x0
#define XPAR_XINTC_0_HAS_SIE 0x0
#define XPAR_XINTC_0_HAS_IPR 0x1
#define XPAR_XINTC_0_IS_FAST 0x0
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_KIND_OF_INTR 0x0
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x1
#define XPAR_XINTC_0_NUM_SW_INTR 0x0

#define XPAR_XQSPIPSU_NUM_INSTANCES 1

/* Definitions for peripheral QSPI */
#define XPAR_QSPI_COMPATIBLE "xlnx,zynqmp-qspi-1.0"
#define XPAR_QSPI_BASEADDR 0xff0f0000
#define XPAR_QSPI_HIGHADDR 0xff0f0fff
#define XPAR_QSPI_BASEADDR_1 0xc0000000
#define XPAR_QSPI_CLOCK_FREQ 0x773545d
#define XPAR_QSPI_CONNECTION_MODE 0x2
#define XPAR_QSPI_BUS_WIDTH 0x2
#define XPAR_QSPI_INTERRUPTS 0x400f
#define XPAR_QSPI_CLOCKS 0x35
#define XPAR_QSPI_QSPI_FBCLK 0x0

/* Canonical definitions for peripheral QSPI */
#define XPAR_XQSPIPSU_0_BASEADDR 0xff0f0000
#define XPAR_XQSPIPSU_0_HIGHADDR 0xff0f0fff
#define XPAR_XQSPIPSU_0_BUS_WIDTH 0x2
#define XPAR_XQSPIPSU_0_COMPATIBLE "xlnx,zynqmp-qspi-1.0"
#define XPAR_XQSPIPSU_0_CLOCK_FREQ 0x773545d
#define XPAR_XQSPIPSU_0_CONNECTION_MODE 0x2
#define XPAR_XQSPIPSU_0_CLOCKS 0x35
#define XPAR_XQSPIPSU_0_INTERRUPTS 0x400f
#define XPAR_XQSPIPSU_0_QSPI_FBCLK 0x0

#define XPAR_XRTCPSU_NUM_INSTANCES 1

/* Definitions for peripheral RTC */
#define XPAR_RTC_COMPATIBLE "xlnx,zynqmp-rtc"
#define XPAR_RTC_BASEADDR 0xffa60000
#define XPAR_RTC_HIGHADDR 0xffa600ff
#define XPAR_RTC_INTERRUPTS 0x401a
#define XPAR_RTC_INTERRUPTS_1 0x401b

/* Canonical definitions for peripheral RTC */
#define XPAR_XRTCPSU_0_BASEADDR 0xffa60000
#define XPAR_XRTCPSU_0_HIGHADDR 0xffa600ff
#define XPAR_XRTCPSU_0_COMPATIBLE "xlnx,zynqmp-rtc"
#define XPAR_XRTCPSU_0_INTERRUPTS 0x401a

#define XPAR_XSDPS_NUM_INSTANCES 2

/* Definitions for peripheral SDHCI0 */
#define XPAR_SDHCI0_COMPATIBLE "xlnx,zynqmp-8.9a"
#define XPAR_SDHCI0_BASEADDR 0xff160000
#define XPAR_SDHCI0_HIGHADDR 0xff160fff
#define XPAR_SDHCI0_SDIO_CLK_FREQ_HZ 0xbebba31
#define XPAR_SDHCI0_HAS_CD 0x0
#define XPAR_SDHCI0_HAS_WP 0x0
#define XPAR_SDHCI0_BUS_WIDTH 0x8
#define XPAR_SDHCI0_MIO_BANK 0x0
#define XPAR_SDHCI0_HAS_EMIO 0x0
#define XPAR_SDHCI0_SLOT_TYPE 0x1
#define XPAR_SDHCI0_IS_CACHE_COHERENT 0x0
#define XPAR_SDHCI0_CLOCKS 0x36
#define XPAR_SDHCI0_CLK_50_SDR_ITAP_DLY 0x15
#define XPAR_SDHCI0_CLK_50_SDR_OTAP_DLY 0x6
#define XPAR_SDHCI0_CLK_50_DDR_ITAP_DLY 0x12
#define XPAR_SDHCI0_CLK_50_DDR_OTAP_DLY 0x6
#define XPAR_SDHCI0_CLK_100_SDR_OTAP_DLY 0x0
#define XPAR_SDHCI0_CLK_200_SDR_OTAP_DLY 0x3

/* Canonical definitions for peripheral SDHCI0 */
#define XPAR_XSDPS_0_BASEADDR 0xff160000
#define XPAR_XSDPS_0_HIGHADDR 0xff160fff
#define XPAR_XSDPS_0_BUS_WIDTH 0x8
#define XPAR_XSDPS_0_COMPATIBLE "xlnx,zynqmp-8.9a"
#define XPAR_XSDPS_0_CLOCKS 0x36
#define XPAR_XSDPS_0_CLK_50_SDR_ITAP_DLY 0x15
#define XPAR_XSDPS_0_CLK_50_SDR_OTAP_DLY 0x6
#define XPAR_XSDPS_0_CLK_50_DDR_ITAP_DLY 0x12
#define XPAR_XSDPS_0_CLK_50_DDR_OTAP_DLY 0x6
#define XPAR_XSDPS_0_CLK_100_SDR_OTAP_DLY 0x0
#define XPAR_XSDPS_0_CLK_200_SDR_OTAP_DLY 0x3
#define XPAR_XSDPS_0_HAS_CD 0x0
#define XPAR_XSDPS_0_HAS_WP 0x0
#define XPAR_XSDPS_0_HAS_EMIO 0x0
#define XPAR_XSDPS_0_IS_CACHE_COHERENT 0x0
#define XPAR_XSDPS_0_MIO_BANK 0x0
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 0xbebba31
#define XPAR_XSDPS_0_SLOT_TYPE 0x1

/* Definitions for peripheral SDHCI1 */
#define XPAR_SDHCI1_COMPATIBLE "xlnx,zynqmp-8.9a"
#define XPAR_SDHCI1_BASEADDR 0xff170000
#define XPAR_SDHCI1_HIGHADDR 0xff170fff
#define XPAR_SDHCI1_SDIO_CLK_FREQ_HZ 0xbebba31
#define XPAR_SDHCI1_HAS_CD 0x0
#define XPAR_SDHCI1_HAS_WP 0x1
#define XPAR_SDHCI1_BUS_WIDTH 0x4
#define XPAR_SDHCI1_MIO_BANK 0x1
#define XPAR_SDHCI1_HAS_EMIO 0x0
#define XPAR_SDHCI1_SLOT_TYPE 0x2
#define XPAR_SDHCI1_IS_CACHE_COHERENT 0x0
#define XPAR_SDHCI1_CLOCKS 0x37
#define XPAR_SDHCI1_CLK_50_SDR_ITAP_DLY 0x15
#define XPAR_SDHCI1_CLK_50_SDR_OTAP_DLY 0x5
#define XPAR_SDHCI1_CLK_50_DDR_ITAP_DLY 0x0
#define XPAR_SDHCI1_CLK_50_DDR_OTAP_DLY 0x0
#define XPAR_SDHCI1_CLK_100_SDR_OTAP_DLY 0x0
#define XPAR_SDHCI1_CLK_200_SDR_OTAP_DLY 0x0

/* Canonical definitions for peripheral SDHCI1 */
#define XPAR_XSDPS_1_BASEADDR 0xff170000
#define XPAR_XSDPS_1_HIGHADDR 0xff170fff
#define XPAR_XSDPS_1_BUS_WIDTH 0x4
#define XPAR_XSDPS_1_COMPATIBLE "xlnx,zynqmp-8.9a"
#define XPAR_XSDPS_1_CLOCKS 0x37
#define XPAR_XSDPS_1_CLK_50_SDR_ITAP_DLY 0x15
#define XPAR_XSDPS_1_CLK_50_SDR_OTAP_DLY 0x5
#define XPAR_XSDPS_1_CLK_50_DDR_ITAP_DLY 0x0
#define XPAR_XSDPS_1_CLK_50_DDR_OTAP_DLY 0x0
#define XPAR_XSDPS_1_CLK_100_SDR_OTAP_DLY 0x0
#define XPAR_XSDPS_1_CLK_200_SDR_OTAP_DLY 0x0
#define XPAR_XSDPS_1_HAS_CD 0x0
#define XPAR_XSDPS_1_HAS_WP 0x1
#define XPAR_XSDPS_1_HAS_EMIO 0x0
#define XPAR_XSDPS_1_IS_CACHE_COHERENT 0x0
#define XPAR_XSDPS_1_MIO_BANK 0x1
#define XPAR_XSDPS_1_SDIO_CLK_FREQ_HZ 0xbebba31
#define XPAR_XSDPS_1_SLOT_TYPE 0x2

#define XPAR_XSPIPS_NUM_INSTANCES 1

/* Definitions for peripheral SPI0 */
#define XPAR_SPI0_COMPATIBLE "cdns,spi-r1p6"
#define XPAR_SPI0_BASEADDR 0xff040000
#define XPAR_SPI0_HIGHADDR 0xff040fff
#define XPAR_SPI0_SPI_CLK_FREQ_HZ 0xbebba31
#define XPAR_SPI0_INTERRUPTS 0x4013

/* Canonical definitions for peripheral SPI0 */
#define XPAR_XSPIPS_0_BASEADDR 0xff040000
#define XPAR_XSPIPS_0_HIGHADDR 0xff040fff
#define XPAR_XSPIPS_0_COMPATIBLE "cdns,spi-r1p6"
#define XPAR_XSPIPS_0_INTERRUPTS 0x4013
#define XPAR_XSPIPS_0_SPI_CLK_FREQ_HZ 0xbebba31

#define XPAR_XSYSMONPSU_NUM_INSTANCES 1

/* Definitions for peripheral XILINX_AMS */
#define XPAR_XILINX_AMS_COMPATIBLE "xlnx,zynqmp-ams"
#define XPAR_XILINX_AMS_BASEADDR 0xffa50000
#define XPAR_XILINX_AMS_HIGHADDR 0xffa507ff
#define XPAR_XILINX_AMS_CLOCK_FREQ 0x31

/* Canonical definitions for peripheral XILINX_AMS */
#define XPAR_XSYSMONPSU_0_BASEADDR 0xffa50000
#define XPAR_XSYSMONPSU_0_HIGHADDR 0xffa507ff
#define XPAR_XSYSMONPSU_0_COMPATIBLE "xlnx,zynqmp-ams"
#define XPAR_XSYSMONPSU_0_CLOCK_FREQ 0x31

#define XPAR_XTTCPS_NUM_INSTANCES 12

/* Definitions for peripheral TTC0 */
#define XPAR_TTC0_COMPATIBLE "cdns,ttc"
#define XPAR_TTC0_BASEADDR 0xff110000
#define XPAR_TTC0_HIGHADDR 0xff110fff
#define XPAR_TTC0_CLOCK_FREQ 0x5f5e100
#define XPAR_TTC0_INTERRUPTS 0x4024
#define XPAR_TTC0_INTERRUPTS_1 0x4025
#define XPAR_TTC0_INTERRUPTS_2 0x4026

/* Canonical definitions for peripheral TTC0 */
#define XPAR_XTTCPS_0_BASEADDR 0xff110000
#define XPAR_XTTCPS_0_HIGHADDR 0xff110fff
#define XPAR_XTTCPS_0_COMPATIBLE "cdns,ttc"
#define XPAR_XTTCPS_0_CLOCK_FREQ 0x5f5e100
#define XPAR_XTTCPS_0_INTERRUPTS 0x4024

/* Definitions for peripheral TTC1 */
#define XPAR_TTC1_COMPATIBLE "cdns,ttc"
#define XPAR_TTC1_BASEADDR 0xff110004
#define XPAR_TTC1_HIGHADDR 0xff110fff
#define XPAR_TTC1_CLOCK_FREQ 0x5f5e100
#define XPAR_TTC1_INTERRUPTS 0x4025
#define XPAR_TTC1_INTERRUPTS_1 0x4026

/* Canonical definitions for peripheral TTC1 */
#define XPAR_XTTCPS_1_BASEADDR 0xff110004
#define XPAR_XTTCPS_1_HIGHADDR 0xff110fff
#define XPAR_XTTCPS_1_COMPATIBLE "cdns,ttc"
#define XPAR_XTTCPS_1_CLOCK_FREQ 0x5f5e100
#define XPAR_XTTCPS_1_INTERRUPTS 0x4025

/* Definitions for peripheral TTC2 */
#define XPAR_TTC2_COMPATIBLE "cdns,ttc"
#define XPAR_TTC2_BASEADDR 0xff110008
#define XPAR_TTC2_HIGHADDR 0xff110fff
#define XPAR_TTC2_CLOCK_FREQ 0x5f5e100
#define XPAR_TTC2_INTERRUPTS 0x4026

/* Canonical definitions for peripheral TTC2 */
#define XPAR_XTTCPS_2_BASEADDR 0xff110008
#define XPAR_XTTCPS_2_HIGHADDR 0xff110fff
#define XPAR_XTTCPS_2_COMPATIBLE "cdns,ttc"
#define XPAR_XTTCPS_2_CLOCK_FREQ 0x5f5e100
#define XPAR_XTTCPS_2_INTERRUPTS 0x4026

/* Definitions for peripheral TTC3 */
#define XPAR_TTC3_COMPATIBLE "cdns,ttc"
#define XPAR_TTC3_BASEADDR 0xff120000
#define XPAR_TTC3_HIGHADDR 0xff120fff
#define XPAR_TTC3_CLOCK_FREQ 0x5f5e100
#define XPAR_TTC3_INTERRUPTS 0x4027
#define XPAR_TTC3_INTERRUPTS_1 0x4028
#define XPAR_TTC3_INTERRUPTS_2 0x4029

/* Canonical definitions for peripheral TTC3 */
#define XPAR_XTTCPS_3_BASEADDR 0xff120000
#define XPAR_XTTCPS_3_HIGHADDR 0xff120fff
#define XPAR_XTTCPS_3_COMPATIBLE "cdns,ttc"
#define XPAR_XTTCPS_3_CLOCK_FREQ 0x5f5e100
#define XPAR_XTTCPS_3_INTERRUPTS 0x4027

/* Definitions for peripheral TTC4 */
#define XPAR_TTC4_COMPATIBLE "cdns,ttc"
#define XPAR_TTC4_BASEADDR 0xff120004
#define XPAR_TTC4_HIGHADDR 0xff120fff
#define XPAR_TTC4_CLOCK_FREQ 0x5f5e100
#define XPAR_TTC4_INTERRUPTS 0x4028
#define XPAR_TTC4_INTERRUPTS_1 0x4029

/* Canonical definitions for peripheral TTC4 */
#define XPAR_XTTCPS_4_BASEADDR 0xff120004
#define XPAR_XTTCPS_4_HIGHADDR 0xff120fff
#define XPAR_XTTCPS_4_COMPATIBLE "cdns,ttc"
#define XPAR_XTTCPS_4_CLOCK_FREQ 0x5f5e100
#define XPAR_XTTCPS_4_INTERRUPTS 0x4028

/* Definitions for peripheral TTC5 */
#define XPAR_TTC5_COMPATIBLE "cdns,ttc"
#define XPAR_TTC5_BASEADDR 0xff120008
#define XPAR_TTC5_HIGHADDR 0xff120fff
#define XPAR_TTC5_CLOCK_FREQ 0x5f5e100
#define XPAR_TTC5_INTERRUPTS 0x4029

/* Canonical definitions for peripheral TTC5 */
#define XPAR_XTTCPS_5_BASEADDR 0xff120008
#define XPAR_XTTCPS_5_HIGHADDR 0xff120fff
#define XPAR_XTTCPS_5_COMPATIBLE "cdns,ttc"
#define XPAR_XTTCPS_5_CLOCK_FREQ 0x5f5e100
#define XPAR_XTTCPS_5_INTERRUPTS 0x4029

/* Definitions for peripheral TTC6 */
#define XPAR_TTC6_COMPATIBLE "cdns,ttc"
#define XPAR_TTC6_BASEADDR 0xff130000
#define XPAR_TTC6_HIGHADDR 0xff130fff
#define XPAR_TTC6_CLOCK_FREQ 0x5f5e100
#define XPAR_TTC6_INTERRUPTS 0x402a
#define XPAR_TTC6_INTERRUPTS_1 0x402b
#define XPAR_TTC6_INTERRUPTS_2 0x402c

/* Canonical definitions for peripheral TTC6 */
#define XPAR_XTTCPS_6_BASEADDR 0xff130000
#define XPAR_XTTCPS_6_HIGHADDR 0xff130fff
#define XPAR_XTTCPS_6_COMPATIBLE "cdns,ttc"
#define XPAR_XTTCPS_6_CLOCK_FREQ 0x5f5e100
#define XPAR_XTTCPS_6_INTERRUPTS 0x402a

/* Definitions for peripheral TTC7 */
#define XPAR_TTC7_COMPATIBLE "cdns,ttc"
#define XPAR_TTC7_BASEADDR 0xff130004
#define XPAR_TTC7_HIGHADDR 0xff130fff
#define XPAR_TTC7_CLOCK_FREQ 0x5f5e100
#define XPAR_TTC7_INTERRUPTS 0x402b
#define XPAR_TTC7_INTERRUPTS_1 0x402c

/* Canonical definitions for peripheral TTC7 */
#define XPAR_XTTCPS_7_BASEADDR 0xff130004
#define XPAR_XTTCPS_7_HIGHADDR 0xff130fff
#define XPAR_XTTCPS_7_COMPATIBLE "cdns,ttc"
#define XPAR_XTTCPS_7_CLOCK_FREQ 0x5f5e100
#define XPAR_XTTCPS_7_INTERRUPTS 0x402b

/* Definitions for peripheral TTC8 */
#define XPAR_TTC8_COMPATIBLE "cdns,ttc"
#define XPAR_TTC8_BASEADDR 0xff130008
#define XPAR_TTC8_HIGHADDR 0xff130fff
#define XPAR_TTC8_CLOCK_FREQ 0x5f5e100
#define XPAR_TTC8_INTERRUPTS 0x402c

/* Canonical definitions for peripheral TTC8 */
#define XPAR_XTTCPS_8_BASEADDR 0xff130008
#define XPAR_XTTCPS_8_HIGHADDR 0xff130fff
#define XPAR_XTTCPS_8_COMPATIBLE "cdns,ttc"
#define XPAR_XTTCPS_8_CLOCK_FREQ 0x5f5e100
#define XPAR_XTTCPS_8_INTERRUPTS 0x402c

/* Definitions for peripheral TTC9 */
#define XPAR_TTC9_COMPATIBLE "cdns,ttc"
#define XPAR_TTC9_BASEADDR 0xff140000
#define XPAR_TTC9_HIGHADDR 0xff140fff
#define XPAR_TTC9_CLOCK_FREQ 0x5f5e100
#define XPAR_TTC9_INTERRUPTS 0x402d
#define XPAR_TTC9_INTERRUPTS_1 0x402e
#define XPAR_TTC9_INTERRUPTS_2 0x402f

/* Canonical definitions for peripheral TTC9 */
#define XPAR_XTTCPS_9_BASEADDR 0xff140000
#define XPAR_XTTCPS_9_HIGHADDR 0xff140fff
#define XPAR_XTTCPS_9_COMPATIBLE "cdns,ttc"
#define XPAR_XTTCPS_9_CLOCK_FREQ 0x5f5e100
#define XPAR_XTTCPS_9_INTERRUPTS 0x402d

/* Definitions for peripheral TTC10 */
#define XPAR_TTC10_COMPATIBLE "cdns,ttc"
#define XPAR_TTC10_BASEADDR 0xff140004
#define XPAR_TTC10_HIGHADDR 0xff140fff
#define XPAR_TTC10_CLOCK_FREQ 0x5f5e100
#define XPAR_TTC10_INTERRUPTS 0x402e
#define XPAR_TTC10_INTERRUPTS_1 0x402f

/* Canonical definitions for peripheral TTC10 */
#define XPAR_XTTCPS_10_BASEADDR 0xff140004
#define XPAR_XTTCPS_10_HIGHADDR 0xff140fff
#define XPAR_XTTCPS_10_COMPATIBLE "cdns,ttc"
#define XPAR_XTTCPS_10_CLOCK_FREQ 0x5f5e100
#define XPAR_XTTCPS_10_INTERRUPTS 0x402e

/* Definitions for peripheral TTC11 */
#define XPAR_TTC11_COMPATIBLE "cdns,ttc"
#define XPAR_TTC11_BASEADDR 0xff140008
#define XPAR_TTC11_HIGHADDR 0xff140fff
#define XPAR_TTC11_CLOCK_FREQ 0x5f5e100
#define XPAR_TTC11_INTERRUPTS 0x402f

/* Canonical definitions for peripheral TTC11 */
#define XPAR_XTTCPS_11_BASEADDR 0xff140008
#define XPAR_XTTCPS_11_HIGHADDR 0xff140fff
#define XPAR_XTTCPS_11_COMPATIBLE "cdns,ttc"
#define XPAR_XTTCPS_11_CLOCK_FREQ 0x5f5e100
#define XPAR_XTTCPS_11_INTERRUPTS 0x402f

#define XPAR_XUARTPS_NUM_INSTANCES 2

/* Definitions for peripheral UART0 */
#define XPAR_UART0_COMPATIBLE "xlnx,zynqmp-uart"
#define XPAR_UART0_BASEADDR 0xff000000
#define XPAR_UART0_HIGHADDR 0xff000fff
#define XPAR_UART0_CLOCK_FREQ 0x5f5dd19
#define XPAR_UART0_HAS_MODEM 0x0
#define XPAR_UART0_CLOCKS 0x38
#define XPAR_UART0_INTERRUPTS 0x4015

/* Canonical definitions for peripheral UART0 */
#define XPAR_XUARTPS_0_BASEADDR 0xff000000
#define XPAR_XUARTPS_0_HIGHADDR 0xff000fff
#define XPAR_XUARTPS_0_COMPATIBLE "xlnx,zynqmp-uart"
#define XPAR_XUARTPS_0_CLOCK_FREQ 0x5f5dd19
#define XPAR_XUARTPS_0_CLOCKS 0x38
#define XPAR_XUARTPS_0_HAS_MODEM 0x0
#define XPAR_XUARTPS_0_INTERRUPTS 0x4015

/* Definitions for peripheral UART1 */
#define XPAR_UART1_COMPATIBLE "xlnx,zynqmp-uart"
#define XPAR_UART1_BASEADDR 0xff010000
#define XPAR_UART1_HIGHADDR 0xff010fff
#define XPAR_UART1_CLOCK_FREQ 0x5f5dd19
#define XPAR_UART1_HAS_MODEM 0x0
#define XPAR_UART1_CLOCKS 0x39
#define XPAR_UART1_INTERRUPTS 0x4016

/* Canonical definitions for peripheral UART1 */
#define XPAR_XUARTPS_1_BASEADDR 0xff010000
#define XPAR_XUARTPS_1_HIGHADDR 0xff010fff
#define XPAR_XUARTPS_1_COMPATIBLE "xlnx,zynqmp-uart"
#define XPAR_XUARTPS_1_CLOCK_FREQ 0x5f5dd19
#define XPAR_XUARTPS_1_CLOCKS 0x39
#define XPAR_XUARTPS_1_HAS_MODEM 0x0
#define XPAR_XUARTPS_1_INTERRUPTS 0x4016

#define XPAR_XWDTPS_NUM_INSTANCES 1

/* Definitions for peripheral LPD_WATCHDOG */
#define XPAR_LPD_WATCHDOG_COMPATIBLE "cdns,wdt-r1p2"
#define XPAR_LPD_WATCHDOG_BASEADDR 0xff150000
#define XPAR_LPD_WATCHDOG_HIGHADDR 0xff150fff
#define XPAR_LPD_WATCHDOG_WDT_CLK_FREQ_HZ 0x5f5dd19
#define XPAR_LPD_WATCHDOG_INTERRUPTS 0x1034

/* Canonical definitions for peripheral LPD_WATCHDOG */
#define XPAR_XWDTPS_0_BASEADDR 0xff150000
#define XPAR_XWDTPS_0_HIGHADDR 0xff150fff
#define XPAR_XWDTPS_0_COMPATIBLE "cdns,wdt-r1p2"
#define XPAR_XWDTPS_0_INTERRUPTS 0x1034
#define XPAR_XWDTPS_0_WDT_CLK_FREQ_HZ 0x5f5dd19

#define XPAR_XZDMA_NUM_INSTANCES 8

/* Definitions for peripheral LPD_DMA_CHAN1 */
#define XPAR_LPD_DMA_CHAN1_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_LPD_DMA_CHAN1_BASEADDR 0xffa80000
#define XPAR_LPD_DMA_CHAN1_HIGHADDR 0xffa80fff
#define XPAR_LPD_DMA_CHAN1_DMA_MODE 0x1
#define XPAR_LPD_DMA_CHAN1_INTERRUPTS 0x404d

/* Canonical definitions for peripheral LPD_DMA_CHAN1 */
#define XPAR_XZDMA_0_BASEADDR 0xffa80000
#define XPAR_XZDMA_0_HIGHADDR 0xffa80fff
#define XPAR_XZDMA_0_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_XZDMA_0_DMA_MODE 0x1
#define XPAR_XZDMA_0_INTERRUPTS 0x404d

/* Definitions for peripheral LPD_DMA_CHAN2 */
#define XPAR_LPD_DMA_CHAN2_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_LPD_DMA_CHAN2_BASEADDR 0xffa90000
#define XPAR_LPD_DMA_CHAN2_HIGHADDR 0xffa90fff
#define XPAR_LPD_DMA_CHAN2_DMA_MODE 0x1
#define XPAR_LPD_DMA_CHAN2_INTERRUPTS 0x404e

/* Canonical definitions for peripheral LPD_DMA_CHAN2 */
#define XPAR_XZDMA_1_BASEADDR 0xffa90000
#define XPAR_XZDMA_1_HIGHADDR 0xffa90fff
#define XPAR_XZDMA_1_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_XZDMA_1_DMA_MODE 0x1
#define XPAR_XZDMA_1_INTERRUPTS 0x404e

/* Definitions for peripheral LPD_DMA_CHAN3 */
#define XPAR_LPD_DMA_CHAN3_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_LPD_DMA_CHAN3_BASEADDR 0xffaa0000
#define XPAR_LPD_DMA_CHAN3_HIGHADDR 0xffaa0fff
#define XPAR_LPD_DMA_CHAN3_DMA_MODE 0x1
#define XPAR_LPD_DMA_CHAN3_INTERRUPTS 0x404f

/* Canonical definitions for peripheral LPD_DMA_CHAN3 */
#define XPAR_XZDMA_2_BASEADDR 0xffaa0000
#define XPAR_XZDMA_2_HIGHADDR 0xffaa0fff
#define XPAR_XZDMA_2_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_XZDMA_2_DMA_MODE 0x1
#define XPAR_XZDMA_2_INTERRUPTS 0x404f

/* Definitions for peripheral LPD_DMA_CHAN4 */
#define XPAR_LPD_DMA_CHAN4_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_LPD_DMA_CHAN4_BASEADDR 0xffab0000
#define XPAR_LPD_DMA_CHAN4_HIGHADDR 0xffab0fff
#define XPAR_LPD_DMA_CHAN4_DMA_MODE 0x1
#define XPAR_LPD_DMA_CHAN4_INTERRUPTS 0x4050

/* Canonical definitions for peripheral LPD_DMA_CHAN4 */
#define XPAR_XZDMA_3_BASEADDR 0xffab0000
#define XPAR_XZDMA_3_HIGHADDR 0xffab0fff
#define XPAR_XZDMA_3_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_XZDMA_3_DMA_MODE 0x1
#define XPAR_XZDMA_3_INTERRUPTS 0x4050

/* Definitions for peripheral LPD_DMA_CHAN5 */
#define XPAR_LPD_DMA_CHAN5_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_LPD_DMA_CHAN5_BASEADDR 0xffac0000
#define XPAR_LPD_DMA_CHAN5_HIGHADDR 0xffac0fff
#define XPAR_LPD_DMA_CHAN5_DMA_MODE 0x1
#define XPAR_LPD_DMA_CHAN5_INTERRUPTS 0x4051

/* Canonical definitions for peripheral LPD_DMA_CHAN5 */
#define XPAR_XZDMA_4_BASEADDR 0xffac0000
#define XPAR_XZDMA_4_HIGHADDR 0xffac0fff
#define XPAR_XZDMA_4_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_XZDMA_4_DMA_MODE 0x1
#define XPAR_XZDMA_4_INTERRUPTS 0x4051

/* Definitions for peripheral LPD_DMA_CHAN6 */
#define XPAR_LPD_DMA_CHAN6_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_LPD_DMA_CHAN6_BASEADDR 0xffad0000
#define XPAR_LPD_DMA_CHAN6_HIGHADDR 0xffad0fff
#define XPAR_LPD_DMA_CHAN6_DMA_MODE 0x1
#define XPAR_LPD_DMA_CHAN6_INTERRUPTS 0x4052

/* Canonical definitions for peripheral LPD_DMA_CHAN6 */
#define XPAR_XZDMA_5_BASEADDR 0xffad0000
#define XPAR_XZDMA_5_HIGHADDR 0xffad0fff
#define XPAR_XZDMA_5_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_XZDMA_5_DMA_MODE 0x1
#define XPAR_XZDMA_5_INTERRUPTS 0x4052

/* Definitions for peripheral LPD_DMA_CHAN7 */
#define XPAR_LPD_DMA_CHAN7_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_LPD_DMA_CHAN7_BASEADDR 0xffae0000
#define XPAR_LPD_DMA_CHAN7_HIGHADDR 0xffae0fff
#define XPAR_LPD_DMA_CHAN7_DMA_MODE 0x1
#define XPAR_LPD_DMA_CHAN7_INTERRUPTS 0x4053

/* Canonical definitions for peripheral LPD_DMA_CHAN7 */
#define XPAR_XZDMA_6_BASEADDR 0xffae0000
#define XPAR_XZDMA_6_HIGHADDR 0xffae0fff
#define XPAR_XZDMA_6_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_XZDMA_6_DMA_MODE 0x1
#define XPAR_XZDMA_6_INTERRUPTS 0x4053

/* Definitions for peripheral LPD_DMA_CHAN8 */
#define XPAR_LPD_DMA_CHAN8_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_LPD_DMA_CHAN8_BASEADDR 0xffaf0000
#define XPAR_LPD_DMA_CHAN8_HIGHADDR 0xffaf0fff
#define XPAR_LPD_DMA_CHAN8_DMA_MODE 0x1
#define XPAR_LPD_DMA_CHAN8_INTERRUPTS 0x4054

/* Canonical definitions for peripheral LPD_DMA_CHAN8 */
#define XPAR_XZDMA_7_BASEADDR 0xffaf0000
#define XPAR_XZDMA_7_HIGHADDR 0xffaf0fff
#define XPAR_XZDMA_7_COMPATIBLE "xlnx,zynqmp-dma-1.0"
#define XPAR_XZDMA_7_DMA_MODE 0x1
#define XPAR_XZDMA_7_INTERRUPTS 0x4054

/* Definitions for peripheral OCM */
#define XPAR_OCM_BASEADDR 0xff960000
#define XPAR_OCM_HIGHADDR 0xff960fff

/* Canonical definitions for peripheral OCM */
#define XPAR_PSU_OCM_0_BASEADDR 0xff960000
#define XPAR_PSU_OCM_0_HIGHADDR 0xff960fff

/* Definitions for peripheral USB0 */
#define XPAR_USB0_BASEADDR 0xff9d0000
#define XPAR_USB0_HIGHADDR 0xff9d00ff

/* Canonical definitions for peripheral USB0 */
#define XPAR_PSU_USB_0_BASEADDR 0xff9d0000
#define XPAR_PSU_USB_0_HIGHADDR 0xff9d00ff

/* Definitions for peripheral PSU_R5_TCM_RAM_GLOBAL */
#define XPAR_PSU_R5_TCM_RAM_GLOBAL_BASEADDR 0xffe00000
#define XPAR_PSU_R5_TCM_RAM_GLOBAL_HIGHADDR 0xffe3ffff

/* Definitions for peripheral PSU_R5_TCM_RAM_0 */
#define XPAR_PSU_R5_TCM_RAM_0_BASEADDR 0x0
#define XPAR_PSU_R5_TCM_RAM_0_HIGHADDR 0x3ffff

/* Canonical definitions for peripheral PSU_R5_TCM_RAM_0 */
#define XPAR_PSU_R5_TCM_RAM_1_BASEADDR 0x0
#define XPAR_PSU_R5_TCM_RAM_1_HIGHADDR 0x3ffff

/* Definitions for peripheral PSU_R5_1_BTCM */
#define XPAR_PSU_R5_1_BTCM_BASEADDR 0x20000
#define XPAR_PSU_R5_1_BTCM_HIGHADDR 0x2ffff

/* Canonical definitions for peripheral PSU_R5_1_BTCM */
#define XPAR_PSU_R5_1_BTCM_0_BASEADDR 0x20000
#define XPAR_PSU_R5_1_BTCM_0_HIGHADDR 0x2ffff

/* Definitions for peripheral PSU_R5_1_BTCM_GLOBAL */
#define XPAR_PSU_R5_1_BTCM_GLOBAL_BASEADDR 0xffeb0000
#define XPAR_PSU_R5_1_BTCM_GLOBAL_HIGHADDR 0xffebffff

/* Canonical definitions for peripheral PSU_R5_1_BTCM_GLOBAL */
#define XPAR_PSU_R5_1_BTCM_GLOBAL_0_BASEADDR 0xffeb0000
#define XPAR_PSU_R5_1_BTCM_GLOBAL_0_HIGHADDR 0xffebffff

/* Definitions for peripheral PSU_R5_1_ATCM */
#define XPAR_PSU_R5_1_ATCM_BASEADDR 0x0
#define XPAR_PSU_R5_1_ATCM_HIGHADDR 0xffff

/* Canonical definitions for peripheral PSU_R5_1_ATCM */
#define XPAR_PSU_R5_1_ATCM_0_BASEADDR 0x0
#define XPAR_PSU_R5_1_ATCM_0_HIGHADDR 0xffff

/* Definitions for peripheral PSU_R5_1_ATCM_GLOBAL */
#define XPAR_PSU_R5_1_ATCM_GLOBAL_BASEADDR 0xffe90000
#define XPAR_PSU_R5_1_ATCM_GLOBAL_HIGHADDR 0xffe9ffff

/* Canonical definitions for peripheral PSU_R5_1_ATCM_GLOBAL */
#define XPAR_PSU_R5_1_ATCM_GLOBAL_0_BASEADDR 0xffe90000
#define XPAR_PSU_R5_1_ATCM_GLOBAL_0_HIGHADDR 0xffe9ffff

/* Definitions for peripheral PSU_R5_0_BTCM_LOCKSTEP */
#define XPAR_PSU_R5_0_BTCM_LOCKSTEP_BASEADDR 0xffe30000
#define XPAR_PSU_R5_0_BTCM_LOCKSTEP_HIGHADDR 0xffe3ffff

/* Canonical definitions for peripheral PSU_R5_0_BTCM_LOCKSTEP */
#define XPAR_PSU_R5_0_BTCM_LOCKSTEP_0_BASEADDR 0xffe30000
#define XPAR_PSU_R5_0_BTCM_LOCKSTEP_0_HIGHADDR 0xffe3ffff

/* Definitions for peripheral PSU_R5_0_BTCM */
#define XPAR_PSU_R5_0_BTCM_BASEADDR 0x20000
#define XPAR_PSU_R5_0_BTCM_HIGHADDR 0x2ffff

/* Canonical definitions for peripheral PSU_R5_0_BTCM */
#define XPAR_PSU_R5_0_BTCM_0_BASEADDR 0x20000
#define XPAR_PSU_R5_0_BTCM_0_HIGHADDR 0x2ffff

/* Definitions for peripheral PSU_R5_0_BTCM_GLOBAL */
#define XPAR_PSU_R5_0_BTCM_GLOBAL_BASEADDR 0xffe20000
#define XPAR_PSU_R5_0_BTCM_GLOBAL_HIGHADDR 0xffe2ffff

/* Canonical definitions for peripheral PSU_R5_0_BTCM_GLOBAL */
#define XPAR_PSU_R5_0_BTCM_GLOBAL_0_BASEADDR 0xffe20000
#define XPAR_PSU_R5_0_BTCM_GLOBAL_0_HIGHADDR 0xffe2ffff

/* Definitions for peripheral PSU_R5_0_ATCM_LOCKSTEP */
#define XPAR_PSU_R5_0_ATCM_LOCKSTEP_BASEADDR 0xffe10000
#define XPAR_PSU_R5_0_ATCM_LOCKSTEP_HIGHADDR 0xffe1ffff

/* Canonical definitions for peripheral PSU_R5_0_ATCM_LOCKSTEP */
#define XPAR_PSU_R5_0_ATCM_LOCKSTEP_0_BASEADDR 0xffe10000
#define XPAR_PSU_R5_0_ATCM_LOCKSTEP_0_HIGHADDR 0xffe1ffff

/* Definitions for peripheral PSU_R5_0_ATCM */
#define XPAR_PSU_R5_0_ATCM_BASEADDR 0x0
#define XPAR_PSU_R5_0_ATCM_HIGHADDR 0xffff

/* Canonical definitions for peripheral PSU_R5_0_ATCM */
#define XPAR_PSU_R5_0_ATCM_0_BASEADDR 0x0
#define XPAR_PSU_R5_0_ATCM_0_HIGHADDR 0xffff

/* Definitions for peripheral PSU_R5_0_ATCM_GLOBAL */
#define XPAR_PSU_R5_0_ATCM_GLOBAL_BASEADDR 0xffe00000
#define XPAR_PSU_R5_0_ATCM_GLOBAL_HIGHADDR 0xffe0ffff

/* Canonical definitions for peripheral PSU_R5_0_ATCM_GLOBAL */
#define XPAR_PSU_R5_0_ATCM_GLOBAL_0_BASEADDR 0xffe00000
#define XPAR_PSU_R5_0_ATCM_GLOBAL_0_HIGHADDR 0xffe0ffff

/* Definitions for peripheral PSU_PMU_GLOBAL_0 */
#define XPAR_PSU_PMU_GLOBAL_0_BASEADDR 0xffd80000
#define XPAR_PSU_PMU_GLOBAL_0_HIGHADDR 0xffdbffff

/* Canonical definitions for peripheral PSU_PMU_GLOBAL_0 */
#define XPAR_PSU_PMU_GLOBAL_0_0_BASEADDR 0xffd80000
#define XPAR_PSU_PMU_GLOBAL_0_0_HIGHADDR 0xffdbffff

/* Definitions for peripheral PSU_MBISTJTAG */
#define XPAR_PSU_MBISTJTAG_BASEADDR 0xffcf0000
#define XPAR_PSU_MBISTJTAG_HIGHADDR 0xffcfffff

/* Canonical definitions for peripheral PSU_MBISTJTAG */
#define XPAR_PSU_MBISTJTAG_0_BASEADDR 0xffcf0000
#define XPAR_PSU_MBISTJTAG_0_HIGHADDR 0xffcfffff

/* Definitions for peripheral PSU_RSA */
#define XPAR_PSU_RSA_BASEADDR 0xffce0000
#define XPAR_PSU_RSA_HIGHADDR 0xffceffff

/* Canonical definitions for peripheral PSU_RSA */
#define XPAR_PSU_RSA_0_BASEADDR 0xffce0000
#define XPAR_PSU_RSA_0_HIGHADDR 0xffceffff

/* Definitions for peripheral PSU_EFUSE */
#define XPAR_PSU_EFUSE_BASEADDR 0xffcc0000
#define XPAR_PSU_EFUSE_HIGHADDR 0xffccffff

/* Canonical definitions for peripheral PSU_EFUSE */
#define XPAR_PSU_EFUSE_0_BASEADDR 0xffcc0000
#define XPAR_PSU_EFUSE_0_HIGHADDR 0xffccffff

/* Definitions for peripheral PSU_CSU_0 */
#define XPAR_PSU_CSU_0_BASEADDR 0xffca0000
#define XPAR_PSU_CSU_0_HIGHADDR 0xffcaffff

/* Definitions for peripheral PSU_OCM_XMPU_CFG */
#define XPAR_PSU_OCM_XMPU_CFG_BASEADDR 0xffa70000
#define XPAR_PSU_OCM_XMPU_CFG_HIGHADDR 0xffa7ffff

/* Canonical definitions for peripheral PSU_OCM_XMPU_CFG */
#define XPAR_PSU_OCM_XMPU_CFG_0_BASEADDR 0xffa70000
#define XPAR_PSU_OCM_XMPU_CFG_0_HIGHADDR 0xffa7ffff

/* Definitions for peripheral PSU_LPD_XPPU_SINK */
#define XPAR_PSU_LPD_XPPU_SINK_BASEADDR 0xff9c0000
#define XPAR_PSU_LPD_XPPU_SINK_HIGHADDR 0xff9cffff

/* Canonical definitions for peripheral PSU_LPD_XPPU_SINK */
#define XPAR_PSU_LPD_XPPU_SINK_0_BASEADDR 0xff9c0000
#define XPAR_PSU_LPD_XPPU_SINK_0_HIGHADDR 0xff9cffff

/* Definitions for peripheral PSU_AFI_6 */
#define XPAR_PSU_AFI_6_BASEADDR 0xff9b0000
#define XPAR_PSU_AFI_6_HIGHADDR 0xff9bffff

/* Canonical definitions for peripheral PSU_AFI_6 */
#define XPAR_PSU_AFI_0_BASEADDR 0xff9b0000
#define XPAR_PSU_AFI_0_HIGHADDR 0xff9bffff

/* Definitions for peripheral PSU_RPU */
#define XPAR_PSU_RPU_BASEADDR 0xff9a0000
#define XPAR_PSU_RPU_HIGHADDR 0xff9affff

/* Canonical definitions for peripheral PSU_RPU */
#define XPAR_PSU_RPU_0_BASEADDR 0xff9a0000
#define XPAR_PSU_RPU_0_HIGHADDR 0xff9affff

/* Definitions for peripheral PSU_LPD_SLCR_SECURE */
#define XPAR_PSU_LPD_SLCR_SECURE_BASEADDR 0xff4b0000
#define XPAR_PSU_LPD_SLCR_SECURE_HIGHADDR 0xff4dffff

/* Canonical definitions for peripheral PSU_LPD_SLCR_SECURE */
#define XPAR_PSU_LPD_SLCR_SECURE_0_BASEADDR 0xff4b0000
#define XPAR_PSU_LPD_SLCR_SECURE_0_HIGHADDR 0xff4dffff

/* Definitions for peripheral PSU_LPD_SLCR */
#define XPAR_PSU_LPD_SLCR_BASEADDR 0xff410000
#define XPAR_PSU_LPD_SLCR_HIGHADDR 0xff4affff

/* Canonical definitions for peripheral PSU_LPD_SLCR */
#define XPAR_PSU_LPD_SLCR_0_BASEADDR 0xff410000
#define XPAR_PSU_LPD_SLCR_0_HIGHADDR 0xff4affff

/* Definitions for peripheral PSU_IOU_SCNTRS */
#define XPAR_PSU_IOU_SCNTRS_BASEADDR 0xff260000
#define XPAR_PSU_IOU_SCNTRS_HIGHADDR 0xff26ffff

/* Canonical definitions for peripheral PSU_IOU_SCNTRS */
#define XPAR_PSU_IOU_SCNTRS_0_BASEADDR 0xff260000
#define XPAR_PSU_IOU_SCNTRS_0_HIGHADDR 0xff26ffff

/* Definitions for peripheral PSU_IOU_SCNTR */
#define XPAR_PSU_IOU_SCNTR_BASEADDR 0xff250000
#define XPAR_PSU_IOU_SCNTR_HIGHADDR 0xff25ffff

/* Canonical definitions for peripheral PSU_IOU_SCNTR */
#define XPAR_PSU_IOU_SCNTR_0_BASEADDR 0xff250000
#define XPAR_PSU_IOU_SCNTR_0_HIGHADDR 0xff25ffff

/* Definitions for peripheral PSU_IOUSECURE_SLCR */
#define XPAR_PSU_IOUSECURE_SLCR_BASEADDR 0xff240000
#define XPAR_PSU_IOUSECURE_SLCR_HIGHADDR 0xff24ffff

/* Canonical definitions for peripheral PSU_IOUSECURE_SLCR */
#define XPAR_PSU_IOUSECURE_SLCR_0_BASEADDR 0xff240000
#define XPAR_PSU_IOUSECURE_SLCR_0_HIGHADDR 0xff24ffff

/* Definitions for peripheral PSU_IOUSLCR_0 */
#define XPAR_PSU_IOUSLCR_0_BASEADDR 0xff180000
#define XPAR_PSU_IOUSLCR_0_HIGHADDR 0xff23ffff

/* Definitions for peripheral LPD_XPPU */
#define XPAR_LPD_XPPU_BASEADDR 0xff980000
#define XPAR_LPD_XPPU_HIGHADDR 0xff980fff

/* Canonical definitions for peripheral LPD_XPPU */
#define XPAR_PSU_LPD_XPPU_0_BASEADDR 0xff980000
#define XPAR_PSU_LPD_XPPU_0_HIGHADDR 0xff980fff

/*  BOARD definition */
#define XPS_BOARD_OSDZU3_REF

#define XPAR_PSU_DDR_0_BASEADDRESS 0x0
#define XPAR_PSU_DDR_0_HIGHADDRESS 0x3fffffff
#define XPAR_PSU_DDR_1_BASEADDRESS 0x60000000
#define XPAR_PSU_DDR_1_HIGHADDRESS 0x7fefffff
#define XPAR_PSU_QSPI_LINEAR_0_BASEADDRESS 0xc0000000
#define XPAR_PSU_QSPI_LINEAR_0_HIGHADDRESS 0xcfffffff
#define XPAR_PSU_OCM_0_BASEADDRESS 0xfffc0000
#define XPAR_PSU_OCM_0_HIGHADDRESS 0xffffffff
#define XPAR_LMB_BRAM_0_BASEADDRESS 0x90000000
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x9001ffff

/*  CPU parameters definition */
#define XPAR_MICROBLAZE_RISCV_TIMEBASE_FREQUENCY 99999001
#define XPAR_MICROBLAZE_RISCV_FREQ 99999001
#define XPAR_MICROBLAZE_RISCV_BASE_VECTORS 2415919104
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_MULDIV 0
#define XPAR_MICROBLAZE_RISCV_USE_ATOMIC 0
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_DATA_SIZE 32
#define XPAR_MICROBLAZE_RISCV_D_CACHE_SIZE 16384
#define XPAR_MICROBLAZE_RISCV_D_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_RISCV_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_D_CACHE_BASEADDR 2147483648
#define XPAR_MICROBLAZE_RISCV_D_CACHE_HIGHADDR 4294967295
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_REG 0

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 99999001

#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0

#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 16384

#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0

#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 16384

#define XPAR_MICROBLAZE_RISCV_USE_FPU 0

#define XPAR_MICROBLAZE_RISCV_USE_MMU 0

#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0

#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0

#define XPAR_MICROBLAZE_RISCV_D_LMB 1

#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0

#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "xczu3eg"

#endif  /* end of protection macro */