# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xci
# IP: The module: 'design_1_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.gen/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xci
# IP: The module: 'design_1_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.gen/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
