# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/OSDZU3_Tutorial_IO_Standards.xdc

# TCL: imports/Constraints/osdzu3_helper.tcl

# TCL: imports/new/osdzu3_package_pins.tcl

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_100M_0/design_1_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lvds_display_tx_0_0/design_1_lvds_display_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lvds_display_tx_0_0 || ORIG_REF_NAME==design_1_lvds_display_tx_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_fb_rd_0_rst_n_0/design_1_v_fb_rd_0_rst_n_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_fb_rd_0_rst_n_0 || ORIG_REF_NAME==design_1_v_fb_rd_0_rst_n_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_fb_rd_1_rst_n_0/design_1_v_fb_rd_1_rst_n_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_fb_rd_1_rst_n_0 || ORIG_REF_NAME==design_1_v_fb_rd_1_rst_n_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_mix_rst_n_0/design_1_v_mix_rst_n_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_mix_rst_n_0 || ORIG_REF_NAME==design_1_v_mix_rst_n_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_1/design_1_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_1 || ORIG_REF_NAME==design_1_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_1_0/design_1_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_0 || ORIG_REF_NAME==design_1_xlslice_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_1_1/design_1_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_1 || ORIG_REF_NAME==design_1_xlslice_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_1/design_1_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_1 || ORIG_REF_NAME==design_1_axi_gpio_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_timer_0_0 || ORIG_REF_NAME==design_1_axi_timer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hls_ip_reset_0/design_1_hls_ip_reset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hls_ip_reset_0 || ORIG_REF_NAME==design_1_hls_ip_reset_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lvds_display_iic_0/design_1_lvds_display_iic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lvds_display_iic_0 || ORIG_REF_NAME==design_1_lvds_display_iic_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_1/design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_1 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_cc_0/design_1_ps8_0_axi_periph_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_cc_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_cc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_cc_1/design_1_ps8_0_axi_periph_imp_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_cc_1 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_cc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_cc_2/design_1_ps8_0_axi_periph_imp_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_cc_2 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_cc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_cc_3/design_1_ps8_0_axi_periph_imp_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_cc_3 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_cc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_cc_4/design_1_ps8_0_axi_periph_imp_auto_cc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_cc_4 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_cc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_1/design_1_ps8_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_1 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_1_0/design_1_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_1_0 || ORIG_REF_NAME==design_1_system_ila_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_2_0/design_1_system_ila_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_2_0 || ORIG_REF_NAME==design_1_system_ila_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_frmbuf_rd_0_0/design_1_v_frmbuf_rd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_rd_0_0 || ORIG_REF_NAME==design_1_v_frmbuf_rd_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_frmbuf_rd_1_0/design_1_v_frmbuf_rd_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_rd_1_0 || ORIG_REF_NAME==design_1_v_frmbuf_rd_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_mix_0_0/design_1_v_mix_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_mix_0_0 || ORIG_REF_NAME==design_1_v_mix_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_tc_0_0 || ORIG_REF_NAME==design_1_v_tc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_100M_1/design_1_rst_ps8_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_100M_1 || ORIG_REF_NAME==design_1_rst_ps8_0_100M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_200M_0/design_1_rst_ps8_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_200M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_200M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_timer_0_1/design_1_axi_timer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_timer_0_1 || ORIG_REF_NAME==design_1_axi_timer_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uart16550_1_0/design_1_axi_uart16550_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uart16550_1_0 || ORIG_REF_NAME==design_1_axi_uart16550_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_2 || ORIG_REF_NAME==design_1_axi_gpio_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uart16550_0_0/design_1_axi_uart16550_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uart16550_0_0 || ORIG_REF_NAME==design_1_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_3 || ORIG_REF_NAME==design_1_axi_gpio_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_1_0/design_1_axi_iic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_1_0 || ORIG_REF_NAME==design_1_axi_iic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_1_0/design_1_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_1_0 || ORIG_REF_NAME==design_1_xlconcat_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_2/design_1_xlconcat_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_2 || ORIG_REF_NAME==design_1_xlconcat_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_0 || ORIG_REF_NAME==design_1_axi_gpio_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_0/design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_ds_0/design_1_ps8_0_axi_periph_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_ds_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_pc_0/design_1_ps8_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_0/design_1_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_riscv_0_0/design_1_mdm_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mdm_riscv_0_0 || ORIG_REF_NAME==design_1_mdm_riscv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_riscv_0_0/design_1_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_riscv_0_0 || ORIG_REF_NAME==design_1_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_intc_0_0/design_1_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_intc_0_0 || ORIG_REF_NAME==design_1_axi_intc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_0 || ORIG_REF_NAME==design_1_axi_smc_0} -quiet] -quiet

# Block Designs: bd/OSDZU3x_Tutorial/OSDZU3x_Tutorial.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial || ORIG_REF_NAME==OSDZU3x_Tutorial} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_zynq_ultra_ps_e_0_0/OSDZU3x_Tutorial_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_axi_gpio_0_0/OSDZU3x_Tutorial_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_axi_gpio_0_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_axi_gpio_0_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_axi_smc_0/OSDZU3x_Tutorial_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_axi_smc_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_axi_smc_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_axi_gpio_1_0/OSDZU3x_Tutorial_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_axi_gpio_1_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_axi_gpio_1_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_axi_gpio_2_0/OSDZU3x_Tutorial_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_axi_gpio_2_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_axi_gpio_2_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_microblaze_riscv_0_1/OSDZU3x_Tutorial_microblaze_riscv_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_microblaze_riscv_0_1 || ORIG_REF_NAME==OSDZU3x_Tutorial_microblaze_riscv_0_1} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_dlmb_v10_0/OSDZU3x_Tutorial_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_dlmb_v10_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_dlmb_v10_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_ilmb_v10_0/OSDZU3x_Tutorial_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_ilmb_v10_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_ilmb_v10_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_dlmb_bram_if_cntlr_0/OSDZU3x_Tutorial_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_ilmb_bram_if_cntlr_0/OSDZU3x_Tutorial_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_lmb_bram_0/OSDZU3x_Tutorial_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_lmb_bram_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_lmb_bram_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_microblaze_riscv_0_axi_intc_0/OSDZU3x_Tutorial_microblaze_riscv_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_microblaze_riscv_0_axi_intc_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_microblaze_riscv_0_axi_intc_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_microblaze_riscv_0_xlconcat_0/OSDZU3x_Tutorial_microblaze_riscv_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_microblaze_riscv_0_xlconcat_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_microblaze_riscv_0_xlconcat_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_mdm_1_0/OSDZU3x_Tutorial_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_mdm_1_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_mdm_1_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_rst_clk_wiz_1_100M_0/OSDZU3x_Tutorial_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/OSDZU3x_Tutorial/ip/OSDZU3x_Tutorial_smartconnect_0_0/OSDZU3x_Tutorial_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_Tutorial_smartconnect_0_0 || ORIG_REF_NAME==OSDZU3x_Tutorial_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/OSDZU3x_BYOTEE/OSDZU3x_BYOTEE.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE || ORIG_REF_NAME==OSDZU3x_BYOTEE} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_zynq_ultra_ps_e_0_1/OSDZU3x_BYOTEE_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==OSDZU3x_BYOTEE_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_rst_ps8_0_99M_0/OSDZU3x_BYOTEE_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_rst_ps8_0_99M_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_intc_0_0/OSDZU3x_BYOTEE_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_intc_0_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_intc_0_0} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_gpio_0_0/OSDZU3x_BYOTEE_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_gpio_0_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_gpio_0_0} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_imp_xbar_1/OSDZU3x_BYOTEE_axi_interconnect_0_imp_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_xbar_1 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_xbar_1} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_1/OSDZU3x_BYOTEE_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_1 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_1_imp_xbar_0/OSDZU3x_BYOTEE_axi_interconnect_1_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_1_imp_xbar_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_1_imp_xbar_0} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_1_0/OSDZU3x_BYOTEE_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_1_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_gpio_1_0/OSDZU3x_BYOTEE_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_gpio_1_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_gpio_1_0} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_gpio_2_0/OSDZU3x_BYOTEE_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_gpio_2_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_gpio_2_0} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_microblaze_riscv_0_0/OSDZU3x_BYOTEE_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_microblaze_riscv_0_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_dlmb_v10_1/OSDZU3x_BYOTEE_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_dlmb_v10_1 || ORIG_REF_NAME==OSDZU3x_BYOTEE_dlmb_v10_1} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_ilmb_v10_1/OSDZU3x_BYOTEE_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_ilmb_v10_1 || ORIG_REF_NAME==OSDZU3x_BYOTEE_ilmb_v10_1} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_dlmb_bram_if_cntlr_1/OSDZU3x_BYOTEE_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==OSDZU3x_BYOTEE_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_ilmb_bram_if_cntlr_1/OSDZU3x_BYOTEE_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==OSDZU3x_BYOTEE_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_lmb_bram_1/OSDZU3x_BYOTEE_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_lmb_bram_1 || ORIG_REF_NAME==OSDZU3x_BYOTEE_lmb_bram_1} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_mdm_1_1/OSDZU3x_BYOTEE_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_mdm_1_1 || ORIG_REF_NAME==OSDZU3x_BYOTEE_mdm_1_1} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_3/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_3 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_3} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_us_0/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_us_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_us_0} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_4/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_4 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_4} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_us_1/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_us_1 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_us_1} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_us_2/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_us_2 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_us_2} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_ds_0/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_ds_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_ds_0} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_0/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_ds_1/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_ds_1 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_ds_1} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_1/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_1 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_1} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_ds_2/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_ds_2 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_ds_2} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_2/OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_2 || ORIG_REF_NAME==OSDZU3x_BYOTEE_axi_interconnect_0_imp_auto_pc_2} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_ultra_ps_0_axi_periph_imp_auto_ds_0/OSDZU3x_BYOTEE_ultra_ps_0_axi_periph_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_ultra_ps_0_axi_periph_imp_auto_ds_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_ultra_ps_0_axi_periph_imp_auto_ds_0} -quiet] -quiet

# IP: bd/OSDZU3x_BYOTEE/ip/OSDZU3x_BYOTEE_ultra_ps_0_axi_periph_imp_auto_pc_0/OSDZU3x_BYOTEE_ultra_ps_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OSDZU3x_BYOTEE_ultra_ps_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==OSDZU3x_BYOTEE_ultra_ps_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# Block Designs: bd/byotee_extclk/byotee_extclk.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk || ORIG_REF_NAME==byotee_extclk} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_gpio_1_0/byotee_extclk_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_gpio_1_0 || ORIG_REF_NAME==byotee_extclk_axi_gpio_1_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_intc_0_0/byotee_extclk_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_intc_0_0 || ORIG_REF_NAME==byotee_extclk_axi_intc_0_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_mdm_0_0/byotee_extclk_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_mdm_0_0 || ORIG_REF_NAME==byotee_extclk_mdm_0_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_microblaze_0_0/byotee_extclk_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_microblaze_0_0 || ORIG_REF_NAME==byotee_extclk_microblaze_0_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_dlmb_v10_0/byotee_extclk_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_dlmb_v10_0 || ORIG_REF_NAME==byotee_extclk_dlmb_v10_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_ilmb_v10_0/byotee_extclk_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_ilmb_v10_0 || ORIG_REF_NAME==byotee_extclk_ilmb_v10_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_dlmb_bram_if_cntlr_0/byotee_extclk_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==byotee_extclk_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_ilmb_bram_if_cntlr_0/byotee_extclk_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==byotee_extclk_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_lmb_bram_0/byotee_extclk_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_lmb_bram_0 || ORIG_REF_NAME==byotee_extclk_lmb_bram_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_pl_ps_intr_0/byotee_extclk_pl_ps_intr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_pl_ps_intr_0 || ORIG_REF_NAME==byotee_extclk_pl_ps_intr_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_ps_pl_intr_0/byotee_extclk_ps_pl_intr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_ps_pl_intr_0 || ORIG_REF_NAME==byotee_extclk_ps_pl_intr_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_rst_ps8_0_99M_0/byotee_extclk_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_rst_ps8_0_99M_0 || ORIG_REF_NAME==byotee_extclk_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_ultra_ps_0_axi_periph_imp_xbar_0/byotee_extclk_ultra_ps_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_ultra_ps_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==byotee_extclk_ultra_ps_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_ultra_ps_0_axi_periph_imp_auto_ds_0/byotee_extclk_ultra_ps_0_axi_periph_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_ultra_ps_0_axi_periph_imp_auto_ds_0 || ORIG_REF_NAME==byotee_extclk_ultra_ps_0_axi_periph_imp_auto_ds_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_ultra_ps_0_axi_periph_imp_auto_pc_0/byotee_extclk_ultra_ps_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_ultra_ps_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==byotee_extclk_ultra_ps_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_ultra_ps_0_axi_periph_0/byotee_extclk_ultra_ps_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_ultra_ps_0_axi_periph_0 || ORIG_REF_NAME==byotee_extclk_ultra_ps_0_axi_periph_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_zynq_ultra_ps_e_0_0/byotee_extclk_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==byotee_extclk_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_proc_sys_reset_0_0/byotee_extclk_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_proc_sys_reset_0_0 || ORIG_REF_NAME==byotee_extclk_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_xbar_0/byotee_extclk_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_pc_3/byotee_extclk_axi_interconnect_0_imp_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_pc_3 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_pc_3} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_us_0/byotee_extclk_axi_interconnect_0_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_us_0 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_us_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_pc_4/byotee_extclk_axi_interconnect_0_imp_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_pc_4 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_pc_4} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_us_1/byotee_extclk_axi_interconnect_0_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_us_1 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_us_1} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_us_2/byotee_extclk_axi_interconnect_0_imp_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_us_2 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_us_2} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_cc_0/byotee_extclk_axi_interconnect_0_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_cc_0 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_cc_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_ds_0/byotee_extclk_axi_interconnect_0_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_ds_0 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_ds_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_pc_0/byotee_extclk_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_ds_1/byotee_extclk_axi_interconnect_0_imp_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_ds_1 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_ds_1} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_pc_1/byotee_extclk_axi_interconnect_0_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_pc_1 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_pc_1} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_ds_2/byotee_extclk_axi_interconnect_0_imp_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_ds_2 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_ds_2} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_pc_2/byotee_extclk_axi_interconnect_0_imp_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_pc_2 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_pc_2} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_auto_cc_1/byotee_extclk_axi_interconnect_0_imp_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_cc_1 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_auto_cc_1} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_s00_mmu_0/byotee_extclk_axi_interconnect_0_imp_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_s00_mmu_0 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_s00_mmu_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_imp_s01_mmu_0/byotee_extclk_axi_interconnect_0_imp_s01_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_imp_s01_mmu_0 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_imp_s01_mmu_0} -quiet] -quiet

# IP: bd/byotee_extclk/ip/byotee_extclk_axi_interconnect_0_0/byotee_extclk_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==byotee_extclk_axi_interconnect_0_0 || ORIG_REF_NAME==byotee_extclk_axi_interconnect_0_0} -quiet] -quiet

# XDC: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.gen/sources_1/bd/design_1/design_1_ooc.xdc

# XDC: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.gen/sources_1/bd/OSDZU3x_Tutorial/OSDZU3x_Tutorial_ooc.xdc

# XDC: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.gen/sources_1/bd/OSDZU3x_BYOTEE/OSDZU3x_BYOTEE_ooc.xdc

# XDC: /home/e/Documents/research/byotee/OSDZU3_Ref_Design/OSDZU3_Ref_Design.gen/sources_1/bd/byotee_extclk/byotee_extclk_ooc.xdc
