-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    bytePlanes_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    bytePlanes_empty_n : IN STD_LOGIC;
    bytePlanes_read : OUT STD_LOGIC;
    bytePlanes_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    img_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    img_full_n : IN STD_LOGIC;
    img_write : OUT STD_LOGIC;
    img_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    Height_val : IN STD_LOGIC_VECTOR (11 downto 0);
    WidthInBytes_val : IN STD_LOGIC_VECTOR (14 downto 0);
    VideoFormat_val : IN STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv6_1A : STD_LOGIC_VECTOR (5 downto 0) := "011010";
    constant ap_const_lv6_D : STD_LOGIC_VECTOR (5 downto 0) := "001101";
    constant ap_const_lv6_E : STD_LOGIC_VECTOR (5 downto 0) := "001110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv15_7 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv6_27 : STD_LOGIC_VECTOR (5 downto 0) := "100111";
    constant ap_const_lv6_22 : STD_LOGIC_VECTOR (5 downto 0) := "100010";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_18 : STD_LOGIC_VECTOR (5 downto 0) := "011000";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_B : STD_LOGIC_VECTOR (5 downto 0) := "001011";
    constant ap_const_lv6_1D : STD_LOGIC_VECTOR (5 downto 0) := "011101";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_1E : STD_LOGIC_VECTOR (5 downto 0) := "011110";
    constant ap_const_lv6_1F : STD_LOGIC_VECTOR (5 downto 0) := "011111";
    constant ap_const_lv6_14 : STD_LOGIC_VECTOR (5 downto 0) := "010100";
    constant ap_const_lv6_15 : STD_LOGIC_VECTOR (5 downto 0) := "010101";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv6_C : STD_LOGIC_VECTOR (5 downto 0) := "001100";
    constant ap_const_lv6_25 : STD_LOGIC_VECTOR (5 downto 0) := "100101";
    constant ap_const_lv6_26 : STD_LOGIC_VECTOR (5 downto 0) := "100110";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_21 : STD_LOGIC_VECTOR (5 downto 0) := "100001";
    constant ap_const_lv6_16 : STD_LOGIC_VECTOR (5 downto 0) := "010110";
    constant ap_const_lv6_17 : STD_LOGIC_VECTOR (5 downto 0) := "010111";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv6_29 : STD_LOGIC_VECTOR (5 downto 0) := "101001";
    constant ap_const_lv6_2C : STD_LOGIC_VECTOR (5 downto 0) := "101100";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv6_2B : STD_LOGIC_VECTOR (5 downto 0) := "101011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal grp_fu_196_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal reg_220 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_block_state1 : BOOLEAN;
    signal VideoFormat_val_read_read_fu_150_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal VideoFormat_val_read_reg_362 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal Height_val_read_reg_366 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal grp_fu_214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1724_reg_379 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal sub309_fu_298_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub309_reg_384 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal xor_ln1686_reg_396 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal sub185_fu_313_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub185_reg_401 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_start : STD_LOGIC;
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_done : STD_LOGIC;
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_idle : STD_LOGIC;
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_ready : STD_LOGIC;
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_img_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_img_write : STD_LOGIC;
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_bytePlanes_read : STD_LOGIC;
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_start : STD_LOGIC;
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_done : STD_LOGIC;
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_idle : STD_LOGIC;
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_ready : STD_LOGIC;
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_img_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_img_write : STD_LOGIC;
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_bytePlanes_read : STD_LOGIC;
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln1727_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln1689_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal y_1_fu_142 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal y_5_fu_332_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal y_fu_146 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal y_3_fu_351_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_190_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_206_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln1721_fu_294_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln1683_fu_309_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_full_n : IN STD_LOGIC;
        img_write : OUT STD_LOGIC;
        img_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        bytePlanes_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        bytePlanes_empty_n : IN STD_LOGIC;
        bytePlanes_read : OUT STD_LOGIC;
        bytePlanes_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        loopWidth_1 : IN STD_LOGIC_VECTOR (11 downto 0);
        sext_ln1727 : IN STD_LOGIC_VECTOR (12 downto 0);
        rev4 : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_full_n : IN STD_LOGIC;
        img_write : OUT STD_LOGIC;
        img_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        bytePlanes_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        bytePlanes_empty_n : IN STD_LOGIC;
        bytePlanes_read : OUT STD_LOGIC;
        bytePlanes_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        trunc_ln1683_1 : IN STD_LOGIC_VECTOR (11 downto 0);
        sub185 : IN STD_LOGIC_VECTOR (12 downto 0);
        rev : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168 : component design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_start,
        ap_done => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_done,
        ap_idle => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_idle,
        ap_ready => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_ready,
        img_din => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_img_din,
        img_full_n => img_full_n,
        img_write => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_img_write,
        img_num_data_valid => img_num_data_valid,
        img_fifo_cap => img_fifo_cap,
        bytePlanes_dout => bytePlanes_dout,
        bytePlanes_empty_n => bytePlanes_empty_n,
        bytePlanes_read => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_bytePlanes_read,
        bytePlanes_num_data_valid => ap_const_lv11_0,
        bytePlanes_fifo_cap => ap_const_lv11_0,
        loopWidth_1 => reg_220,
        sext_ln1727 => sub309_reg_384,
        rev4 => xor_ln1724_reg_379);

    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179 : component design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_start,
        ap_done => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_done,
        ap_idle => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_idle,
        ap_ready => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_ready,
        img_din => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_img_din,
        img_full_n => img_full_n,
        img_write => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_img_write,
        img_num_data_valid => img_num_data_valid,
        img_fifo_cap => img_fifo_cap,
        bytePlanes_dout => bytePlanes_dout,
        bytePlanes_empty_n => bytePlanes_empty_n,
        bytePlanes_read => grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_bytePlanes_read,
        bytePlanes_num_data_valid => ap_const_lv11_0,
        bytePlanes_fifo_cap => ap_const_lv11_0,
        trunc_ln1683_1 => reg_220,
        sub185 => sub185_reg_401,
        rev => xor_ln1686_reg_396);





    Height_val_read_reg_366_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                Height_val_read_reg_366 <= ap_const_lv12_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    Height_val_read_reg_366 <= Height_val;
                end if; 
            end if;
        end if;
    end process;


    VideoFormat_val_read_reg_362_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                VideoFormat_val_read_reg_362 <= ap_const_lv6_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    VideoFormat_val_read_reg_362 <= VideoFormat_val;
                end if; 
            end if;
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_const_lv6_2B = VideoFormat_val_read_reg_362) or ((ap_const_lv6_2A = VideoFormat_val_read_reg_362) or ((ap_const_lv6_2C = VideoFormat_val_read_reg_362) or ((ap_const_lv6_29 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_13 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_12 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_17 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_16 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_21 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_20 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_26 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_25 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_C = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1C = VideoFormat_val_read_reg_362) or ((ap_const_lv6_15 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_14 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1F = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1E = VideoFormat_val_read_reg_362) or ((ap_const_lv6_24 = VideoFormat_val_read_reg_362) 
    or ((ap_const_lv6_23 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1D = VideoFormat_val_read_reg_362) or ((ap_const_lv6_B = VideoFormat_val_read_reg_362) or ((ap_const_lv6_A = VideoFormat_val_read_reg_362) or ((ap_const_lv6_10 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_F = VideoFormat_val_read_reg_362) or ((ap_const_lv6_18 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_19 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_22 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_27 = VideoFormat_val_read_reg_362) or ((((not((ap_const_lv6_E = VideoFormat_val_read_reg_362)) and not((ap_const_lv6_D = VideoFormat_val_read_reg_362)) and (icmp_ln1727_fu_327_p2 = ap_const_lv1_1)) or ((ap_const_lv6_D = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 = ap_const_lv1_1))) or (not((ap_const_lv6_E = VideoFormat_val_read_reg_362)) and not((ap_const_lv6_D = VideoFormat_val_read_reg_362)) and not((ap_const_lv6_1A = VideoFormat_val_read_reg_362)))) or ((ap_const_lv6_E = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 
    = ap_const_lv1_1)))))))))))))))))))))))))))))))))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (((ap_const_lv6_E = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 = ap_const_lv1_0)) or ((ap_const_lv6_D = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 = ap_const_lv1_0))))) then 
                    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_ready = ap_const_logic_1)) then 
                    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_lv6_1A = VideoFormat_val_read_reg_362) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln1727_fu_327_p2 = ap_const_lv1_0))) then 
                    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_ready = ap_const_logic_1)) then 
                    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    reg_220_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                reg_220 <= ap_const_lv12_0;
            else
                if ((((ap_const_lv6_1A = VideoFormat_val_read_read_fu_150_p2) and (ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1) and ((ap_const_lv6_E = VideoFormat_val_read_read_fu_150_p2) or (ap_const_lv6_D = VideoFormat_val_read_read_fu_150_p2))))) then 
                    reg_220 <= grp_fu_190_p2(14 downto 3);
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    sub185_reg_401_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                sub185_reg_401 <= ap_const_lv13_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    sub185_reg_401 <= sub185_fu_313_p2;
                end if; 
            end if;
        end if;
    end process;


    sub309_reg_384_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                sub309_reg_384 <= ap_const_lv13_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    sub309_reg_384 <= sub309_fu_298_p2;
                end if; 
            end if;
        end if;
    end process;


    xor_ln1686_reg_396_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                xor_ln1686_reg_396 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    xor_ln1686_reg_396 <= grp_fu_214_p2;
                end if; 
            end if;
        end if;
    end process;


    xor_ln1724_reg_379_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                xor_ln1724_reg_379 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    xor_ln1724_reg_379 <= grp_fu_214_p2;
                end if; 
            end if;
        end if;
    end process;


    y_1_fu_142_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                y_1_fu_142 <= ap_const_lv12_0;
            else
                if (((ap_const_lv6_1A = VideoFormat_val_read_read_fu_150_p2) and (ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    y_1_fu_142 <= ap_const_lv12_0;
                elsif (((ap_const_lv6_1A = VideoFormat_val_read_reg_362) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln1727_fu_327_p2 = ap_const_lv1_0))) then 
                    y_1_fu_142 <= y_5_fu_332_p2;
                end if; 
            end if;
        end if;
    end process;


    y_fu_146_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                y_fu_146 <= ap_const_lv12_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1) and ((ap_const_lv6_E = VideoFormat_val_read_read_fu_150_p2) or (ap_const_lv6_D = VideoFormat_val_read_read_fu_150_p2)))) then 
                    y_fu_146 <= ap_const_lv12_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (((ap_const_lv6_E = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 = ap_const_lv1_0)) or ((ap_const_lv6_D = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 = ap_const_lv1_0))))) then 
                    y_fu_146 <= y_3_fu_351_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, VideoFormat_val_read_reg_362, grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_done, grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_done, ap_CS_fsm_state2, icmp_ln1727_fu_327_p2, ap_CS_fsm_state3, icmp_ln1689_fu_346_p2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_const_lv6_2B = VideoFormat_val_read_reg_362) or ((ap_const_lv6_2A = VideoFormat_val_read_reg_362) or ((ap_const_lv6_2C = VideoFormat_val_read_reg_362) or ((ap_const_lv6_29 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_13 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_12 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_17 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_16 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_21 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_20 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_26 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_25 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_C = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1C = VideoFormat_val_read_reg_362) or ((ap_const_lv6_15 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_14 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1F = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1E = VideoFormat_val_read_reg_362) or ((ap_const_lv6_24 = VideoFormat_val_read_reg_362) 
    or ((ap_const_lv6_23 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1D = VideoFormat_val_read_reg_362) or ((ap_const_lv6_B = VideoFormat_val_read_reg_362) or ((ap_const_lv6_A = VideoFormat_val_read_reg_362) or ((ap_const_lv6_10 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_F = VideoFormat_val_read_reg_362) or ((ap_const_lv6_18 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_19 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_22 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_27 = VideoFormat_val_read_reg_362) or ((((not((ap_const_lv6_E = VideoFormat_val_read_reg_362)) and not((ap_const_lv6_D = VideoFormat_val_read_reg_362)) and (icmp_ln1727_fu_327_p2 = ap_const_lv1_1)) or ((ap_const_lv6_D = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 = ap_const_lv1_1))) or (not((ap_const_lv6_E = VideoFormat_val_read_reg_362)) and not((ap_const_lv6_D = VideoFormat_val_read_reg_362)) and not((ap_const_lv6_1A = VideoFormat_val_read_reg_362)))) or ((ap_const_lv6_E = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 
    = ap_const_lv1_1)))))))))))))))))))))))))))))))))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (((ap_const_lv6_E = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 = ap_const_lv1_0)) or ((ap_const_lv6_D = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    VideoFormat_val_read_read_fu_150_p2 <= VideoFormat_val;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_done)
    begin
        if ((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_done)
    begin
        if ((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, VideoFormat_val_read_reg_362, ap_CS_fsm_state2, icmp_ln1727_fu_327_p2, icmp_ln1689_fu_346_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_const_lv6_2B = VideoFormat_val_read_reg_362) or ((ap_const_lv6_2A = VideoFormat_val_read_reg_362) or ((ap_const_lv6_2C = VideoFormat_val_read_reg_362) or ((ap_const_lv6_29 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_13 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_12 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_17 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_16 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_21 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_20 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_26 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_25 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_C = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1C = VideoFormat_val_read_reg_362) or ((ap_const_lv6_15 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_14 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1F = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1E = VideoFormat_val_read_reg_362) or ((ap_const_lv6_24 = VideoFormat_val_read_reg_362) 
    or ((ap_const_lv6_23 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1D = VideoFormat_val_read_reg_362) or ((ap_const_lv6_B = VideoFormat_val_read_reg_362) or ((ap_const_lv6_A = VideoFormat_val_read_reg_362) or ((ap_const_lv6_10 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_F = VideoFormat_val_read_reg_362) or ((ap_const_lv6_18 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_19 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_22 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_27 = VideoFormat_val_read_reg_362) or ((((not((ap_const_lv6_E = VideoFormat_val_read_reg_362)) and not((ap_const_lv6_D = VideoFormat_val_read_reg_362)) and (icmp_ln1727_fu_327_p2 = ap_const_lv1_1)) or ((ap_const_lv6_D = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 = ap_const_lv1_1))) or (not((ap_const_lv6_E = VideoFormat_val_read_reg_362)) and not((ap_const_lv6_D = VideoFormat_val_read_reg_362)) and not((ap_const_lv6_1A = VideoFormat_val_read_reg_362)))) or ((ap_const_lv6_E = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 
    = ap_const_lv1_1)))))))))))))))))))))))))))))))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    bytePlanes_read_assign_proc : process(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_bytePlanes_read, grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_bytePlanes_read, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bytePlanes_read <= grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_bytePlanes_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            bytePlanes_read <= grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_bytePlanes_read;
        else 
            bytePlanes_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_start <= grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_ap_start_reg;
    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_start <= grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_ap_start_reg;
    grp_fu_190_p2 <= std_logic_vector(unsigned(WidthInBytes_val) + unsigned(ap_const_lv15_7));
    grp_fu_196_p4 <= grp_fu_190_p2(14 downto 3);
    grp_fu_206_p3 <= WidthInBytes_val(2 downto 2);
    grp_fu_214_p2 <= (grp_fu_206_p3 xor ap_const_lv1_1);
    icmp_ln1689_fu_346_p2 <= "1" when (y_fu_146 = Height_val_read_reg_366) else "0";
    icmp_ln1727_fu_327_p2 <= "1" when (y_1_fu_142 = Height_val_read_reg_366) else "0";

    img_din_assign_proc : process(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_img_din, grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_img_din, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            img_din <= grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_img_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            img_din <= grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_img_din;
        else 
            img_din <= grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_img_din;
        end if; 
    end process;


    img_write_assign_proc : process(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_img_write, grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_img_write, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            img_write <= grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1696_1_fu_179_img_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            img_write <= grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1734_4_fu_168_img_write;
        else 
            img_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(VideoFormat_val_read_reg_362, ap_CS_fsm_state2, icmp_ln1727_fu_327_p2, icmp_ln1689_fu_346_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_const_lv6_2B = VideoFormat_val_read_reg_362) or ((ap_const_lv6_2A = VideoFormat_val_read_reg_362) or ((ap_const_lv6_2C = VideoFormat_val_read_reg_362) or ((ap_const_lv6_29 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_13 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_12 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_17 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_16 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_21 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_20 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_26 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_25 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_C = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1C = VideoFormat_val_read_reg_362) or ((ap_const_lv6_15 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_14 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1F = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1E = VideoFormat_val_read_reg_362) or ((ap_const_lv6_24 = VideoFormat_val_read_reg_362) 
    or ((ap_const_lv6_23 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_1D = VideoFormat_val_read_reg_362) or ((ap_const_lv6_B = VideoFormat_val_read_reg_362) or ((ap_const_lv6_A = VideoFormat_val_read_reg_362) or ((ap_const_lv6_10 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_F = VideoFormat_val_read_reg_362) or ((ap_const_lv6_18 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_19 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_22 = VideoFormat_val_read_reg_362) or ((ap_const_lv6_27 = VideoFormat_val_read_reg_362) or ((((not((ap_const_lv6_E = VideoFormat_val_read_reg_362)) and not((ap_const_lv6_D = VideoFormat_val_read_reg_362)) and (icmp_ln1727_fu_327_p2 = ap_const_lv1_1)) or ((ap_const_lv6_D = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 = ap_const_lv1_1))) or (not((ap_const_lv6_E = VideoFormat_val_read_reg_362)) and not((ap_const_lv6_D = VideoFormat_val_read_reg_362)) and not((ap_const_lv6_1A = VideoFormat_val_read_reg_362)))) or ((ap_const_lv6_E = VideoFormat_val_read_reg_362) and (icmp_ln1689_fu_346_p2 
    = ap_const_lv1_1)))))))))))))))))))))))))))))))))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub185_fu_313_p2 <= std_logic_vector(unsigned(zext_ln1683_fu_309_p1) + unsigned(ap_const_lv13_1FFF));
    sub309_fu_298_p2 <= std_logic_vector(unsigned(zext_ln1721_fu_294_p1) + unsigned(ap_const_lv13_1FFF));
    y_3_fu_351_p2 <= std_logic_vector(unsigned(y_fu_146) + unsigned(ap_const_lv12_1));
    y_5_fu_332_p2 <= std_logic_vector(unsigned(y_1_fu_142) + unsigned(ap_const_lv12_1));
    zext_ln1683_fu_309_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_196_p4),13));
    zext_ln1721_fu_294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_196_p4),13));
end behav;
