// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_frmbuf_rd_1_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_954_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_din,
        img_full_n,
        img_write,
        img_num_data_valid,
        img_fifo_cap,
        bytePlanes_plane0_dout,
        bytePlanes_plane0_empty_n,
        bytePlanes_plane0_read,
        bytePlanes_plane0_num_data_valid,
        bytePlanes_plane0_fifo_cap,
        bytePlanes_plane1_dout,
        bytePlanes_plane1_empty_n,
        bytePlanes_plane1_read,
        bytePlanes_plane1_num_data_valid,
        bytePlanes_plane1_fifo_cap,
        trunc_ln941_1,
        icmp_ln944,
        cmp83_6,
        cmp83_5,
        cmp83_4,
        icmp6,
        cmp83_2,
        sub79,
        icmp3,
        VideoFormat_val,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [23:0] img_din;
input   img_full_n;
output   img_write;
input  [31:0] img_num_data_valid;
input  [31:0] img_fifo_cap;
input  [63:0] bytePlanes_plane0_dout;
input   bytePlanes_plane0_empty_n;
output   bytePlanes_plane0_read;
input  [10:0] bytePlanes_plane0_num_data_valid;
input  [10:0] bytePlanes_plane0_fifo_cap;
input  [63:0] bytePlanes_plane1_dout;
input   bytePlanes_plane1_empty_n;
output   bytePlanes_plane1_read;
input  [10:0] bytePlanes_plane1_num_data_valid;
input  [10:0] bytePlanes_plane1_fifo_cap;
input  [11:0] trunc_ln941_1;
input  [0:0] icmp_ln944;
input  [0:0] cmp83_6;
input  [0:0] cmp83_5;
input  [0:0] cmp83_4;
input  [0:0] icmp6;
input  [0:0] cmp83_2;
input  [12:0] sub79;
input  [0:0] icmp3;
input  [4:0] VideoFormat_val;
input  [0:0] empty;

reg ap_idle;
reg[23:0] img_din;
reg img_write;
reg bytePlanes_plane0_read;
reg bytePlanes_plane1_read;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg   [0:0] or_ln975_6_reg_573;
reg    ap_block_state9_pp0_stage0_iter1_grp8;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln954_fu_229_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage7;
reg   [0:0] icmp_ln954_reg_541;
reg   [0:0] or_ln975_5_reg_569;
reg    ap_predicate_op105_write_state8;
reg    ap_block_state8_pp0_stage7_iter0_grp7;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage7_subdone;
reg    img_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp2;
reg   [0:0] or_ln975_reg_549;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_grp3;
reg   [0:0] or_ln975_1_reg_553;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_grp4;
reg   [0:0] or_ln975_2_reg_557;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_grp5;
reg   [0:0] or_ln975_3_reg_561;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_grp6;
reg   [0:0] or_ln975_4_reg_565;
wire    ap_block_pp0_stage7_grp7;
wire    ap_block_pp0_stage0_grp8;
reg    bytePlanes_plane0_blk_n;
reg    bytePlanes_plane1_blk_n;
reg   [0:0] and_ln962_reg_545;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] and_ln962_fu_251_p2;
wire   [0:0] or_ln975_fu_263_p2;
wire   [0:0] or_ln975_1_fu_269_p2;
wire   [0:0] or_ln975_2_fu_275_p2;
wire   [0:0] or_ln975_3_fu_281_p2;
wire   [0:0] or_ln975_4_fu_287_p2;
wire   [0:0] or_ln975_5_fu_293_p2;
wire   [0:0] or_ln975_6_fu_299_p2;
reg   [7:0] tmp_1_reg_577;
reg    ap_predicate_op62_read_state2;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
reg   [7:0] tmp_2_reg_582;
reg   [7:0] tmp_4_reg_587;
reg   [7:0] tmp_5_reg_592;
reg   [7:0] tmp_7_reg_597;
reg   [7:0] tmp_8_reg_602;
reg   [7:0] tmp_10_reg_607;
reg   [7:0] tmp_11_reg_612;
reg   [7:0] tmp_13_reg_617;
reg   [7:0] tmp_14_reg_622;
reg   [7:0] tmp_16_reg_627;
reg   [7:0] tmp_17_reg_632;
reg   [7:0] tmp_19_reg_637;
reg   [7:0] tmp_20_reg_642;
reg   [63:0] ap_phi_mux_rdUv_1_phi_fu_213_p4;
wire   [63:0] ap_phi_reg_pp0_iter0_rdUv_1_reg_209;
reg   [11:0] x_fu_120;
wire   [11:0] x_2_fu_235_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_x_1;
wire    ap_block_pp0_stage0;
wire   [23:0] zext_ln976_fu_326_p1;
reg    ap_block_pp0_stage1_01001_grp1;
wire   [23:0] zext_ln976_1_fu_463_p1;
reg    ap_predicate_op85_write_state3;
reg    ap_block_state3_pp0_stage2_iter0_grp2;
reg    ap_block_pp0_stage2_01001_grp2;
wire   [23:0] zext_ln976_2_fu_474_p1;
reg    ap_predicate_op89_write_state4;
reg    ap_block_state4_pp0_stage3_iter0_grp3;
reg    ap_block_pp0_stage3_01001_grp3;
wire   [23:0] zext_ln976_3_fu_485_p1;
reg    ap_predicate_op93_write_state5;
reg    ap_block_state5_pp0_stage4_iter0_grp4;
reg    ap_block_pp0_stage4_01001_grp4;
wire   [23:0] zext_ln976_4_fu_496_p1;
reg    ap_predicate_op97_write_state6;
reg    ap_block_state6_pp0_stage5_iter0_grp5;
reg    ap_block_pp0_stage5_01001_grp5;
wire   [23:0] zext_ln976_5_fu_507_p1;
reg    ap_predicate_op101_write_state7;
reg    ap_block_state7_pp0_stage6_iter0_grp6;
reg    ap_block_pp0_stage6_01001_grp6;
wire   [23:0] zext_ln976_6_fu_518_p1;
reg    ap_block_pp0_stage7_01001_grp7;
wire   [23:0] zext_ln976_7_fu_529_p1;
reg    ap_block_pp0_stage0_01001_grp8;
reg    ap_block_pp0_stage2_11001_grp2;
reg    ap_block_pp0_stage3_11001_grp3;
reg    ap_block_pp0_stage4_11001_grp4;
reg    ap_block_pp0_stage5_11001_grp5;
reg    ap_block_pp0_stage6_11001_grp6;
reg    ap_block_pp0_stage7_11001_grp7;
reg    ap_block_pp0_stage0_11001_grp8;
wire   [0:0] icmp_ln962_fu_245_p2;
wire   [12:0] zext_ln954_fu_241_p1;
wire   [0:0] cmp80_fu_257_p2;
wire   [7:0] trunc_ln976_fu_314_p1;
wire   [7:0] trunc_ln971_fu_310_p1;
wire   [15:0] tmp_s_fu_318_p3;
wire   [15:0] tmp_3_fu_457_p3;
wire   [15:0] tmp_6_fu_468_p3;
wire   [15:0] tmp_9_fu_479_p3;
wire   [15:0] tmp_12_fu_490_p3;
wire   [15:0] tmp_15_fu_501_p3;
wire   [15:0] tmp_18_fu_512_p3;
wire   [15:0] tmp_21_fu_523_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 or_ln975_6_reg_573 = 1'd0;
#0 icmp_ln954_reg_541 = 1'd0;
#0 or_ln975_5_reg_569 = 1'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 or_ln975_reg_549 = 1'd0;
#0 or_ln975_1_reg_553 = 1'd0;
#0 or_ln975_2_reg_557 = 1'd0;
#0 or_ln975_3_reg_561 = 1'd0;
#0 or_ln975_4_reg_565 = 1'd0;
#0 and_ln962_reg_545 = 1'd0;
#0 tmp_1_reg_577 = 8'd0;
#0 tmp_2_reg_582 = 8'd0;
#0 tmp_4_reg_587 = 8'd0;
#0 tmp_5_reg_592 = 8'd0;
#0 tmp_7_reg_597 = 8'd0;
#0 tmp_8_reg_602 = 8'd0;
#0 tmp_10_reg_607 = 8'd0;
#0 tmp_11_reg_612 = 8'd0;
#0 tmp_13_reg_617 = 8'd0;
#0 tmp_14_reg_622 = 8'd0;
#0 tmp_16_reg_627 = 8'd0;
#0 tmp_17_reg_632 = 8'd0;
#0 tmp_19_reg_637 = 8'd0;
#0 tmp_20_reg_642 = 8'd0;
#0 x_fu_120 = 12'd0;
#0 ap_done_reg = 1'b0;
end

design_1_v_frmbuf_rd_1_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        and_ln962_reg_545 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            and_ln962_reg_545 <= and_ln962_fu_251_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln954_reg_541 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            icmp_ln954_reg_541 <= icmp_ln954_fu_229_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        or_ln975_1_reg_553 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            or_ln975_1_reg_553 <= or_ln975_1_fu_269_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        or_ln975_2_reg_557 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            or_ln975_2_reg_557 <= or_ln975_2_fu_275_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        or_ln975_3_reg_561 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            or_ln975_3_reg_561 <= or_ln975_3_fu_281_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        or_ln975_4_reg_565 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            or_ln975_4_reg_565 <= or_ln975_4_fu_287_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        or_ln975_5_reg_569 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            or_ln975_5_reg_569 <= or_ln975_5_fu_293_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        or_ln975_6_reg_573 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            or_ln975_6_reg_573 <= or_ln975_6_fu_299_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        or_ln975_reg_549 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            or_ln975_reg_549 <= or_ln975_fu_263_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_10_reg_607 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_10_reg_607 <= {{bytePlanes_plane0_dout[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_11_reg_612 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_11_reg_612 <= {{ap_phi_mux_rdUv_1_phi_fu_213_p4[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_13_reg_617 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_13_reg_617 <= {{bytePlanes_plane0_dout[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_14_reg_622 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_14_reg_622 <= {{ap_phi_mux_rdUv_1_phi_fu_213_p4[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_16_reg_627 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_16_reg_627 <= {{bytePlanes_plane0_dout[55:48]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_17_reg_632 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_17_reg_632 <= {{ap_phi_mux_rdUv_1_phi_fu_213_p4[55:48]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_19_reg_637 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_19_reg_637 <= {{bytePlanes_plane0_dout[63:56]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_1_reg_577 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_1_reg_577 <= {{bytePlanes_plane0_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_20_reg_642 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_20_reg_642 <= {{ap_phi_mux_rdUv_1_phi_fu_213_p4[63:56]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_2_reg_582 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_2_reg_582 <= {{ap_phi_mux_rdUv_1_phi_fu_213_p4[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_4_reg_587 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_4_reg_587 <= {{bytePlanes_plane0_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_5_reg_592 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_5_reg_592 <= {{ap_phi_mux_rdUv_1_phi_fu_213_p4[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_7_reg_597 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_7_reg_597 <= {{bytePlanes_plane0_dout[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_8_reg_602 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_8_reg_602 <= {{ap_phi_mux_rdUv_1_phi_fu_213_p4[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        x_fu_120 <= 12'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            if (((icmp_ln954_fu_229_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                x_fu_120 <= x_2_fu_235_p2;
            end else if ((ap_loop_init == 1'b1)) begin
                x_fu_120 <= 12'd0;
            end
        end
    end
end

always @ (*) begin
    if (((icmp_ln954_fu_229_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln954_reg_541 == 1'd0) & (1'd0 == and_ln962_reg_545))) begin
        ap_phi_mux_rdUv_1_phi_fu_213_p4 = bytePlanes_plane1_dout;
    end else begin
        ap_phi_mux_rdUv_1_phi_fu_213_p4 = ap_phi_reg_pp0_iter0_rdUv_1_reg_209;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_1 = 12'd0;
    end else begin
        ap_sig_allocacmp_x_1 = x_fu_120;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln954_reg_541 == 1'd0) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bytePlanes_plane0_blk_n = bytePlanes_plane0_empty_n;
    end else begin
        bytePlanes_plane0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln954_reg_541 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bytePlanes_plane0_read = 1'b1;
    end else begin
        bytePlanes_plane0_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln954_reg_541 == 1'd0) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'd0 == and_ln962_reg_545) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bytePlanes_plane1_blk_n = bytePlanes_plane1_empty_n;
    end else begin
        bytePlanes_plane1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (ap_predicate_op62_read_state2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bytePlanes_plane1_read = 1'b1;
    end else begin
        bytePlanes_plane1_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op105_write_state8 == 1'b1) & (1'b0 == ap_block_pp0_stage7_grp7) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln954_reg_541 == 1'd0) & (1'b0 == ap_block_pp0_stage6_grp6) & (1'b1 == ap_CS_fsm_pp0_stage6) & (or_ln975_4_reg_565 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln954_reg_541 == 1'd0) & (1'b0 == ap_block_pp0_stage5_grp5) & (1'b1 == ap_CS_fsm_pp0_stage5) & (or_ln975_3_reg_561 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln954_reg_541 == 1'd0) & (1'b0 == ap_block_pp0_stage4_grp4) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln975_2_reg_557 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln954_reg_541 == 1'd0) & (1'b0 == ap_block_pp0_stage3_grp3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln975_1_reg_553 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln954_reg_541 == 1'd0) & (1'b0 == ap_block_pp0_stage2_grp2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (or_ln975_reg_549 == 1'd1)) | 
    ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln954_reg_541 == 1'd0) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_grp8) & (or_ln975_6_reg_573 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_blk_n = img_full_n;
    end else begin
        img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp8) & (or_ln975_6_reg_573 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_din = zext_ln976_7_fu_529_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op105_write_state8 == 1'b1) & (1'b0 == ap_block_pp0_stage7_01001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        img_din = zext_ln976_6_fu_518_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_01001_grp6) & (ap_predicate_op101_write_state7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        img_din = zext_ln976_5_fu_507_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_01001_grp5) & (ap_predicate_op97_write_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        img_din = zext_ln976_4_fu_496_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_01001_grp4) & (ap_predicate_op93_write_state5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        img_din = zext_ln976_3_fu_485_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_01001_grp3) & (ap_predicate_op89_write_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        img_din = zext_ln976_2_fu_474_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_01001_grp2) & (ap_predicate_op85_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        img_din = zext_ln976_1_fu_463_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln954_reg_541 == 1'd0) & (1'b0 == ap_block_pp0_stage1_01001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_din = zext_ln976_fu_326_p1;
    end else begin
        img_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op105_write_state8 == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln954_reg_541 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001_grp6) & (ap_predicate_op101_write_state7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001_grp5) & (ap_predicate_op97_write_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp4) & (ap_predicate_op93_write_state5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (ap_predicate_op89_write_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp2) 
    & (ap_predicate_op85_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001_grp8) & (or_ln975_6_reg_573 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_write = 1'b1;
    end else begin
        img_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln962_fu_251_p2 = (icmp_ln962_fu_245_p2 & empty);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp8 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1_grp8));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1_grp8));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp8 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1_grp8));
end

assign ap_block_pp0_stage0_grp8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1_grp8));
end

always @ (*) begin
    ap_block_pp0_stage1_01001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage2_01001_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp2));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp2));
end

assign ap_block_pp0_stage2_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp2));
end

always @ (*) begin
    ap_block_pp0_stage3_01001_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp3));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp3));
end

assign ap_block_pp0_stage3_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp3));
end

always @ (*) begin
    ap_block_pp0_stage4_01001_grp4 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp4));
end

always @ (*) begin
    ap_block_pp0_stage4_11001_grp4 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp4));
end

assign ap_block_pp0_stage4_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp4));
end

always @ (*) begin
    ap_block_pp0_stage5_01001_grp5 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0_grp5));
end

always @ (*) begin
    ap_block_pp0_stage5_11001_grp5 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0_grp5));
end

assign ap_block_pp0_stage5_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0_grp5));
end

always @ (*) begin
    ap_block_pp0_stage6_01001_grp6 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp6));
end

always @ (*) begin
    ap_block_pp0_stage6_11001_grp6 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp6));
end

assign ap_block_pp0_stage6_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp6));
end

always @ (*) begin
    ap_block_pp0_stage7_01001_grp7 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0_grp7));
end

always @ (*) begin
    ap_block_pp0_stage7_11001_grp7 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0_grp7));
end

assign ap_block_pp0_stage7_grp7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0_grp7));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = (((icmp_ln954_reg_541 == 1'd0) & (img_full_n == 1'b0)) | ((icmp_ln954_reg_541 == 1'd0) & (bytePlanes_plane0_empty_n == 1'b0)) | ((bytePlanes_plane1_empty_n == 1'b0) & (ap_predicate_op62_read_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0_grp2 = ((img_full_n == 1'b0) & (ap_predicate_op85_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0_grp3 = ((img_full_n == 1'b0) & (ap_predicate_op89_write_state4 == 1'b1));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0_grp4 = ((img_full_n == 1'b0) & (ap_predicate_op93_write_state5 == 1'b1));
end

always @ (*) begin
    ap_block_state6_pp0_stage5_iter0_grp5 = ((img_full_n == 1'b0) & (ap_predicate_op97_write_state6 == 1'b1));
end

always @ (*) begin
    ap_block_state7_pp0_stage6_iter0_grp6 = ((img_full_n == 1'b0) & (ap_predicate_op101_write_state7 == 1'b1));
end

always @ (*) begin
    ap_block_state8_pp0_stage7_iter0_grp7 = ((ap_predicate_op105_write_state8 == 1'b1) & (img_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter1_grp8 = ((or_ln975_6_reg_573 == 1'd1) & (img_full_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_rdUv_1_reg_209 = 'bx;

always @ (*) begin
    ap_predicate_op101_write_state7 = ((icmp_ln954_reg_541 == 1'd0) & (or_ln975_4_reg_565 == 1'd1));
end

always @ (*) begin
    ap_predicate_op105_write_state8 = ((or_ln975_5_reg_569 == 1'd1) & (icmp_ln954_reg_541 == 1'd0));
end

always @ (*) begin
    ap_predicate_op62_read_state2 = ((icmp_ln954_reg_541 == 1'd0) & (1'd0 == and_ln962_reg_545));
end

always @ (*) begin
    ap_predicate_op85_write_state3 = ((icmp_ln954_reg_541 == 1'd0) & (or_ln975_reg_549 == 1'd1));
end

always @ (*) begin
    ap_predicate_op89_write_state4 = ((icmp_ln954_reg_541 == 1'd0) & (or_ln975_1_reg_553 == 1'd1));
end

always @ (*) begin
    ap_predicate_op93_write_state5 = ((icmp_ln954_reg_541 == 1'd0) & (or_ln975_2_reg_557 == 1'd1));
end

always @ (*) begin
    ap_predicate_op97_write_state6 = ((icmp_ln954_reg_541 == 1'd0) & (or_ln975_3_reg_561 == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign cmp80_fu_257_p2 = (($signed(zext_ln954_fu_241_p1) < $signed(sub79)) ? 1'b1 : 1'b0);

assign icmp_ln954_fu_229_p2 = ((ap_sig_allocacmp_x_1 == trunc_ln941_1) ? 1'b1 : 1'b0);

assign icmp_ln962_fu_245_p2 = ((VideoFormat_val == 5'd19) ? 1'b1 : 1'b0);

assign or_ln975_1_fu_269_p2 = (cmp83_2 | cmp80_fu_257_p2);

assign or_ln975_2_fu_275_p2 = (icmp6 | cmp80_fu_257_p2);

assign or_ln975_3_fu_281_p2 = (cmp83_4 | cmp80_fu_257_p2);

assign or_ln975_4_fu_287_p2 = (cmp83_5 | cmp80_fu_257_p2);

assign or_ln975_5_fu_293_p2 = (cmp83_6 | cmp80_fu_257_p2);

assign or_ln975_6_fu_299_p2 = (icmp_ln944 | cmp80_fu_257_p2);

assign or_ln975_fu_263_p2 = (icmp3 | cmp80_fu_257_p2);

assign tmp_12_fu_490_p3 = {{tmp_11_reg_612}, {tmp_10_reg_607}};

assign tmp_15_fu_501_p3 = {{tmp_14_reg_622}, {tmp_13_reg_617}};

assign tmp_18_fu_512_p3 = {{tmp_17_reg_632}, {tmp_16_reg_627}};

assign tmp_21_fu_523_p3 = {{tmp_20_reg_642}, {tmp_19_reg_637}};

assign tmp_3_fu_457_p3 = {{tmp_2_reg_582}, {tmp_1_reg_577}};

assign tmp_6_fu_468_p3 = {{tmp_5_reg_592}, {tmp_4_reg_587}};

assign tmp_9_fu_479_p3 = {{tmp_8_reg_602}, {tmp_7_reg_597}};

assign tmp_s_fu_318_p3 = {{trunc_ln976_fu_314_p1}, {trunc_ln971_fu_310_p1}};

assign trunc_ln971_fu_310_p1 = bytePlanes_plane0_dout[7:0];

assign trunc_ln976_fu_314_p1 = ap_phi_mux_rdUv_1_phi_fu_213_p4[7:0];

assign x_2_fu_235_p2 = (ap_sig_allocacmp_x_1 + 12'd1);

assign zext_ln954_fu_241_p1 = ap_sig_allocacmp_x_1;

assign zext_ln976_1_fu_463_p1 = tmp_3_fu_457_p3;

assign zext_ln976_2_fu_474_p1 = tmp_6_fu_468_p3;

assign zext_ln976_3_fu_485_p1 = tmp_9_fu_479_p3;

assign zext_ln976_4_fu_496_p1 = tmp_12_fu_490_p3;

assign zext_ln976_5_fu_507_p1 = tmp_15_fu_501_p3;

assign zext_ln976_6_fu_518_p1 = tmp_18_fu_512_p3;

assign zext_ln976_7_fu_529_p1 = tmp_21_fu_523_p3;

assign zext_ln976_fu_326_p1 = tmp_s_fu_318_p3;

endmodule //design_1_v_frmbuf_rd_1_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_954_1
