// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_mix_0_0_AXIvideo2MultiPixStream (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_axis_video2_TDATA,
        s_axis_video2_TVALID,
        s_axis_video2_TREADY,
        s_axis_video2_TKEEP,
        s_axis_video2_TSTRB,
        s_axis_video2_TUSER,
        s_axis_video2_TLAST,
        s_axis_video2_TID,
        s_axis_video2_TDEST,
        srcLayer2_din,
        srcLayer2_full_n,
        srcLayer2_write,
        srcLayer2_num_data_valid,
        srcLayer2_fifo_cap,
        HwReg_layerHeight_2_val,
        HwReg_layerWidth_2_val,
        HwReg_layerEnableFlag_2_val
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [23:0] s_axis_video2_TDATA;
input   s_axis_video2_TVALID;
output   s_axis_video2_TREADY;
input  [2:0] s_axis_video2_TKEEP;
input  [2:0] s_axis_video2_TSTRB;
input  [0:0] s_axis_video2_TUSER;
input  [0:0] s_axis_video2_TLAST;
input  [0:0] s_axis_video2_TID;
input  [0:0] s_axis_video2_TDEST;
output  [23:0] srcLayer2_din;
input   srcLayer2_full_n;
output   srcLayer2_write;
input  [2:0] srcLayer2_num_data_valid;
input  [2:0] srcLayer2_fifo_cap;
input  [11:0] HwReg_layerHeight_2_val;
input  [11:0] HwReg_layerWidth_2_val;
input  [0:0] HwReg_layerEnableFlag_2_val;

reg ap_done;
reg ap_idle;
reg start_write;
reg s_axis_video2_TREADY;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    ap_block_state1;
wire   [0:0] HwReg_layerEnableFlag_2_val_read_read_fu_112_p2;
reg   [0:0] HwReg_layerEnableFlag_2_val_read_reg_437;
wire    ap_CS_fsm_state2;
wire   [11:0] grp_reg_unsigned_short_s_fu_211_ap_return;
reg   [11:0] rows_reg_441;
wire   [11:0] grp_reg_unsigned_short_s_fu_217_ap_return;
reg   [11:0] cols_reg_446;
wire   [0:0] cmp10403_i_i_fu_269_p2;
reg   [0:0] cmp10403_i_i_reg_469;
wire    ap_CS_fsm_state4;
wire   [0:0] xor_ln3436_fu_274_p2;
reg   [0:0] xor_ln3436_reg_474;
wire   [0:0] and_ln3436_fu_298_p2;
reg   [0:0] and_ln3436_reg_485;
wire    ap_CS_fsm_state5;
wire   [0:0] select_ln3436_fu_354_p3;
reg   [0:0] select_ln3436_reg_496;
wire    ap_CS_fsm_state7;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_ready;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_s_axis_video2_TREADY;
wire   [23:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_data_i_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_data_i_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_last_i_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_last_i_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_ready;
wire   [23:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_srcLayer2_din;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_srcLayer2_write;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_s_axis_video2_TREADY;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_eol_i_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_eol_i_out_ap_vld;
wire   [23:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_axi_data_18_i_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_axi_data_18_i_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_ready;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_s_axis_video2_TREADY;
wire   [23:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_data_19_i_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_data_19_i_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_last_23_i_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_last_23_i_out_ap_vld;
reg    grp_reg_unsigned_short_s_fu_211_ap_start;
wire    grp_reg_unsigned_short_s_fu_211_ap_done;
wire    grp_reg_unsigned_short_s_fu_211_ap_idle;
wire    grp_reg_unsigned_short_s_fu_211_ap_ready;
reg    grp_reg_unsigned_short_s_fu_211_ap_ce;
reg    ap_block_state1_ignore_call13;
reg    grp_reg_unsigned_short_s_fu_217_ap_start;
wire    grp_reg_unsigned_short_s_fu_217_ap_done;
wire    grp_reg_unsigned_short_s_fu_217_ap_idle;
wire    grp_reg_unsigned_short_s_fu_217_ap_ready;
reg    grp_reg_unsigned_short_s_fu_217_ap_ce;
reg    ap_block_state1_ignore_call14;
reg   [0:0] sof_reg_118;
wire    ap_CS_fsm_state9;
reg   [0:0] axi_last_reg_130;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [23:0] axi_data_fu_92;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start_reg;
wire   [0:0] icmp_ln3387_fu_283_p2;
wire    ap_CS_fsm_state6;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start_reg;
wire    ap_CS_fsm_state8;
reg   [0:0] axi_last_23_i_loc_fu_76;
reg   [11:0] i_fu_96;
wire   [11:0] i_8_fu_288_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start_reg = 1'b0;
#0 i_fu_96 = 12'd0;
end

design_1_v_mix_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_ready),
    .s_axis_video2_TVALID(s_axis_video2_TVALID),
    .s_axis_video2_TDATA(s_axis_video2_TDATA),
    .s_axis_video2_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_s_axis_video2_TREADY),
    .s_axis_video2_TKEEP(s_axis_video2_TKEEP),
    .s_axis_video2_TSTRB(s_axis_video2_TSTRB),
    .s_axis_video2_TUSER(s_axis_video2_TUSER),
    .s_axis_video2_TLAST(s_axis_video2_TLAST),
    .s_axis_video2_TID(s_axis_video2_TID),
    .s_axis_video2_TDEST(s_axis_video2_TDEST),
    .axi_data_i_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_data_i_out),
    .axi_data_i_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_data_i_out_ap_vld),
    .axi_last_i_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_last_i_out),
    .axi_last_i_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_last_i_out_ap_vld)
);

design_1_v_mix_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_ready),
    .s_axis_video2_TVALID(s_axis_video2_TVALID),
    .srcLayer2_din(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_srcLayer2_din),
    .srcLayer2_full_n(srcLayer2_full_n),
    .srcLayer2_write(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_srcLayer2_write),
    .srcLayer2_num_data_valid(3'd0),
    .srcLayer2_fifo_cap(3'd0),
    .sof_10_i(sof_reg_118),
    .axi_last_21_i(axi_last_reg_130),
    .axi_data_17_i(axi_data_fu_92),
    .cols_i(cols_reg_446),
    .s_axis_video2_TDATA(s_axis_video2_TDATA),
    .s_axis_video2_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_s_axis_video2_TREADY),
    .s_axis_video2_TKEEP(s_axis_video2_TKEEP),
    .s_axis_video2_TSTRB(s_axis_video2_TSTRB),
    .s_axis_video2_TUSER(s_axis_video2_TUSER),
    .s_axis_video2_TLAST(s_axis_video2_TLAST),
    .s_axis_video2_TID(s_axis_video2_TID),
    .s_axis_video2_TDEST(s_axis_video2_TDEST),
    .eol_i_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_eol_i_out),
    .eol_i_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_eol_i_out_ap_vld),
    .axi_data_18_i_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_axi_data_18_i_out),
    .axi_data_18_i_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_axi_data_18_i_out_ap_vld)
);

design_1_v_mix_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_ready),
    .s_axis_video2_TVALID(s_axis_video2_TVALID),
    .axi_data_18_i_reload(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_axi_data_18_i_out),
    .select_ln3436_i(select_ln3436_reg_496),
    .eol_i_reload(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_eol_i_out),
    .s_axis_video2_TDATA(s_axis_video2_TDATA),
    .s_axis_video2_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_s_axis_video2_TREADY),
    .s_axis_video2_TKEEP(s_axis_video2_TKEEP),
    .s_axis_video2_TSTRB(s_axis_video2_TSTRB),
    .s_axis_video2_TUSER(s_axis_video2_TUSER),
    .s_axis_video2_TLAST(s_axis_video2_TLAST),
    .s_axis_video2_TID(s_axis_video2_TID),
    .s_axis_video2_TDEST(s_axis_video2_TDEST),
    .axi_data_19_i_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_data_19_i_out),
    .axi_data_19_i_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_data_19_i_out_ap_vld),
    .axi_last_23_i_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_last_23_i_out),
    .axi_last_23_i_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_last_23_i_out_ap_vld)
);

design_1_v_mix_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_211(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_211_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_211_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_211_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_211_ap_ready),
    .ap_ce(grp_reg_unsigned_short_s_fu_211_ap_ce),
    .d(HwReg_layerHeight_2_val),
    .ap_return(grp_reg_unsigned_short_s_fu_211_ap_return)
);

design_1_v_mix_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_217(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_217_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_217_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_217_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_217_ap_ready),
    .ap_ce(grp_reg_unsigned_short_s_fu_217_ap_ce),
    .d(HwReg_layerWidth_2_val),
    .ap_return(grp_reg_unsigned_short_s_fu_217_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & ((1'd0 == HwReg_layerEnableFlag_2_val_read_reg_437) | (icmp_ln3387_fu_283_p2 == 1'd1)))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start_reg <= 1'b0;
    end else begin
        if (((1'd1 == HwReg_layerEnableFlag_2_val_read_read_fu_112_p2) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln3387_fu_283_p2 == 1'd0) & (1'd1 == HwReg_layerEnableFlag_2_val_read_reg_437) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_data_19_i_out_ap_vld == 1'b1))) begin
        axi_data_fu_92 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_data_19_i_out;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_data_i_out_ap_vld == 1'b1))) begin
        axi_data_fu_92 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_data_i_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        axi_last_reg_130 <= axi_last_23_i_loc_fu_76;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_last_reg_130 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_axi_last_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == HwReg_layerEnableFlag_2_val_read_read_fu_112_p2) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_96 <= 12'd0;
    end else if (((icmp_ln3387_fu_283_p2 == 1'd0) & (1'd1 == HwReg_layerEnableFlag_2_val_read_reg_437) & (1'b1 == ap_CS_fsm_state5))) begin
        i_fu_96 <= i_8_fu_288_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        sof_reg_118 <= and_ln3436_reg_485;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        sof_reg_118 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        HwReg_layerEnableFlag_2_val_read_reg_437 <= HwReg_layerEnableFlag_2_val;
        cols_reg_446 <= grp_reg_unsigned_short_s_fu_217_ap_return;
        rows_reg_441 <= grp_reg_unsigned_short_s_fu_211_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        and_ln3436_reg_485 <= and_ln3436_fu_298_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_last_23_i_out_ap_vld == 1'b1))) begin
        axi_last_23_i_loc_fu_76 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_axi_last_23_i_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cmp10403_i_i_reg_469 <= cmp10403_i_i_fu_269_p2;
        xor_ln3436_reg_474 <= xor_ln3436_fu_274_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        select_ln3436_reg_496 <= select_ln3436_fu_354_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((1'd0 == HwReg_layerEnableFlag_2_val_read_reg_437) | (icmp_ln3387_fu_283_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1_ignore_call13) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_reg_unsigned_short_s_fu_211_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_211_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b0 == ap_block_state1_ignore_call13) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_reg_unsigned_short_s_fu_211_ap_start = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_211_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1_ignore_call14) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_reg_unsigned_short_s_fu_217_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_217_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b0 == ap_block_state1_ignore_call14) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_reg_unsigned_short_s_fu_217_ap_start = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_217_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((1'd0 == HwReg_layerEnableFlag_2_val_read_reg_437) | (icmp_ln3387_fu_283_p2 == 1'd1)))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        s_axis_video2_TREADY = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_s_axis_video2_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        s_axis_video2_TREADY = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_s_axis_video2_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_video2_TREADY = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_s_axis_video2_TREADY;
    end else begin
        s_axis_video2_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'd0 == HwReg_layerEnableFlag_2_val_read_read_fu_112_p2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & ((1'd0 == HwReg_layerEnableFlag_2_val_read_reg_437) | (icmp_ln3387_fu_283_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HwReg_layerEnableFlag_2_val_read_read_fu_112_p2 = HwReg_layerEnableFlag_2_val;

assign and_ln3436_fu_298_p2 = (xor_ln3436_reg_474 & sof_reg_118);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call13 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call14 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign cmp10403_i_i_fu_269_p2 = ((cols_reg_446 != 12'd0) ? 1'b1 : 1'b0);

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_ap_start_reg;

assign i_8_fu_288_p2 = (i_fu_96 + 12'd1);

assign icmp_ln3387_fu_283_p2 = ((i_fu_96 == rows_reg_441) ? 1'b1 : 1'b0);

assign select_ln3436_fu_354_p3 = ((cmp10403_i_i_reg_469[0:0] == 1'b1) ? grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_eol_i_out : axi_last_reg_130);

assign srcLayer2_din = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_srcLayer2_din;

assign srcLayer2_write = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160_srcLayer2_write;

assign start_out = real_start;

assign xor_ln3436_fu_274_p2 = (cmp10403_i_i_fu_269_p2 ^ 1'd1);

endmodule //design_1_v_mix_0_0_AXIvideo2MultiPixStream
