// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_mix_0_0_VMixHlsDataFlowFunction (
        HwReg_width_val,
        HwReg_height_val,
        HwReg_background_Y_R_val12,
        HwReg_background_U_G_val13,
        HwReg_background_V_B_val14,
        HwReg_layerEnable_val16,
        HwReg_layerEnableFlag_0_val,
        HwReg_layerEnableFlag_1_val,
        HwReg_layerEnableFlag_2_val,
        HwReg_layerAlpha_2_val17,
        HwReg_layerStartX_1_val18,
        HwReg_layerStartX_2_val19,
        HwReg_layerStartY_1_val20,
        HwReg_layerStartY_2_val21,
        HwReg_layerWidth_1_val,
        HwReg_layerWidth_2_val,
        HwReg_layerHeight_1_val,
        HwReg_layerHeight_2_val,
        HwReg_layerScaleFactor_1_val26,
        HwReg_layerScaleFactor_2_val27,
        s_axis_video_TDATA,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        s_axis_video1_TDATA,
        s_axis_video1_TKEEP,
        s_axis_video1_TSTRB,
        s_axis_video1_TUSER,
        s_axis_video1_TLAST,
        s_axis_video1_TID,
        s_axis_video1_TDEST,
        s_axis_video2_TDATA,
        s_axis_video2_TKEEP,
        s_axis_video2_TSTRB,
        s_axis_video2_TUSER,
        s_axis_video2_TLAST,
        s_axis_video2_TID,
        s_axis_video2_TDEST,
        m_axis_video_TDATA,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        ap_clk,
        ap_rst,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        HwReg_height_val_ap_vld,
        HwReg_width_val_ap_vld,
        HwReg_layerEnableFlag_0_val_ap_vld,
        ap_start,
        s_axis_video1_TVALID,
        s_axis_video1_TREADY,
        HwReg_layerHeight_1_val_ap_vld,
        HwReg_layerWidth_1_val_ap_vld,
        HwReg_layerEnableFlag_1_val_ap_vld,
        HwReg_background_Y_R_val12_ap_vld,
        HwReg_background_U_G_val13_ap_vld,
        HwReg_background_V_B_val14_ap_vld,
        HwReg_layerEnable_val16_ap_vld,
        HwReg_layerStartX_1_val18_ap_vld,
        HwReg_layerStartY_1_val20_ap_vld,
        HwReg_layerScaleFactor_1_val26_ap_vld,
        s_axis_video2_TVALID,
        s_axis_video2_TREADY,
        HwReg_layerHeight_2_val_ap_vld,
        HwReg_layerWidth_2_val_ap_vld,
        HwReg_layerEnableFlag_2_val_ap_vld,
        HwReg_layerAlpha_2_val17_ap_vld,
        HwReg_layerStartX_2_val19_ap_vld,
        HwReg_layerStartY_2_val21_ap_vld,
        HwReg_layerScaleFactor_2_val27_ap_vld,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [11:0] HwReg_width_val;
input  [11:0] HwReg_height_val;
input  [7:0] HwReg_background_Y_R_val12;
input  [7:0] HwReg_background_U_G_val13;
input  [7:0] HwReg_background_V_B_val14;
input  [2:0] HwReg_layerEnable_val16;
input  [0:0] HwReg_layerEnableFlag_0_val;
input  [0:0] HwReg_layerEnableFlag_1_val;
input  [0:0] HwReg_layerEnableFlag_2_val;
input  [8:0] HwReg_layerAlpha_2_val17;
input  [15:0] HwReg_layerStartX_1_val18;
input  [15:0] HwReg_layerStartX_2_val19;
input  [15:0] HwReg_layerStartY_1_val20;
input  [15:0] HwReg_layerStartY_2_val21;
input  [15:0] HwReg_layerWidth_1_val;
input  [15:0] HwReg_layerWidth_2_val;
input  [15:0] HwReg_layerHeight_1_val;
input  [15:0] HwReg_layerHeight_2_val;
input  [7:0] HwReg_layerScaleFactor_1_val26;
input  [7:0] HwReg_layerScaleFactor_2_val27;
input  [23:0] s_axis_video_TDATA;
input  [2:0] s_axis_video_TKEEP;
input  [2:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
input  [23:0] s_axis_video1_TDATA;
input  [2:0] s_axis_video1_TKEEP;
input  [2:0] s_axis_video1_TSTRB;
input  [0:0] s_axis_video1_TUSER;
input  [0:0] s_axis_video1_TLAST;
input  [0:0] s_axis_video1_TID;
input  [0:0] s_axis_video1_TDEST;
input  [23:0] s_axis_video2_TDATA;
input  [2:0] s_axis_video2_TKEEP;
input  [2:0] s_axis_video2_TSTRB;
input  [0:0] s_axis_video2_TUSER;
input  [0:0] s_axis_video2_TLAST;
input  [0:0] s_axis_video2_TID;
input  [0:0] s_axis_video2_TDEST;
output  [23:0] m_axis_video_TDATA;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input   ap_clk;
input   ap_rst;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input   HwReg_height_val_ap_vld;
input   HwReg_width_val_ap_vld;
input   HwReg_layerEnableFlag_0_val_ap_vld;
input   ap_start;
input   s_axis_video1_TVALID;
output   s_axis_video1_TREADY;
input   HwReg_layerHeight_1_val_ap_vld;
input   HwReg_layerWidth_1_val_ap_vld;
input   HwReg_layerEnableFlag_1_val_ap_vld;
input   HwReg_background_Y_R_val12_ap_vld;
input   HwReg_background_U_G_val13_ap_vld;
input   HwReg_background_V_B_val14_ap_vld;
input   HwReg_layerEnable_val16_ap_vld;
input   HwReg_layerStartX_1_val18_ap_vld;
input   HwReg_layerStartY_1_val20_ap_vld;
input   HwReg_layerScaleFactor_1_val26_ap_vld;
input   s_axis_video2_TVALID;
output   s_axis_video2_TREADY;
input   HwReg_layerHeight_2_val_ap_vld;
input   HwReg_layerWidth_2_val_ap_vld;
input   HwReg_layerEnableFlag_2_val_ap_vld;
input   HwReg_layerAlpha_2_val17_ap_vld;
input   HwReg_layerStartX_2_val19_ap_vld;
input   HwReg_layerStartY_2_val21_ap_vld;
input   HwReg_layerScaleFactor_2_val27_ap_vld;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    AXIvideo2MultiPixStream_1_U0_ap_start;
wire    AXIvideo2MultiPixStream_1_U0_ap_done;
wire    AXIvideo2MultiPixStream_1_U0_ap_continue;
wire    AXIvideo2MultiPixStream_1_U0_ap_idle;
wire    AXIvideo2MultiPixStream_1_U0_ap_ready;
wire    AXIvideo2MultiPixStream_1_U0_start_out;
wire    AXIvideo2MultiPixStream_1_U0_start_write;
wire    AXIvideo2MultiPixStream_1_U0_s_axis_video_TREADY;
wire   [23:0] AXIvideo2MultiPixStream_1_U0_srcLayer0_din;
wire    AXIvideo2MultiPixStream_1_U0_srcLayer0_write;
wire    v_mix_420_to_422_false_2_U0_ap_start;
wire    v_mix_420_to_422_false_2_U0_ap_done;
wire    v_mix_420_to_422_false_2_U0_ap_continue;
wire    v_mix_420_to_422_false_2_U0_ap_idle;
wire    v_mix_420_to_422_false_2_U0_ap_ready;
wire    v_mix_420_to_422_false_2_U0_start_out;
wire    v_mix_420_to_422_false_2_U0_start_write;
wire    v_mix_420_to_422_false_2_U0_srcLayer0_read;
wire   [23:0] v_mix_420_to_422_false_2_U0_srcLayer0Yuv422_din;
wire    v_mix_420_to_422_false_2_U0_srcLayer0Yuv422_write;
wire   [31:0] v_mix_420_to_422_false_2_U0_srcLayer0Yuv422_num_data_valid;
wire   [31:0] v_mix_420_to_422_false_2_U0_srcLayer0Yuv422_fifo_cap;
wire    v_mix_422_to_444_false_3_U0_ap_start;
wire    v_mix_422_to_444_false_3_U0_ap_done;
wire    v_mix_422_to_444_false_3_U0_ap_continue;
wire    v_mix_422_to_444_false_3_U0_ap_idle;
wire    v_mix_422_to_444_false_3_U0_ap_ready;
wire    v_mix_422_to_444_false_3_U0_start_out;
wire    v_mix_422_to_444_false_3_U0_start_write;
wire    v_mix_422_to_444_false_3_U0_srcLayer0Yuv422_read;
wire   [23:0] v_mix_422_to_444_false_3_U0_srcLayer0Yuv_din;
wire    v_mix_422_to_444_false_3_U0_srcLayer0Yuv_write;
wire   [31:0] v_mix_422_to_444_false_3_U0_srcLayer0Yuv_num_data_valid;
wire   [31:0] v_mix_422_to_444_false_3_U0_srcLayer0Yuv_fifo_cap;
wire    v_mix_yuv2rgb_false_4_U0_ap_start;
wire    v_mix_yuv2rgb_false_4_U0_ap_done;
wire    v_mix_yuv2rgb_false_4_U0_ap_continue;
wire    v_mix_yuv2rgb_false_4_U0_ap_idle;
wire    v_mix_yuv2rgb_false_4_U0_ap_ready;
wire    v_mix_yuv2rgb_false_4_U0_start_out;
wire    v_mix_yuv2rgb_false_4_U0_start_write;
wire    v_mix_yuv2rgb_false_4_U0_srcLayer0Yuv_read;
wire   [23:0] v_mix_yuv2rgb_false_4_U0_outLayer0_din;
wire    v_mix_yuv2rgb_false_4_U0_outLayer0_write;
wire   [31:0] v_mix_yuv2rgb_false_4_U0_outLayer0_num_data_valid;
wire   [31:0] v_mix_yuv2rgb_false_4_U0_outLayer0_fifo_cap;
wire    AXIvideo2MultiPixStream_5_U0_ap_start;
wire    AXIvideo2MultiPixStream_5_U0_ap_done;
wire    AXIvideo2MultiPixStream_5_U0_ap_continue;
wire    AXIvideo2MultiPixStream_5_U0_ap_idle;
wire    AXIvideo2MultiPixStream_5_U0_ap_ready;
wire    AXIvideo2MultiPixStream_5_U0_start_out;
wire    AXIvideo2MultiPixStream_5_U0_start_write;
wire    AXIvideo2MultiPixStream_5_U0_s_axis_video1_TREADY;
wire   [23:0] AXIvideo2MultiPixStream_5_U0_srcLayer1_din;
wire    AXIvideo2MultiPixStream_5_U0_srcLayer1_write;
wire   [11:0] AXIvideo2MultiPixStream_5_U0_HwReg_layerHeight_1_val;
wire   [11:0] AXIvideo2MultiPixStream_5_U0_HwReg_layerWidth_1_val;
wire    v_mix_420_to_422_false_6_U0_ap_start;
wire    v_mix_420_to_422_false_6_U0_ap_done;
wire    v_mix_420_to_422_false_6_U0_ap_continue;
wire    v_mix_420_to_422_false_6_U0_ap_idle;
wire    v_mix_420_to_422_false_6_U0_ap_ready;
wire    v_mix_420_to_422_false_6_U0_start_out;
wire    v_mix_420_to_422_false_6_U0_start_write;
wire    v_mix_420_to_422_false_6_U0_srcLayer1_read;
wire   [11:0] v_mix_420_to_422_false_6_U0_HwReg_layerHeight_1_val;
wire   [11:0] v_mix_420_to_422_false_6_U0_HwReg_layerWidth_1_val;
wire   [23:0] v_mix_420_to_422_false_6_U0_srcLayer1Yuv422_din;
wire    v_mix_420_to_422_false_6_U0_srcLayer1Yuv422_write;
wire   [31:0] v_mix_420_to_422_false_6_U0_srcLayer1Yuv422_num_data_valid;
wire   [31:0] v_mix_420_to_422_false_6_U0_srcLayer1Yuv422_fifo_cap;
wire    v_mix_422_to_444_true_U0_ap_start;
wire    v_mix_422_to_444_true_U0_ap_done;
wire    v_mix_422_to_444_true_U0_ap_continue;
wire    v_mix_422_to_444_true_U0_ap_idle;
wire    v_mix_422_to_444_true_U0_ap_ready;
wire    v_mix_422_to_444_true_U0_start_out;
wire    v_mix_422_to_444_true_U0_start_write;
wire    v_mix_422_to_444_true_U0_srcLayer1Yuv422_read;
wire   [23:0] v_mix_422_to_444_true_U0_srcLayer1Yuv_din;
wire    v_mix_422_to_444_true_U0_srcLayer1Yuv_write;
wire   [31:0] v_mix_422_to_444_true_U0_srcLayer1Yuv_num_data_valid;
wire   [31:0] v_mix_422_to_444_true_U0_srcLayer1Yuv_fifo_cap;
wire    v_mix_yuv2rgb_true_U0_ap_start;
wire    v_mix_yuv2rgb_true_U0_ap_done;
wire    v_mix_yuv2rgb_true_U0_ap_continue;
wire    v_mix_yuv2rgb_true_U0_ap_idle;
wire    v_mix_yuv2rgb_true_U0_ap_ready;
wire    v_mix_yuv2rgb_true_U0_start_out;
wire    v_mix_yuv2rgb_true_U0_start_write;
wire    v_mix_yuv2rgb_true_U0_srcLayer1Yuv_read;
wire   [11:0] v_mix_yuv2rgb_true_U0_HwReg_layerHeight_1_val;
wire   [11:0] v_mix_yuv2rgb_true_U0_HwReg_layerWidth_1_val;
wire   [23:0] v_mix_yuv2rgb_true_U0_srcLayer1Rgb_din;
wire    v_mix_yuv2rgb_true_U0_srcLayer1Rgb_write;
wire   [31:0] v_mix_yuv2rgb_true_U0_srcLayer1Rgb_num_data_valid;
wire   [31:0] v_mix_yuv2rgb_true_U0_srcLayer1Rgb_fifo_cap;
wire    v_mix_upsample_false_7_U0_ap_start;
wire    v_mix_upsample_false_7_U0_ap_done;
wire    v_mix_upsample_false_7_U0_ap_continue;
wire    v_mix_upsample_false_7_U0_ap_idle;
wire    v_mix_upsample_false_7_U0_ap_ready;
wire    v_mix_upsample_false_7_U0_srcLayer1Rgb_read;
wire   [11:0] v_mix_upsample_false_7_U0_HwReg_layerHeight_1_val;
wire   [11:0] v_mix_upsample_false_7_U0_HwReg_layerWidth_1_val;
wire   [23:0] v_mix_upsample_false_7_U0_srcLayer1x_din;
wire    v_mix_upsample_false_7_U0_srcLayer1x_write;
wire   [31:0] v_mix_upsample_false_7_U0_srcLayer1x_num_data_valid;
wire   [31:0] v_mix_upsample_false_7_U0_srcLayer1x_fifo_cap;
wire    v_mix_core_alpha_false_false_U0_ap_start;
wire    v_mix_core_alpha_false_false_U0_ap_done;
wire    v_mix_core_alpha_false_false_U0_ap_continue;
wire    v_mix_core_alpha_false_false_U0_ap_idle;
wire    v_mix_core_alpha_false_false_U0_ap_ready;
wire    v_mix_core_alpha_false_false_U0_start_out;
wire    v_mix_core_alpha_false_false_U0_start_write;
wire    v_mix_core_alpha_false_false_U0_outLayer0_read;
wire    v_mix_core_alpha_false_false_U0_srcLayer1x_read;
wire   [1:0] v_mix_core_alpha_false_false_U0_HwReg_layerEnable_val16;
wire   [23:0] v_mix_core_alpha_false_false_U0_outLayer1_din;
wire    v_mix_core_alpha_false_false_U0_outLayer1_write;
wire   [31:0] v_mix_core_alpha_false_false_U0_outLayer1_num_data_valid;
wire   [31:0] v_mix_core_alpha_false_false_U0_outLayer1_fifo_cap;
wire    AXIvideo2MultiPixStream_U0_ap_start;
wire    AXIvideo2MultiPixStream_U0_ap_done;
wire    AXIvideo2MultiPixStream_U0_ap_continue;
wire    AXIvideo2MultiPixStream_U0_ap_idle;
wire    AXIvideo2MultiPixStream_U0_ap_ready;
wire    AXIvideo2MultiPixStream_U0_start_out;
wire    AXIvideo2MultiPixStream_U0_start_write;
wire    AXIvideo2MultiPixStream_U0_s_axis_video2_TREADY;
wire   [23:0] AXIvideo2MultiPixStream_U0_srcLayer2_din;
wire    AXIvideo2MultiPixStream_U0_srcLayer2_write;
wire   [11:0] AXIvideo2MultiPixStream_U0_HwReg_layerHeight_2_val;
wire   [11:0] AXIvideo2MultiPixStream_U0_HwReg_layerWidth_2_val;
wire    v_mix_420_to_422_false_U0_ap_start;
wire    v_mix_420_to_422_false_U0_ap_done;
wire    v_mix_420_to_422_false_U0_ap_continue;
wire    v_mix_420_to_422_false_U0_ap_idle;
wire    v_mix_420_to_422_false_U0_ap_ready;
wire    v_mix_420_to_422_false_U0_start_out;
wire    v_mix_420_to_422_false_U0_start_write;
wire    v_mix_420_to_422_false_U0_srcLayer2_read;
wire   [11:0] v_mix_420_to_422_false_U0_HwReg_layerHeight_2_val;
wire   [11:0] v_mix_420_to_422_false_U0_HwReg_layerWidth_2_val;
wire   [23:0] v_mix_420_to_422_false_U0_srcLayer2Yuv422_din;
wire    v_mix_420_to_422_false_U0_srcLayer2Yuv422_write;
wire   [31:0] v_mix_420_to_422_false_U0_srcLayer2Yuv422_num_data_valid;
wire   [31:0] v_mix_420_to_422_false_U0_srcLayer2Yuv422_fifo_cap;
wire    v_mix_422_to_444_false_U0_ap_start;
wire    v_mix_422_to_444_false_U0_ap_done;
wire    v_mix_422_to_444_false_U0_ap_continue;
wire    v_mix_422_to_444_false_U0_ap_idle;
wire    v_mix_422_to_444_false_U0_ap_ready;
wire    v_mix_422_to_444_false_U0_start_out;
wire    v_mix_422_to_444_false_U0_start_write;
wire    v_mix_422_to_444_false_U0_srcLayer2Yuv422_read;
wire   [11:0] v_mix_422_to_444_false_U0_HwReg_layerHeight_2_val;
wire   [11:0] v_mix_422_to_444_false_U0_HwReg_layerWidth_2_val;
wire   [23:0] v_mix_422_to_444_false_U0_srcLayer2Yuv_din;
wire    v_mix_422_to_444_false_U0_srcLayer2Yuv_write;
wire   [31:0] v_mix_422_to_444_false_U0_srcLayer2Yuv_num_data_valid;
wire   [31:0] v_mix_422_to_444_false_U0_srcLayer2Yuv_fifo_cap;
wire    v_mix_yuv2rgb_false_U0_ap_start;
wire    v_mix_yuv2rgb_false_U0_ap_done;
wire    v_mix_yuv2rgb_false_U0_ap_continue;
wire    v_mix_yuv2rgb_false_U0_ap_idle;
wire    v_mix_yuv2rgb_false_U0_ap_ready;
wire    v_mix_yuv2rgb_false_U0_start_out;
wire    v_mix_yuv2rgb_false_U0_start_write;
wire    v_mix_yuv2rgb_false_U0_srcLayer2Yuv_read;
wire   [11:0] v_mix_yuv2rgb_false_U0_HwReg_layerHeight_2_val;
wire   [11:0] v_mix_yuv2rgb_false_U0_HwReg_layerWidth_2_val;
wire   [23:0] v_mix_yuv2rgb_false_U0_srcLayer2Rgb_din;
wire    v_mix_yuv2rgb_false_U0_srcLayer2Rgb_write;
wire   [31:0] v_mix_yuv2rgb_false_U0_srcLayer2Rgb_num_data_valid;
wire   [31:0] v_mix_yuv2rgb_false_U0_srcLayer2Rgb_fifo_cap;
wire    v_mix_upsample_false_U0_ap_start;
wire    v_mix_upsample_false_U0_ap_done;
wire    v_mix_upsample_false_U0_ap_continue;
wire    v_mix_upsample_false_U0_ap_idle;
wire    v_mix_upsample_false_U0_ap_ready;
wire    v_mix_upsample_false_U0_srcLayer2Rgb_read;
wire   [11:0] v_mix_upsample_false_U0_HwReg_layerHeight_2_val;
wire   [11:0] v_mix_upsample_false_U0_HwReg_layerWidth_2_val;
wire   [23:0] v_mix_upsample_false_U0_srcLayer2x_din;
wire    v_mix_upsample_false_U0_srcLayer2x_write;
wire   [31:0] v_mix_upsample_false_U0_srcLayer2x_num_data_valid;
wire   [31:0] v_mix_upsample_false_U0_srcLayer2x_fifo_cap;
wire    v_mix_core_alpha_true_false_U0_ap_start;
wire    v_mix_core_alpha_true_false_U0_ap_done;
wire    v_mix_core_alpha_true_false_U0_ap_continue;
wire    v_mix_core_alpha_true_false_U0_ap_idle;
wire    v_mix_core_alpha_true_false_U0_ap_ready;
wire    v_mix_core_alpha_true_false_U0_start_out;
wire    v_mix_core_alpha_true_false_U0_start_write;
wire    v_mix_core_alpha_true_false_U0_outLayer1_read;
wire    v_mix_core_alpha_true_false_U0_srcLayer2x_read;
wire   [23:0] v_mix_core_alpha_true_false_U0_outLayer2_din;
wire    v_mix_core_alpha_true_false_U0_outLayer2_write;
wire   [31:0] v_mix_core_alpha_true_false_U0_outLayer2_num_data_valid;
wire   [31:0] v_mix_core_alpha_true_false_U0_outLayer2_fifo_cap;
wire    v_mix_rgb2yuv_false_U0_ap_start;
wire    v_mix_rgb2yuv_false_U0_ap_done;
wire    v_mix_rgb2yuv_false_U0_ap_continue;
wire    v_mix_rgb2yuv_false_U0_ap_idle;
wire    v_mix_rgb2yuv_false_U0_ap_ready;
wire    v_mix_rgb2yuv_false_U0_start_out;
wire    v_mix_rgb2yuv_false_U0_start_write;
wire    v_mix_rgb2yuv_false_U0_outLayer2_read;
wire   [23:0] v_mix_rgb2yuv_false_U0_outYuv_din;
wire    v_mix_rgb2yuv_false_U0_outYuv_write;
wire   [31:0] v_mix_rgb2yuv_false_U0_outYuv_num_data_valid;
wire   [31:0] v_mix_rgb2yuv_false_U0_outYuv_fifo_cap;
wire    v_mix_444_to_422_false_U0_ap_start;
wire    v_mix_444_to_422_false_U0_ap_done;
wire    v_mix_444_to_422_false_U0_ap_continue;
wire    v_mix_444_to_422_false_U0_ap_idle;
wire    v_mix_444_to_422_false_U0_ap_ready;
wire    v_mix_444_to_422_false_U0_start_out;
wire    v_mix_444_to_422_false_U0_start_write;
wire    v_mix_444_to_422_false_U0_outYuv_read;
wire   [23:0] v_mix_444_to_422_false_U0_out422_din;
wire    v_mix_444_to_422_false_U0_out422_write;
wire   [31:0] v_mix_444_to_422_false_U0_out422_num_data_valid;
wire   [31:0] v_mix_444_to_422_false_U0_out422_fifo_cap;
wire    v_mix_422_to_420_false_U0_ap_start;
wire    v_mix_422_to_420_false_U0_ap_done;
wire    v_mix_422_to_420_false_U0_ap_continue;
wire    v_mix_422_to_420_false_U0_ap_idle;
wire    v_mix_422_to_420_false_U0_ap_ready;
wire    v_mix_422_to_420_false_U0_start_out;
wire    v_mix_422_to_420_false_U0_start_write;
wire    v_mix_422_to_420_false_U0_out422_read;
wire   [23:0] v_mix_422_to_420_false_U0_out420_din;
wire    v_mix_422_to_420_false_U0_out420_write;
wire   [31:0] v_mix_422_to_420_false_U0_out420_num_data_valid;
wire   [31:0] v_mix_422_to_420_false_U0_out420_fifo_cap;
wire    MultiPixStream2AXIvideo_U0_ap_start;
wire    MultiPixStream2AXIvideo_U0_ap_done;
wire    MultiPixStream2AXIvideo_U0_ap_continue;
wire    MultiPixStream2AXIvideo_U0_ap_idle;
wire    MultiPixStream2AXIvideo_U0_ap_ready;
wire    MultiPixStream2AXIvideo_U0_out420_read;
wire   [23:0] MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;
wire    MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;
wire   [2:0] MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;
wire   [2:0] MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TID;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;
wire    srcLayer0_full_n;
wire   [23:0] srcLayer0_dout;
wire    srcLayer0_empty_n;
wire   [2:0] srcLayer0_num_data_valid;
wire   [2:0] srcLayer0_fifo_cap;
wire    srcLayer0Yuv422_full_n;
wire   [23:0] srcLayer0Yuv422_dout;
wire    srcLayer0Yuv422_empty_n;
wire   [2:0] srcLayer0Yuv422_num_data_valid;
wire   [2:0] srcLayer0Yuv422_fifo_cap;
wire    srcLayer0Yuv_full_n;
wire   [23:0] srcLayer0Yuv_dout;
wire    srcLayer0Yuv_empty_n;
wire   [2:0] srcLayer0Yuv_num_data_valid;
wire   [2:0] srcLayer0Yuv_fifo_cap;
wire    outLayer0_full_n;
wire   [23:0] outLayer0_dout;
wire    outLayer0_empty_n;
wire   [2:0] outLayer0_num_data_valid;
wire   [2:0] outLayer0_fifo_cap;
wire    srcLayer1_full_n;
wire   [23:0] srcLayer1_dout;
wire    srcLayer1_empty_n;
wire   [2:0] srcLayer1_num_data_valid;
wire   [2:0] srcLayer1_fifo_cap;
wire    srcLayer1Yuv422_full_n;
wire   [23:0] srcLayer1Yuv422_dout;
wire    srcLayer1Yuv422_empty_n;
wire   [2:0] srcLayer1Yuv422_num_data_valid;
wire   [2:0] srcLayer1Yuv422_fifo_cap;
wire    srcLayer1Yuv_full_n;
wire   [23:0] srcLayer1Yuv_dout;
wire    srcLayer1Yuv_empty_n;
wire   [2:0] srcLayer1Yuv_num_data_valid;
wire   [2:0] srcLayer1Yuv_fifo_cap;
wire    srcLayer1Rgb_full_n;
wire   [23:0] srcLayer1Rgb_dout;
wire    srcLayer1Rgb_empty_n;
wire   [2:0] srcLayer1Rgb_num_data_valid;
wire   [2:0] srcLayer1Rgb_fifo_cap;
wire    srcLayer1x_full_n;
wire   [23:0] srcLayer1x_dout;
wire    srcLayer1x_empty_n;
wire   [2:0] srcLayer1x_num_data_valid;
wire   [2:0] srcLayer1x_fifo_cap;
wire    outLayer1_full_n;
wire   [23:0] outLayer1_dout;
wire    outLayer1_empty_n;
wire   [2:0] outLayer1_num_data_valid;
wire   [2:0] outLayer1_fifo_cap;
wire    srcLayer2_full_n;
wire   [23:0] srcLayer2_dout;
wire    srcLayer2_empty_n;
wire   [2:0] srcLayer2_num_data_valid;
wire   [2:0] srcLayer2_fifo_cap;
wire    srcLayer2Yuv422_full_n;
wire   [23:0] srcLayer2Yuv422_dout;
wire    srcLayer2Yuv422_empty_n;
wire   [2:0] srcLayer2Yuv422_num_data_valid;
wire   [2:0] srcLayer2Yuv422_fifo_cap;
wire    srcLayer2Yuv_full_n;
wire   [23:0] srcLayer2Yuv_dout;
wire    srcLayer2Yuv_empty_n;
wire   [2:0] srcLayer2Yuv_num_data_valid;
wire   [2:0] srcLayer2Yuv_fifo_cap;
wire    srcLayer2Rgb_full_n;
wire   [23:0] srcLayer2Rgb_dout;
wire    srcLayer2Rgb_empty_n;
wire   [2:0] srcLayer2Rgb_num_data_valid;
wire   [2:0] srcLayer2Rgb_fifo_cap;
wire    srcLayer2x_full_n;
wire   [23:0] srcLayer2x_dout;
wire    srcLayer2x_empty_n;
wire   [2:0] srcLayer2x_num_data_valid;
wire   [2:0] srcLayer2x_fifo_cap;
wire    outLayer2_full_n;
wire   [23:0] outLayer2_dout;
wire    outLayer2_empty_n;
wire   [2:0] outLayer2_num_data_valid;
wire   [2:0] outLayer2_fifo_cap;
wire    outYuv_full_n;
wire   [23:0] outYuv_dout;
wire    outYuv_empty_n;
wire   [2:0] outYuv_num_data_valid;
wire   [2:0] outYuv_fifo_cap;
wire    out422_full_n;
wire   [23:0] out422_dout;
wire    out422_empty_n;
wire   [2:0] out422_num_data_valid;
wire   [2:0] out422_fifo_cap;
wire    out420_full_n;
wire   [23:0] out420_dout;
wire    out420_empty_n;
wire   [2:0] out420_num_data_valid;
wire   [2:0] out420_fifo_cap;
reg    ap_sync_ready;
reg    ap_sync_reg_AXIvideo2MultiPixStream_1_U0_ap_ready;
wire    ap_sync_AXIvideo2MultiPixStream_1_U0_ap_ready;
reg    ap_sync_reg_AXIvideo2MultiPixStream_5_U0_ap_ready;
wire    ap_sync_AXIvideo2MultiPixStream_5_U0_ap_ready;
reg    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready;
wire    ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
wire   [0:0] start_for_v_mix_420_to_422_false_2_U0_din;
wire    start_for_v_mix_420_to_422_false_2_U0_full_n;
wire   [0:0] start_for_v_mix_420_to_422_false_2_U0_dout;
wire    start_for_v_mix_420_to_422_false_2_U0_empty_n;
wire   [0:0] start_for_v_mix_422_to_444_false_3_U0_din;
wire    start_for_v_mix_422_to_444_false_3_U0_full_n;
wire   [0:0] start_for_v_mix_422_to_444_false_3_U0_dout;
wire    start_for_v_mix_422_to_444_false_3_U0_empty_n;
wire   [0:0] start_for_v_mix_yuv2rgb_false_4_U0_din;
wire    start_for_v_mix_yuv2rgb_false_4_U0_full_n;
wire   [0:0] start_for_v_mix_yuv2rgb_false_4_U0_dout;
wire    start_for_v_mix_yuv2rgb_false_4_U0_empty_n;
wire   [0:0] start_for_v_mix_core_alpha_false_false_U0_din;
wire    start_for_v_mix_core_alpha_false_false_U0_full_n;
wire   [0:0] start_for_v_mix_core_alpha_false_false_U0_dout;
wire    start_for_v_mix_core_alpha_false_false_U0_empty_n;
wire   [0:0] start_for_v_mix_420_to_422_false_6_U0_din;
wire    start_for_v_mix_420_to_422_false_6_U0_full_n;
wire   [0:0] start_for_v_mix_420_to_422_false_6_U0_dout;
wire    start_for_v_mix_420_to_422_false_6_U0_empty_n;
wire   [0:0] start_for_v_mix_422_to_444_true_U0_din;
wire    start_for_v_mix_422_to_444_true_U0_full_n;
wire   [0:0] start_for_v_mix_422_to_444_true_U0_dout;
wire    start_for_v_mix_422_to_444_true_U0_empty_n;
wire   [0:0] start_for_v_mix_yuv2rgb_true_U0_din;
wire    start_for_v_mix_yuv2rgb_true_U0_full_n;
wire   [0:0] start_for_v_mix_yuv2rgb_true_U0_dout;
wire    start_for_v_mix_yuv2rgb_true_U0_empty_n;
wire   [0:0] start_for_v_mix_upsample_false_7_U0_din;
wire    start_for_v_mix_upsample_false_7_U0_full_n;
wire   [0:0] start_for_v_mix_upsample_false_7_U0_dout;
wire    start_for_v_mix_upsample_false_7_U0_empty_n;
wire   [0:0] start_for_v_mix_core_alpha_true_false_U0_din;
wire    start_for_v_mix_core_alpha_true_false_U0_full_n;
wire   [0:0] start_for_v_mix_core_alpha_true_false_U0_dout;
wire    start_for_v_mix_core_alpha_true_false_U0_empty_n;
wire   [0:0] start_for_v_mix_420_to_422_false_U0_din;
wire    start_for_v_mix_420_to_422_false_U0_full_n;
wire   [0:0] start_for_v_mix_420_to_422_false_U0_dout;
wire    start_for_v_mix_420_to_422_false_U0_empty_n;
wire   [0:0] start_for_v_mix_422_to_444_false_U0_din;
wire    start_for_v_mix_422_to_444_false_U0_full_n;
wire   [0:0] start_for_v_mix_422_to_444_false_U0_dout;
wire    start_for_v_mix_422_to_444_false_U0_empty_n;
wire   [0:0] start_for_v_mix_yuv2rgb_false_U0_din;
wire    start_for_v_mix_yuv2rgb_false_U0_full_n;
wire   [0:0] start_for_v_mix_yuv2rgb_false_U0_dout;
wire    start_for_v_mix_yuv2rgb_false_U0_empty_n;
wire   [0:0] start_for_v_mix_upsample_false_U0_din;
wire    start_for_v_mix_upsample_false_U0_full_n;
wire   [0:0] start_for_v_mix_upsample_false_U0_dout;
wire    start_for_v_mix_upsample_false_U0_empty_n;
wire   [0:0] start_for_v_mix_rgb2yuv_false_U0_din;
wire    start_for_v_mix_rgb2yuv_false_U0_full_n;
wire   [0:0] start_for_v_mix_rgb2yuv_false_U0_dout;
wire    start_for_v_mix_rgb2yuv_false_U0_empty_n;
wire   [0:0] start_for_v_mix_444_to_422_false_U0_din;
wire    start_for_v_mix_444_to_422_false_U0_full_n;
wire   [0:0] start_for_v_mix_444_to_422_false_U0_dout;
wire    start_for_v_mix_444_to_422_false_U0_empty_n;
wire   [0:0] start_for_v_mix_422_to_420_false_U0_din;
wire    start_for_v_mix_422_to_420_false_U0_full_n;
wire   [0:0] start_for_v_mix_422_to_420_false_U0_dout;
wire    start_for_v_mix_422_to_420_false_U0_empty_n;
wire   [0:0] start_for_MultiPixStream2AXIvideo_U0_din;
wire    start_for_MultiPixStream2AXIvideo_U0_full_n;
wire   [0:0] start_for_MultiPixStream2AXIvideo_U0_dout;
wire    start_for_MultiPixStream2AXIvideo_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_AXIvideo2MultiPixStream_1_U0_ap_ready = 1'b0;
#0 ap_sync_reg_AXIvideo2MultiPixStream_5_U0_ap_ready = 1'b0;
#0 ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready = 1'b0;
end

design_1_v_mix_0_0_AXIvideo2MultiPixStream_1 AXIvideo2MultiPixStream_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(AXIvideo2MultiPixStream_1_U0_ap_start),
    .start_full_n(start_for_v_mix_420_to_422_false_2_U0_full_n),
    .ap_done(AXIvideo2MultiPixStream_1_U0_ap_done),
    .ap_continue(AXIvideo2MultiPixStream_1_U0_ap_continue),
    .ap_idle(AXIvideo2MultiPixStream_1_U0_ap_idle),
    .ap_ready(AXIvideo2MultiPixStream_1_U0_ap_ready),
    .start_out(AXIvideo2MultiPixStream_1_U0_start_out),
    .start_write(AXIvideo2MultiPixStream_1_U0_start_write),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .s_axis_video_TREADY(AXIvideo2MultiPixStream_1_U0_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .srcLayer0_din(AXIvideo2MultiPixStream_1_U0_srcLayer0_din),
    .srcLayer0_full_n(srcLayer0_full_n),
    .srcLayer0_write(AXIvideo2MultiPixStream_1_U0_srcLayer0_write),
    .srcLayer0_num_data_valid(srcLayer0_num_data_valid),
    .srcLayer0_fifo_cap(srcLayer0_fifo_cap),
    .Height(HwReg_height_val),
    .WidthIn(HwReg_width_val),
    .layerEnableFlag(HwReg_layerEnableFlag_0_val)
);

design_1_v_mix_0_0_v_mix_420_to_422_false_2 v_mix_420_to_422_false_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_420_to_422_false_2_U0_ap_start),
    .start_full_n(start_for_v_mix_422_to_444_false_3_U0_full_n),
    .ap_done(v_mix_420_to_422_false_2_U0_ap_done),
    .ap_continue(v_mix_420_to_422_false_2_U0_ap_continue),
    .ap_idle(v_mix_420_to_422_false_2_U0_ap_idle),
    .ap_ready(v_mix_420_to_422_false_2_U0_ap_ready),
    .start_out(v_mix_420_to_422_false_2_U0_start_out),
    .start_write(v_mix_420_to_422_false_2_U0_start_write),
    .srcLayer0_dout(srcLayer0_dout),
    .srcLayer0_empty_n(srcLayer0_empty_n),
    .srcLayer0_read(v_mix_420_to_422_false_2_U0_srcLayer0_read),
    .srcLayer0_num_data_valid(srcLayer0_num_data_valid),
    .srcLayer0_fifo_cap(srcLayer0_fifo_cap),
    .height(HwReg_height_val),
    .width(HwReg_width_val),
    .layerEnableFlag(HwReg_layerEnableFlag_0_val),
    .srcLayer0Yuv422_din(v_mix_420_to_422_false_2_U0_srcLayer0Yuv422_din),
    .srcLayer0Yuv422_full_n(srcLayer0Yuv422_full_n),
    .srcLayer0Yuv422_write(v_mix_420_to_422_false_2_U0_srcLayer0Yuv422_write),
    .srcLayer0Yuv422_num_data_valid(v_mix_420_to_422_false_2_U0_srcLayer0Yuv422_num_data_valid),
    .srcLayer0Yuv422_fifo_cap(v_mix_420_to_422_false_2_U0_srcLayer0Yuv422_fifo_cap)
);

design_1_v_mix_0_0_v_mix_422_to_444_false_3 v_mix_422_to_444_false_3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_422_to_444_false_3_U0_ap_start),
    .start_full_n(start_for_v_mix_yuv2rgb_false_4_U0_full_n),
    .ap_done(v_mix_422_to_444_false_3_U0_ap_done),
    .ap_continue(v_mix_422_to_444_false_3_U0_ap_continue),
    .ap_idle(v_mix_422_to_444_false_3_U0_ap_idle),
    .ap_ready(v_mix_422_to_444_false_3_U0_ap_ready),
    .start_out(v_mix_422_to_444_false_3_U0_start_out),
    .start_write(v_mix_422_to_444_false_3_U0_start_write),
    .srcLayer0Yuv422_dout(srcLayer0Yuv422_dout),
    .srcLayer0Yuv422_empty_n(srcLayer0Yuv422_empty_n),
    .srcLayer0Yuv422_read(v_mix_422_to_444_false_3_U0_srcLayer0Yuv422_read),
    .srcLayer0Yuv422_num_data_valid(srcLayer0Yuv422_num_data_valid),
    .srcLayer0Yuv422_fifo_cap(srcLayer0Yuv422_fifo_cap),
    .height(HwReg_height_val),
    .width(HwReg_width_val),
    .layerEnableFlag(HwReg_layerEnableFlag_0_val),
    .srcLayer0Yuv_din(v_mix_422_to_444_false_3_U0_srcLayer0Yuv_din),
    .srcLayer0Yuv_full_n(srcLayer0Yuv_full_n),
    .srcLayer0Yuv_write(v_mix_422_to_444_false_3_U0_srcLayer0Yuv_write),
    .srcLayer0Yuv_num_data_valid(v_mix_422_to_444_false_3_U0_srcLayer0Yuv_num_data_valid),
    .srcLayer0Yuv_fifo_cap(v_mix_422_to_444_false_3_U0_srcLayer0Yuv_fifo_cap)
);

design_1_v_mix_0_0_v_mix_yuv2rgb_false_4 v_mix_yuv2rgb_false_4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_yuv2rgb_false_4_U0_ap_start),
    .start_full_n(start_for_v_mix_core_alpha_false_false_U0_full_n),
    .ap_done(v_mix_yuv2rgb_false_4_U0_ap_done),
    .ap_continue(v_mix_yuv2rgb_false_4_U0_ap_continue),
    .ap_idle(v_mix_yuv2rgb_false_4_U0_ap_idle),
    .ap_ready(v_mix_yuv2rgb_false_4_U0_ap_ready),
    .start_out(v_mix_yuv2rgb_false_4_U0_start_out),
    .start_write(v_mix_yuv2rgb_false_4_U0_start_write),
    .srcLayer0Yuv_dout(srcLayer0Yuv_dout),
    .srcLayer0Yuv_empty_n(srcLayer0Yuv_empty_n),
    .srcLayer0Yuv_read(v_mix_yuv2rgb_false_4_U0_srcLayer0Yuv_read),
    .srcLayer0Yuv_num_data_valid(srcLayer0Yuv_num_data_valid),
    .srcLayer0Yuv_fifo_cap(srcLayer0Yuv_fifo_cap),
    .height(HwReg_height_val),
    .width(HwReg_width_val),
    .layerEnableFlag(HwReg_layerEnableFlag_0_val),
    .outLayer0_din(v_mix_yuv2rgb_false_4_U0_outLayer0_din),
    .outLayer0_full_n(outLayer0_full_n),
    .outLayer0_write(v_mix_yuv2rgb_false_4_U0_outLayer0_write),
    .outLayer0_num_data_valid(v_mix_yuv2rgb_false_4_U0_outLayer0_num_data_valid),
    .outLayer0_fifo_cap(v_mix_yuv2rgb_false_4_U0_outLayer0_fifo_cap)
);

design_1_v_mix_0_0_AXIvideo2MultiPixStream_5 AXIvideo2MultiPixStream_5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(AXIvideo2MultiPixStream_5_U0_ap_start),
    .start_full_n(start_for_v_mix_420_to_422_false_6_U0_full_n),
    .ap_done(AXIvideo2MultiPixStream_5_U0_ap_done),
    .ap_continue(AXIvideo2MultiPixStream_5_U0_ap_continue),
    .ap_idle(AXIvideo2MultiPixStream_5_U0_ap_idle),
    .ap_ready(AXIvideo2MultiPixStream_5_U0_ap_ready),
    .start_out(AXIvideo2MultiPixStream_5_U0_start_out),
    .start_write(AXIvideo2MultiPixStream_5_U0_start_write),
    .s_axis_video1_TDATA(s_axis_video1_TDATA),
    .s_axis_video1_TVALID(s_axis_video1_TVALID),
    .s_axis_video1_TREADY(AXIvideo2MultiPixStream_5_U0_s_axis_video1_TREADY),
    .s_axis_video1_TKEEP(s_axis_video1_TKEEP),
    .s_axis_video1_TSTRB(s_axis_video1_TSTRB),
    .s_axis_video1_TUSER(s_axis_video1_TUSER),
    .s_axis_video1_TLAST(s_axis_video1_TLAST),
    .s_axis_video1_TID(s_axis_video1_TID),
    .s_axis_video1_TDEST(s_axis_video1_TDEST),
    .srcLayer1_din(AXIvideo2MultiPixStream_5_U0_srcLayer1_din),
    .srcLayer1_full_n(srcLayer1_full_n),
    .srcLayer1_write(AXIvideo2MultiPixStream_5_U0_srcLayer1_write),
    .srcLayer1_num_data_valid(srcLayer1_num_data_valid),
    .srcLayer1_fifo_cap(srcLayer1_fifo_cap),
    .HwReg_layerHeight_1_val(AXIvideo2MultiPixStream_5_U0_HwReg_layerHeight_1_val),
    .HwReg_layerWidth_1_val(AXIvideo2MultiPixStream_5_U0_HwReg_layerWidth_1_val),
    .HwReg_layerEnableFlag_1_val(HwReg_layerEnableFlag_1_val)
);

design_1_v_mix_0_0_v_mix_420_to_422_false_6 v_mix_420_to_422_false_6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_420_to_422_false_6_U0_ap_start),
    .start_full_n(start_for_v_mix_422_to_444_true_U0_full_n),
    .ap_done(v_mix_420_to_422_false_6_U0_ap_done),
    .ap_continue(v_mix_420_to_422_false_6_U0_ap_continue),
    .ap_idle(v_mix_420_to_422_false_6_U0_ap_idle),
    .ap_ready(v_mix_420_to_422_false_6_U0_ap_ready),
    .start_out(v_mix_420_to_422_false_6_U0_start_out),
    .start_write(v_mix_420_to_422_false_6_U0_start_write),
    .srcLayer1_dout(srcLayer1_dout),
    .srcLayer1_empty_n(srcLayer1_empty_n),
    .srcLayer1_read(v_mix_420_to_422_false_6_U0_srcLayer1_read),
    .srcLayer1_num_data_valid(srcLayer1_num_data_valid),
    .srcLayer1_fifo_cap(srcLayer1_fifo_cap),
    .HwReg_layerHeight_1_val(v_mix_420_to_422_false_6_U0_HwReg_layerHeight_1_val),
    .HwReg_layerWidth_1_val(v_mix_420_to_422_false_6_U0_HwReg_layerWidth_1_val),
    .HwReg_layerEnableFlag_1_val(HwReg_layerEnableFlag_1_val),
    .srcLayer1Yuv422_din(v_mix_420_to_422_false_6_U0_srcLayer1Yuv422_din),
    .srcLayer1Yuv422_full_n(srcLayer1Yuv422_full_n),
    .srcLayer1Yuv422_write(v_mix_420_to_422_false_6_U0_srcLayer1Yuv422_write),
    .srcLayer1Yuv422_num_data_valid(v_mix_420_to_422_false_6_U0_srcLayer1Yuv422_num_data_valid),
    .srcLayer1Yuv422_fifo_cap(v_mix_420_to_422_false_6_U0_srcLayer1Yuv422_fifo_cap)
);

design_1_v_mix_0_0_v_mix_422_to_444_true_s v_mix_422_to_444_true_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_422_to_444_true_U0_ap_start),
    .start_full_n(start_for_v_mix_yuv2rgb_true_U0_full_n),
    .ap_done(v_mix_422_to_444_true_U0_ap_done),
    .ap_continue(v_mix_422_to_444_true_U0_ap_continue),
    .ap_idle(v_mix_422_to_444_true_U0_ap_idle),
    .ap_ready(v_mix_422_to_444_true_U0_ap_ready),
    .start_out(v_mix_422_to_444_true_U0_start_out),
    .start_write(v_mix_422_to_444_true_U0_start_write),
    .srcLayer1Yuv422_dout(srcLayer1Yuv422_dout),
    .srcLayer1Yuv422_empty_n(srcLayer1Yuv422_empty_n),
    .srcLayer1Yuv422_read(v_mix_422_to_444_true_U0_srcLayer1Yuv422_read),
    .srcLayer1Yuv422_num_data_valid(srcLayer1Yuv422_num_data_valid),
    .srcLayer1Yuv422_fifo_cap(srcLayer1Yuv422_fifo_cap),
    .height(HwReg_layerHeight_1_val),
    .width(HwReg_layerWidth_1_val),
    .layerEnableFlag(HwReg_layerEnableFlag_1_val),
    .srcLayer1Yuv_din(v_mix_422_to_444_true_U0_srcLayer1Yuv_din),
    .srcLayer1Yuv_full_n(srcLayer1Yuv_full_n),
    .srcLayer1Yuv_write(v_mix_422_to_444_true_U0_srcLayer1Yuv_write),
    .srcLayer1Yuv_num_data_valid(v_mix_422_to_444_true_U0_srcLayer1Yuv_num_data_valid),
    .srcLayer1Yuv_fifo_cap(v_mix_422_to_444_true_U0_srcLayer1Yuv_fifo_cap)
);

design_1_v_mix_0_0_v_mix_yuv2rgb_true_s v_mix_yuv2rgb_true_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_yuv2rgb_true_U0_ap_start),
    .start_full_n(start_for_v_mix_upsample_false_7_U0_full_n),
    .ap_done(v_mix_yuv2rgb_true_U0_ap_done),
    .ap_continue(v_mix_yuv2rgb_true_U0_ap_continue),
    .ap_idle(v_mix_yuv2rgb_true_U0_ap_idle),
    .ap_ready(v_mix_yuv2rgb_true_U0_ap_ready),
    .start_out(v_mix_yuv2rgb_true_U0_start_out),
    .start_write(v_mix_yuv2rgb_true_U0_start_write),
    .srcLayer1Yuv_dout(srcLayer1Yuv_dout),
    .srcLayer1Yuv_empty_n(srcLayer1Yuv_empty_n),
    .srcLayer1Yuv_read(v_mix_yuv2rgb_true_U0_srcLayer1Yuv_read),
    .srcLayer1Yuv_num_data_valid(srcLayer1Yuv_num_data_valid),
    .srcLayer1Yuv_fifo_cap(srcLayer1Yuv_fifo_cap),
    .HwReg_layerHeight_1_val(v_mix_yuv2rgb_true_U0_HwReg_layerHeight_1_val),
    .HwReg_layerWidth_1_val(v_mix_yuv2rgb_true_U0_HwReg_layerWidth_1_val),
    .HwReg_layerEnableFlag_1_val(HwReg_layerEnableFlag_1_val),
    .srcLayer1Rgb_din(v_mix_yuv2rgb_true_U0_srcLayer1Rgb_din),
    .srcLayer1Rgb_full_n(srcLayer1Rgb_full_n),
    .srcLayer1Rgb_write(v_mix_yuv2rgb_true_U0_srcLayer1Rgb_write),
    .srcLayer1Rgb_num_data_valid(v_mix_yuv2rgb_true_U0_srcLayer1Rgb_num_data_valid),
    .srcLayer1Rgb_fifo_cap(v_mix_yuv2rgb_true_U0_srcLayer1Rgb_fifo_cap)
);

design_1_v_mix_0_0_v_mix_upsample_false_7 v_mix_upsample_false_7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_upsample_false_7_U0_ap_start),
    .ap_done(v_mix_upsample_false_7_U0_ap_done),
    .ap_continue(v_mix_upsample_false_7_U0_ap_continue),
    .ap_idle(v_mix_upsample_false_7_U0_ap_idle),
    .ap_ready(v_mix_upsample_false_7_U0_ap_ready),
    .srcLayer1Rgb_dout(srcLayer1Rgb_dout),
    .srcLayer1Rgb_empty_n(srcLayer1Rgb_empty_n),
    .srcLayer1Rgb_read(v_mix_upsample_false_7_U0_srcLayer1Rgb_read),
    .srcLayer1Rgb_num_data_valid(srcLayer1Rgb_num_data_valid),
    .srcLayer1Rgb_fifo_cap(srcLayer1Rgb_fifo_cap),
    .HwReg_layerHeight_1_val(v_mix_upsample_false_7_U0_HwReg_layerHeight_1_val),
    .HwReg_layerWidth_1_val(v_mix_upsample_false_7_U0_HwReg_layerWidth_1_val),
    .HwReg_layerEnableFlag_1_val(HwReg_layerEnableFlag_1_val),
    .srcLayer1x_din(v_mix_upsample_false_7_U0_srcLayer1x_din),
    .srcLayer1x_full_n(srcLayer1x_full_n),
    .srcLayer1x_write(v_mix_upsample_false_7_U0_srcLayer1x_write),
    .srcLayer1x_num_data_valid(v_mix_upsample_false_7_U0_srcLayer1x_num_data_valid),
    .srcLayer1x_fifo_cap(v_mix_upsample_false_7_U0_srcLayer1x_fifo_cap)
);

design_1_v_mix_0_0_v_mix_core_alpha_false_false_s v_mix_core_alpha_false_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_core_alpha_false_false_U0_ap_start),
    .start_full_n(start_for_v_mix_core_alpha_true_false_U0_full_n),
    .ap_done(v_mix_core_alpha_false_false_U0_ap_done),
    .ap_continue(v_mix_core_alpha_false_false_U0_ap_continue),
    .ap_idle(v_mix_core_alpha_false_false_U0_ap_idle),
    .ap_ready(v_mix_core_alpha_false_false_U0_ap_ready),
    .start_out(v_mix_core_alpha_false_false_U0_start_out),
    .start_write(v_mix_core_alpha_false_false_U0_start_write),
    .outLayer0_dout(outLayer0_dout),
    .outLayer0_empty_n(outLayer0_empty_n),
    .outLayer0_read(v_mix_core_alpha_false_false_U0_outLayer0_read),
    .outLayer0_num_data_valid(outLayer0_num_data_valid),
    .outLayer0_fifo_cap(outLayer0_fifo_cap),
    .srcLayer1x_dout(srcLayer1x_dout),
    .srcLayer1x_empty_n(srcLayer1x_empty_n),
    .srcLayer1x_read(v_mix_core_alpha_false_false_U0_srcLayer1x_read),
    .srcLayer1x_num_data_valid(srcLayer1x_num_data_valid),
    .srcLayer1x_fifo_cap(srcLayer1x_fifo_cap),
    .HwReg_width_val(HwReg_width_val),
    .HwReg_height_val(HwReg_height_val),
    .HwReg_background_Y_R_val12(HwReg_background_Y_R_val12),
    .HwReg_background_U_G_val13(HwReg_background_U_G_val13),
    .HwReg_background_V_B_val14(HwReg_background_V_B_val14),
    .HwReg_layerEnable_val16(v_mix_core_alpha_false_false_U0_HwReg_layerEnable_val16),
    .HwReg_layerStartX_1_val18(HwReg_layerStartX_1_val18),
    .HwReg_layerStartY_1_val20(HwReg_layerStartY_1_val20),
    .HwReg_layerWidth_1_val(HwReg_layerWidth_1_val),
    .HwReg_layerHeight_1_val(HwReg_layerHeight_1_val),
    .HwReg_layerScaleFactor_1_val26(HwReg_layerScaleFactor_1_val26),
    .outLayer1_din(v_mix_core_alpha_false_false_U0_outLayer1_din),
    .outLayer1_full_n(outLayer1_full_n),
    .outLayer1_write(v_mix_core_alpha_false_false_U0_outLayer1_write),
    .outLayer1_num_data_valid(v_mix_core_alpha_false_false_U0_outLayer1_num_data_valid),
    .outLayer1_fifo_cap(v_mix_core_alpha_false_false_U0_outLayer1_fifo_cap)
);

design_1_v_mix_0_0_AXIvideo2MultiPixStream AXIvideo2MultiPixStream_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(AXIvideo2MultiPixStream_U0_ap_start),
    .start_full_n(start_for_v_mix_420_to_422_false_U0_full_n),
    .ap_done(AXIvideo2MultiPixStream_U0_ap_done),
    .ap_continue(AXIvideo2MultiPixStream_U0_ap_continue),
    .ap_idle(AXIvideo2MultiPixStream_U0_ap_idle),
    .ap_ready(AXIvideo2MultiPixStream_U0_ap_ready),
    .start_out(AXIvideo2MultiPixStream_U0_start_out),
    .start_write(AXIvideo2MultiPixStream_U0_start_write),
    .s_axis_video2_TDATA(s_axis_video2_TDATA),
    .s_axis_video2_TVALID(s_axis_video2_TVALID),
    .s_axis_video2_TREADY(AXIvideo2MultiPixStream_U0_s_axis_video2_TREADY),
    .s_axis_video2_TKEEP(s_axis_video2_TKEEP),
    .s_axis_video2_TSTRB(s_axis_video2_TSTRB),
    .s_axis_video2_TUSER(s_axis_video2_TUSER),
    .s_axis_video2_TLAST(s_axis_video2_TLAST),
    .s_axis_video2_TID(s_axis_video2_TID),
    .s_axis_video2_TDEST(s_axis_video2_TDEST),
    .srcLayer2_din(AXIvideo2MultiPixStream_U0_srcLayer2_din),
    .srcLayer2_full_n(srcLayer2_full_n),
    .srcLayer2_write(AXIvideo2MultiPixStream_U0_srcLayer2_write),
    .srcLayer2_num_data_valid(srcLayer2_num_data_valid),
    .srcLayer2_fifo_cap(srcLayer2_fifo_cap),
    .HwReg_layerHeight_2_val(AXIvideo2MultiPixStream_U0_HwReg_layerHeight_2_val),
    .HwReg_layerWidth_2_val(AXIvideo2MultiPixStream_U0_HwReg_layerWidth_2_val),
    .HwReg_layerEnableFlag_2_val(HwReg_layerEnableFlag_2_val)
);

design_1_v_mix_0_0_v_mix_420_to_422_false_s v_mix_420_to_422_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_420_to_422_false_U0_ap_start),
    .start_full_n(start_for_v_mix_422_to_444_false_U0_full_n),
    .ap_done(v_mix_420_to_422_false_U0_ap_done),
    .ap_continue(v_mix_420_to_422_false_U0_ap_continue),
    .ap_idle(v_mix_420_to_422_false_U0_ap_idle),
    .ap_ready(v_mix_420_to_422_false_U0_ap_ready),
    .start_out(v_mix_420_to_422_false_U0_start_out),
    .start_write(v_mix_420_to_422_false_U0_start_write),
    .srcLayer2_dout(srcLayer2_dout),
    .srcLayer2_empty_n(srcLayer2_empty_n),
    .srcLayer2_read(v_mix_420_to_422_false_U0_srcLayer2_read),
    .srcLayer2_num_data_valid(srcLayer2_num_data_valid),
    .srcLayer2_fifo_cap(srcLayer2_fifo_cap),
    .HwReg_layerHeight_2_val(v_mix_420_to_422_false_U0_HwReg_layerHeight_2_val),
    .HwReg_layerWidth_2_val(v_mix_420_to_422_false_U0_HwReg_layerWidth_2_val),
    .HwReg_layerEnableFlag_2_val(HwReg_layerEnableFlag_2_val),
    .srcLayer2Yuv422_din(v_mix_420_to_422_false_U0_srcLayer2Yuv422_din),
    .srcLayer2Yuv422_full_n(srcLayer2Yuv422_full_n),
    .srcLayer2Yuv422_write(v_mix_420_to_422_false_U0_srcLayer2Yuv422_write),
    .srcLayer2Yuv422_num_data_valid(v_mix_420_to_422_false_U0_srcLayer2Yuv422_num_data_valid),
    .srcLayer2Yuv422_fifo_cap(v_mix_420_to_422_false_U0_srcLayer2Yuv422_fifo_cap)
);

design_1_v_mix_0_0_v_mix_422_to_444_false_s v_mix_422_to_444_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_422_to_444_false_U0_ap_start),
    .start_full_n(start_for_v_mix_yuv2rgb_false_U0_full_n),
    .ap_done(v_mix_422_to_444_false_U0_ap_done),
    .ap_continue(v_mix_422_to_444_false_U0_ap_continue),
    .ap_idle(v_mix_422_to_444_false_U0_ap_idle),
    .ap_ready(v_mix_422_to_444_false_U0_ap_ready),
    .start_out(v_mix_422_to_444_false_U0_start_out),
    .start_write(v_mix_422_to_444_false_U0_start_write),
    .srcLayer2Yuv422_dout(srcLayer2Yuv422_dout),
    .srcLayer2Yuv422_empty_n(srcLayer2Yuv422_empty_n),
    .srcLayer2Yuv422_read(v_mix_422_to_444_false_U0_srcLayer2Yuv422_read),
    .srcLayer2Yuv422_num_data_valid(srcLayer2Yuv422_num_data_valid),
    .srcLayer2Yuv422_fifo_cap(srcLayer2Yuv422_fifo_cap),
    .HwReg_layerHeight_2_val(v_mix_422_to_444_false_U0_HwReg_layerHeight_2_val),
    .HwReg_layerWidth_2_val(v_mix_422_to_444_false_U0_HwReg_layerWidth_2_val),
    .HwReg_layerEnableFlag_2_val(HwReg_layerEnableFlag_2_val),
    .srcLayer2Yuv_din(v_mix_422_to_444_false_U0_srcLayer2Yuv_din),
    .srcLayer2Yuv_full_n(srcLayer2Yuv_full_n),
    .srcLayer2Yuv_write(v_mix_422_to_444_false_U0_srcLayer2Yuv_write),
    .srcLayer2Yuv_num_data_valid(v_mix_422_to_444_false_U0_srcLayer2Yuv_num_data_valid),
    .srcLayer2Yuv_fifo_cap(v_mix_422_to_444_false_U0_srcLayer2Yuv_fifo_cap)
);

design_1_v_mix_0_0_v_mix_yuv2rgb_false_s v_mix_yuv2rgb_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_yuv2rgb_false_U0_ap_start),
    .start_full_n(start_for_v_mix_upsample_false_U0_full_n),
    .ap_done(v_mix_yuv2rgb_false_U0_ap_done),
    .ap_continue(v_mix_yuv2rgb_false_U0_ap_continue),
    .ap_idle(v_mix_yuv2rgb_false_U0_ap_idle),
    .ap_ready(v_mix_yuv2rgb_false_U0_ap_ready),
    .start_out(v_mix_yuv2rgb_false_U0_start_out),
    .start_write(v_mix_yuv2rgb_false_U0_start_write),
    .srcLayer2Yuv_dout(srcLayer2Yuv_dout),
    .srcLayer2Yuv_empty_n(srcLayer2Yuv_empty_n),
    .srcLayer2Yuv_read(v_mix_yuv2rgb_false_U0_srcLayer2Yuv_read),
    .srcLayer2Yuv_num_data_valid(srcLayer2Yuv_num_data_valid),
    .srcLayer2Yuv_fifo_cap(srcLayer2Yuv_fifo_cap),
    .HwReg_layerHeight_2_val(v_mix_yuv2rgb_false_U0_HwReg_layerHeight_2_val),
    .HwReg_layerWidth_2_val(v_mix_yuv2rgb_false_U0_HwReg_layerWidth_2_val),
    .HwReg_layerEnableFlag_2_val(HwReg_layerEnableFlag_2_val),
    .srcLayer2Rgb_din(v_mix_yuv2rgb_false_U0_srcLayer2Rgb_din),
    .srcLayer2Rgb_full_n(srcLayer2Rgb_full_n),
    .srcLayer2Rgb_write(v_mix_yuv2rgb_false_U0_srcLayer2Rgb_write),
    .srcLayer2Rgb_num_data_valid(v_mix_yuv2rgb_false_U0_srcLayer2Rgb_num_data_valid),
    .srcLayer2Rgb_fifo_cap(v_mix_yuv2rgb_false_U0_srcLayer2Rgb_fifo_cap)
);

design_1_v_mix_0_0_v_mix_upsample_false_s v_mix_upsample_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_upsample_false_U0_ap_start),
    .ap_done(v_mix_upsample_false_U0_ap_done),
    .ap_continue(v_mix_upsample_false_U0_ap_continue),
    .ap_idle(v_mix_upsample_false_U0_ap_idle),
    .ap_ready(v_mix_upsample_false_U0_ap_ready),
    .srcLayer2Rgb_dout(srcLayer2Rgb_dout),
    .srcLayer2Rgb_empty_n(srcLayer2Rgb_empty_n),
    .srcLayer2Rgb_read(v_mix_upsample_false_U0_srcLayer2Rgb_read),
    .srcLayer2Rgb_num_data_valid(srcLayer2Rgb_num_data_valid),
    .srcLayer2Rgb_fifo_cap(srcLayer2Rgb_fifo_cap),
    .HwReg_layerHeight_2_val(v_mix_upsample_false_U0_HwReg_layerHeight_2_val),
    .HwReg_layerWidth_2_val(v_mix_upsample_false_U0_HwReg_layerWidth_2_val),
    .HwReg_layerEnableFlag_2_val(HwReg_layerEnableFlag_2_val),
    .srcLayer2x_din(v_mix_upsample_false_U0_srcLayer2x_din),
    .srcLayer2x_full_n(srcLayer2x_full_n),
    .srcLayer2x_write(v_mix_upsample_false_U0_srcLayer2x_write),
    .srcLayer2x_num_data_valid(v_mix_upsample_false_U0_srcLayer2x_num_data_valid),
    .srcLayer2x_fifo_cap(v_mix_upsample_false_U0_srcLayer2x_fifo_cap)
);

design_1_v_mix_0_0_v_mix_core_alpha_true_false_s v_mix_core_alpha_true_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_core_alpha_true_false_U0_ap_start),
    .start_full_n(start_for_v_mix_rgb2yuv_false_U0_full_n),
    .ap_done(v_mix_core_alpha_true_false_U0_ap_done),
    .ap_continue(v_mix_core_alpha_true_false_U0_ap_continue),
    .ap_idle(v_mix_core_alpha_true_false_U0_ap_idle),
    .ap_ready(v_mix_core_alpha_true_false_U0_ap_ready),
    .start_out(v_mix_core_alpha_true_false_U0_start_out),
    .start_write(v_mix_core_alpha_true_false_U0_start_write),
    .outLayer1_dout(outLayer1_dout),
    .outLayer1_empty_n(outLayer1_empty_n),
    .outLayer1_read(v_mix_core_alpha_true_false_U0_outLayer1_read),
    .outLayer1_num_data_valid(outLayer1_num_data_valid),
    .outLayer1_fifo_cap(outLayer1_fifo_cap),
    .srcLayer2x_dout(srcLayer2x_dout),
    .srcLayer2x_empty_n(srcLayer2x_empty_n),
    .srcLayer2x_read(v_mix_core_alpha_true_false_U0_srcLayer2x_read),
    .srcLayer2x_num_data_valid(srcLayer2x_num_data_valid),
    .srcLayer2x_fifo_cap(srcLayer2x_fifo_cap),
    .hwReg_width_val(HwReg_width_val),
    .hwReg_height_val(HwReg_height_val),
    .hwReg_layerEnable_val(HwReg_layerEnable_val16),
    .hwReg_layerAlpha_2_val(HwReg_layerAlpha_2_val17),
    .hwReg_layerStartX_2_val(HwReg_layerStartX_2_val19),
    .hwReg_layerStartY_2_val(HwReg_layerStartY_2_val21),
    .hwReg_layerWidth_2_val(HwReg_layerWidth_2_val),
    .hwReg_layerHeight_2_val(HwReg_layerHeight_2_val),
    .hwReg_layerScaleFactor_2_val(HwReg_layerScaleFactor_2_val27),
    .outLayer2_din(v_mix_core_alpha_true_false_U0_outLayer2_din),
    .outLayer2_full_n(outLayer2_full_n),
    .outLayer2_write(v_mix_core_alpha_true_false_U0_outLayer2_write),
    .outLayer2_num_data_valid(v_mix_core_alpha_true_false_U0_outLayer2_num_data_valid),
    .outLayer2_fifo_cap(v_mix_core_alpha_true_false_U0_outLayer2_fifo_cap)
);

design_1_v_mix_0_0_v_mix_rgb2yuv_false_s v_mix_rgb2yuv_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_rgb2yuv_false_U0_ap_start),
    .start_full_n(start_for_v_mix_444_to_422_false_U0_full_n),
    .ap_done(v_mix_rgb2yuv_false_U0_ap_done),
    .ap_continue(v_mix_rgb2yuv_false_U0_ap_continue),
    .ap_idle(v_mix_rgb2yuv_false_U0_ap_idle),
    .ap_ready(v_mix_rgb2yuv_false_U0_ap_ready),
    .start_out(v_mix_rgb2yuv_false_U0_start_out),
    .start_write(v_mix_rgb2yuv_false_U0_start_write),
    .outLayer2_dout(outLayer2_dout),
    .outLayer2_empty_n(outLayer2_empty_n),
    .outLayer2_read(v_mix_rgb2yuv_false_U0_outLayer2_read),
    .outLayer2_num_data_valid(outLayer2_num_data_valid),
    .outLayer2_fifo_cap(outLayer2_fifo_cap),
    .height_val(HwReg_height_val),
    .width_val(HwReg_width_val),
    .outYuv_din(v_mix_rgb2yuv_false_U0_outYuv_din),
    .outYuv_full_n(outYuv_full_n),
    .outYuv_write(v_mix_rgb2yuv_false_U0_outYuv_write),
    .outYuv_num_data_valid(v_mix_rgb2yuv_false_U0_outYuv_num_data_valid),
    .outYuv_fifo_cap(v_mix_rgb2yuv_false_U0_outYuv_fifo_cap)
);

design_1_v_mix_0_0_v_mix_444_to_422_false_s v_mix_444_to_422_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_444_to_422_false_U0_ap_start),
    .start_full_n(start_for_v_mix_422_to_420_false_U0_full_n),
    .ap_done(v_mix_444_to_422_false_U0_ap_done),
    .ap_continue(v_mix_444_to_422_false_U0_ap_continue),
    .ap_idle(v_mix_444_to_422_false_U0_ap_idle),
    .ap_ready(v_mix_444_to_422_false_U0_ap_ready),
    .start_out(v_mix_444_to_422_false_U0_start_out),
    .start_write(v_mix_444_to_422_false_U0_start_write),
    .outYuv_dout(outYuv_dout),
    .outYuv_empty_n(outYuv_empty_n),
    .outYuv_read(v_mix_444_to_422_false_U0_outYuv_read),
    .outYuv_num_data_valid(outYuv_num_data_valid),
    .outYuv_fifo_cap(outYuv_fifo_cap),
    .height_val(HwReg_height_val),
    .width_val(HwReg_width_val),
    .out422_din(v_mix_444_to_422_false_U0_out422_din),
    .out422_full_n(out422_full_n),
    .out422_write(v_mix_444_to_422_false_U0_out422_write),
    .out422_num_data_valid(v_mix_444_to_422_false_U0_out422_num_data_valid),
    .out422_fifo_cap(v_mix_444_to_422_false_U0_out422_fifo_cap)
);

design_1_v_mix_0_0_v_mix_422_to_420_false_s v_mix_422_to_420_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_mix_422_to_420_false_U0_ap_start),
    .start_full_n(start_for_MultiPixStream2AXIvideo_U0_full_n),
    .ap_done(v_mix_422_to_420_false_U0_ap_done),
    .ap_continue(v_mix_422_to_420_false_U0_ap_continue),
    .ap_idle(v_mix_422_to_420_false_U0_ap_idle),
    .ap_ready(v_mix_422_to_420_false_U0_ap_ready),
    .start_out(v_mix_422_to_420_false_U0_start_out),
    .start_write(v_mix_422_to_420_false_U0_start_write),
    .out422_dout(out422_dout),
    .out422_empty_n(out422_empty_n),
    .out422_read(v_mix_422_to_420_false_U0_out422_read),
    .out422_num_data_valid(out422_num_data_valid),
    .out422_fifo_cap(out422_fifo_cap),
    .height_val(HwReg_height_val),
    .width_val(HwReg_width_val),
    .out420_din(v_mix_422_to_420_false_U0_out420_din),
    .out420_full_n(out420_full_n),
    .out420_write(v_mix_422_to_420_false_U0_out420_write),
    .out420_num_data_valid(v_mix_422_to_420_false_U0_out420_num_data_valid),
    .out420_fifo_cap(v_mix_422_to_420_false_U0_out420_fifo_cap)
);

design_1_v_mix_0_0_MultiPixStream2AXIvideo MultiPixStream2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(MultiPixStream2AXIvideo_U0_ap_start),
    .ap_done(MultiPixStream2AXIvideo_U0_ap_done),
    .ap_continue(MultiPixStream2AXIvideo_U0_ap_continue),
    .ap_idle(MultiPixStream2AXIvideo_U0_ap_idle),
    .ap_ready(MultiPixStream2AXIvideo_U0_ap_ready),
    .out420_dout(out420_dout),
    .out420_empty_n(out420_empty_n),
    .out420_read(MultiPixStream2AXIvideo_U0_out420_read),
    .out420_num_data_valid(out420_num_data_valid),
    .out420_fifo_cap(out420_fifo_cap),
    .m_axis_video_TDATA(MultiPixStream2AXIvideo_U0_m_axis_video_TDATA),
    .m_axis_video_TVALID(MultiPixStream2AXIvideo_U0_m_axis_video_TVALID),
    .m_axis_video_TREADY(m_axis_video_TREADY),
    .m_axis_video_TKEEP(MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB),
    .m_axis_video_TUSER(MultiPixStream2AXIvideo_U0_m_axis_video_TUSER),
    .m_axis_video_TLAST(MultiPixStream2AXIvideo_U0_m_axis_video_TLAST),
    .m_axis_video_TID(MultiPixStream2AXIvideo_U0_m_axis_video_TID),
    .m_axis_video_TDEST(MultiPixStream2AXIvideo_U0_m_axis_video_TDEST),
    .Height(HwReg_height_val),
    .WidthOut(HwReg_width_val)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_1_U0_srcLayer0_din),
    .if_full_n(srcLayer0_full_n),
    .if_write(AXIvideo2MultiPixStream_1_U0_srcLayer0_write),
    .if_dout(srcLayer0_dout),
    .if_empty_n(srcLayer0_empty_n),
    .if_read(v_mix_420_to_422_false_2_U0_srcLayer0_read),
    .if_num_data_valid(srcLayer0_num_data_valid),
    .if_fifo_cap(srcLayer0_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer0Yuv422_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_420_to_422_false_2_U0_srcLayer0Yuv422_din),
    .if_full_n(srcLayer0Yuv422_full_n),
    .if_write(v_mix_420_to_422_false_2_U0_srcLayer0Yuv422_write),
    .if_dout(srcLayer0Yuv422_dout),
    .if_empty_n(srcLayer0Yuv422_empty_n),
    .if_read(v_mix_422_to_444_false_3_U0_srcLayer0Yuv422_read),
    .if_num_data_valid(srcLayer0Yuv422_num_data_valid),
    .if_fifo_cap(srcLayer0Yuv422_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer0Yuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_422_to_444_false_3_U0_srcLayer0Yuv_din),
    .if_full_n(srcLayer0Yuv_full_n),
    .if_write(v_mix_422_to_444_false_3_U0_srcLayer0Yuv_write),
    .if_dout(srcLayer0Yuv_dout),
    .if_empty_n(srcLayer0Yuv_empty_n),
    .if_read(v_mix_yuv2rgb_false_4_U0_srcLayer0Yuv_read),
    .if_num_data_valid(srcLayer0Yuv_num_data_valid),
    .if_fifo_cap(srcLayer0Yuv_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S outLayer0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_yuv2rgb_false_4_U0_outLayer0_din),
    .if_full_n(outLayer0_full_n),
    .if_write(v_mix_yuv2rgb_false_4_U0_outLayer0_write),
    .if_dout(outLayer0_dout),
    .if_empty_n(outLayer0_empty_n),
    .if_read(v_mix_core_alpha_false_false_U0_outLayer0_read),
    .if_num_data_valid(outLayer0_num_data_valid),
    .if_fifo_cap(outLayer0_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_5_U0_srcLayer1_din),
    .if_full_n(srcLayer1_full_n),
    .if_write(AXIvideo2MultiPixStream_5_U0_srcLayer1_write),
    .if_dout(srcLayer1_dout),
    .if_empty_n(srcLayer1_empty_n),
    .if_read(v_mix_420_to_422_false_6_U0_srcLayer1_read),
    .if_num_data_valid(srcLayer1_num_data_valid),
    .if_fifo_cap(srcLayer1_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer1Yuv422_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_420_to_422_false_6_U0_srcLayer1Yuv422_din),
    .if_full_n(srcLayer1Yuv422_full_n),
    .if_write(v_mix_420_to_422_false_6_U0_srcLayer1Yuv422_write),
    .if_dout(srcLayer1Yuv422_dout),
    .if_empty_n(srcLayer1Yuv422_empty_n),
    .if_read(v_mix_422_to_444_true_U0_srcLayer1Yuv422_read),
    .if_num_data_valid(srcLayer1Yuv422_num_data_valid),
    .if_fifo_cap(srcLayer1Yuv422_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer1Yuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_422_to_444_true_U0_srcLayer1Yuv_din),
    .if_full_n(srcLayer1Yuv_full_n),
    .if_write(v_mix_422_to_444_true_U0_srcLayer1Yuv_write),
    .if_dout(srcLayer1Yuv_dout),
    .if_empty_n(srcLayer1Yuv_empty_n),
    .if_read(v_mix_yuv2rgb_true_U0_srcLayer1Yuv_read),
    .if_num_data_valid(srcLayer1Yuv_num_data_valid),
    .if_fifo_cap(srcLayer1Yuv_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer1Rgb_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_yuv2rgb_true_U0_srcLayer1Rgb_din),
    .if_full_n(srcLayer1Rgb_full_n),
    .if_write(v_mix_yuv2rgb_true_U0_srcLayer1Rgb_write),
    .if_dout(srcLayer1Rgb_dout),
    .if_empty_n(srcLayer1Rgb_empty_n),
    .if_read(v_mix_upsample_false_7_U0_srcLayer1Rgb_read),
    .if_num_data_valid(srcLayer1Rgb_num_data_valid),
    .if_fifo_cap(srcLayer1Rgb_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer1x_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_upsample_false_7_U0_srcLayer1x_din),
    .if_full_n(srcLayer1x_full_n),
    .if_write(v_mix_upsample_false_7_U0_srcLayer1x_write),
    .if_dout(srcLayer1x_dout),
    .if_empty_n(srcLayer1x_empty_n),
    .if_read(v_mix_core_alpha_false_false_U0_srcLayer1x_read),
    .if_num_data_valid(srcLayer1x_num_data_valid),
    .if_fifo_cap(srcLayer1x_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S outLayer1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_core_alpha_false_false_U0_outLayer1_din),
    .if_full_n(outLayer1_full_n),
    .if_write(v_mix_core_alpha_false_false_U0_outLayer1_write),
    .if_dout(outLayer1_dout),
    .if_empty_n(outLayer1_empty_n),
    .if_read(v_mix_core_alpha_true_false_U0_outLayer1_read),
    .if_num_data_valid(outLayer1_num_data_valid),
    .if_fifo_cap(outLayer1_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_srcLayer2_din),
    .if_full_n(srcLayer2_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_srcLayer2_write),
    .if_dout(srcLayer2_dout),
    .if_empty_n(srcLayer2_empty_n),
    .if_read(v_mix_420_to_422_false_U0_srcLayer2_read),
    .if_num_data_valid(srcLayer2_num_data_valid),
    .if_fifo_cap(srcLayer2_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer2Yuv422_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_420_to_422_false_U0_srcLayer2Yuv422_din),
    .if_full_n(srcLayer2Yuv422_full_n),
    .if_write(v_mix_420_to_422_false_U0_srcLayer2Yuv422_write),
    .if_dout(srcLayer2Yuv422_dout),
    .if_empty_n(srcLayer2Yuv422_empty_n),
    .if_read(v_mix_422_to_444_false_U0_srcLayer2Yuv422_read),
    .if_num_data_valid(srcLayer2Yuv422_num_data_valid),
    .if_fifo_cap(srcLayer2Yuv422_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer2Yuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_422_to_444_false_U0_srcLayer2Yuv_din),
    .if_full_n(srcLayer2Yuv_full_n),
    .if_write(v_mix_422_to_444_false_U0_srcLayer2Yuv_write),
    .if_dout(srcLayer2Yuv_dout),
    .if_empty_n(srcLayer2Yuv_empty_n),
    .if_read(v_mix_yuv2rgb_false_U0_srcLayer2Yuv_read),
    .if_num_data_valid(srcLayer2Yuv_num_data_valid),
    .if_fifo_cap(srcLayer2Yuv_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer2Rgb_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_yuv2rgb_false_U0_srcLayer2Rgb_din),
    .if_full_n(srcLayer2Rgb_full_n),
    .if_write(v_mix_yuv2rgb_false_U0_srcLayer2Rgb_write),
    .if_dout(srcLayer2Rgb_dout),
    .if_empty_n(srcLayer2Rgb_empty_n),
    .if_read(v_mix_upsample_false_U0_srcLayer2Rgb_read),
    .if_num_data_valid(srcLayer2Rgb_num_data_valid),
    .if_fifo_cap(srcLayer2Rgb_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S srcLayer2x_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_upsample_false_U0_srcLayer2x_din),
    .if_full_n(srcLayer2x_full_n),
    .if_write(v_mix_upsample_false_U0_srcLayer2x_write),
    .if_dout(srcLayer2x_dout),
    .if_empty_n(srcLayer2x_empty_n),
    .if_read(v_mix_core_alpha_true_false_U0_srcLayer2x_read),
    .if_num_data_valid(srcLayer2x_num_data_valid),
    .if_fifo_cap(srcLayer2x_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S outLayer2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_core_alpha_true_false_U0_outLayer2_din),
    .if_full_n(outLayer2_full_n),
    .if_write(v_mix_core_alpha_true_false_U0_outLayer2_write),
    .if_dout(outLayer2_dout),
    .if_empty_n(outLayer2_empty_n),
    .if_read(v_mix_rgb2yuv_false_U0_outLayer2_read),
    .if_num_data_valid(outLayer2_num_data_valid),
    .if_fifo_cap(outLayer2_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S outYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_rgb2yuv_false_U0_outYuv_din),
    .if_full_n(outYuv_full_n),
    .if_write(v_mix_rgb2yuv_false_U0_outYuv_write),
    .if_dout(outYuv_dout),
    .if_empty_n(outYuv_empty_n),
    .if_read(v_mix_444_to_422_false_U0_outYuv_read),
    .if_num_data_valid(outYuv_num_data_valid),
    .if_fifo_cap(outYuv_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S out422_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_444_to_422_false_U0_out422_din),
    .if_full_n(out422_full_n),
    .if_write(v_mix_444_to_422_false_U0_out422_write),
    .if_dout(out422_dout),
    .if_empty_n(out422_empty_n),
    .if_read(v_mix_422_to_420_false_U0_out422_read),
    .if_num_data_valid(out422_num_data_valid),
    .if_fifo_cap(out422_fifo_cap)
);

design_1_v_mix_0_0_fifo_w24_d2_S out420_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_mix_422_to_420_false_U0_out420_din),
    .if_full_n(out420_full_n),
    .if_write(v_mix_422_to_420_false_U0_out420_write),
    .if_dout(out420_dout),
    .if_empty_n(out420_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_out420_read),
    .if_num_data_valid(out420_num_data_valid),
    .if_fifo_cap(out420_fifo_cap)
);

design_1_v_mix_0_0_start_for_v_mix_420_to_422_false_2_U0 start_for_v_mix_420_to_422_false_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_420_to_422_false_2_U0_din),
    .if_full_n(start_for_v_mix_420_to_422_false_2_U0_full_n),
    .if_write(AXIvideo2MultiPixStream_1_U0_start_write),
    .if_dout(start_for_v_mix_420_to_422_false_2_U0_dout),
    .if_empty_n(start_for_v_mix_420_to_422_false_2_U0_empty_n),
    .if_read(v_mix_420_to_422_false_2_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_422_to_444_false_3_U0 start_for_v_mix_422_to_444_false_3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_422_to_444_false_3_U0_din),
    .if_full_n(start_for_v_mix_422_to_444_false_3_U0_full_n),
    .if_write(v_mix_420_to_422_false_2_U0_start_write),
    .if_dout(start_for_v_mix_422_to_444_false_3_U0_dout),
    .if_empty_n(start_for_v_mix_422_to_444_false_3_U0_empty_n),
    .if_read(v_mix_422_to_444_false_3_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_yuv2rgb_false_4_U0 start_for_v_mix_yuv2rgb_false_4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_yuv2rgb_false_4_U0_din),
    .if_full_n(start_for_v_mix_yuv2rgb_false_4_U0_full_n),
    .if_write(v_mix_422_to_444_false_3_U0_start_write),
    .if_dout(start_for_v_mix_yuv2rgb_false_4_U0_dout),
    .if_empty_n(start_for_v_mix_yuv2rgb_false_4_U0_empty_n),
    .if_read(v_mix_yuv2rgb_false_4_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_core_alpha_false_false_U0 start_for_v_mix_core_alpha_false_false_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_core_alpha_false_false_U0_din),
    .if_full_n(start_for_v_mix_core_alpha_false_false_U0_full_n),
    .if_write(v_mix_yuv2rgb_false_4_U0_start_write),
    .if_dout(start_for_v_mix_core_alpha_false_false_U0_dout),
    .if_empty_n(start_for_v_mix_core_alpha_false_false_U0_empty_n),
    .if_read(v_mix_core_alpha_false_false_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_420_to_422_false_6_U0 start_for_v_mix_420_to_422_false_6_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_420_to_422_false_6_U0_din),
    .if_full_n(start_for_v_mix_420_to_422_false_6_U0_full_n),
    .if_write(AXIvideo2MultiPixStream_5_U0_start_write),
    .if_dout(start_for_v_mix_420_to_422_false_6_U0_dout),
    .if_empty_n(start_for_v_mix_420_to_422_false_6_U0_empty_n),
    .if_read(v_mix_420_to_422_false_6_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_422_to_444_true_U0 start_for_v_mix_422_to_444_true_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_422_to_444_true_U0_din),
    .if_full_n(start_for_v_mix_422_to_444_true_U0_full_n),
    .if_write(v_mix_420_to_422_false_6_U0_start_write),
    .if_dout(start_for_v_mix_422_to_444_true_U0_dout),
    .if_empty_n(start_for_v_mix_422_to_444_true_U0_empty_n),
    .if_read(v_mix_422_to_444_true_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_yuv2rgb_true_U0 start_for_v_mix_yuv2rgb_true_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_yuv2rgb_true_U0_din),
    .if_full_n(start_for_v_mix_yuv2rgb_true_U0_full_n),
    .if_write(v_mix_422_to_444_true_U0_start_write),
    .if_dout(start_for_v_mix_yuv2rgb_true_U0_dout),
    .if_empty_n(start_for_v_mix_yuv2rgb_true_U0_empty_n),
    .if_read(v_mix_yuv2rgb_true_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_upsample_false_7_U0 start_for_v_mix_upsample_false_7_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_upsample_false_7_U0_din),
    .if_full_n(start_for_v_mix_upsample_false_7_U0_full_n),
    .if_write(v_mix_yuv2rgb_true_U0_start_write),
    .if_dout(start_for_v_mix_upsample_false_7_U0_dout),
    .if_empty_n(start_for_v_mix_upsample_false_7_U0_empty_n),
    .if_read(v_mix_upsample_false_7_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_core_alpha_true_false_U0 start_for_v_mix_core_alpha_true_false_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_core_alpha_true_false_U0_din),
    .if_full_n(start_for_v_mix_core_alpha_true_false_U0_full_n),
    .if_write(v_mix_core_alpha_false_false_U0_start_write),
    .if_dout(start_for_v_mix_core_alpha_true_false_U0_dout),
    .if_empty_n(start_for_v_mix_core_alpha_true_false_U0_empty_n),
    .if_read(v_mix_core_alpha_true_false_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_420_to_422_false_U0 start_for_v_mix_420_to_422_false_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_420_to_422_false_U0_din),
    .if_full_n(start_for_v_mix_420_to_422_false_U0_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_start_write),
    .if_dout(start_for_v_mix_420_to_422_false_U0_dout),
    .if_empty_n(start_for_v_mix_420_to_422_false_U0_empty_n),
    .if_read(v_mix_420_to_422_false_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_422_to_444_false_U0 start_for_v_mix_422_to_444_false_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_422_to_444_false_U0_din),
    .if_full_n(start_for_v_mix_422_to_444_false_U0_full_n),
    .if_write(v_mix_420_to_422_false_U0_start_write),
    .if_dout(start_for_v_mix_422_to_444_false_U0_dout),
    .if_empty_n(start_for_v_mix_422_to_444_false_U0_empty_n),
    .if_read(v_mix_422_to_444_false_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_yuv2rgb_false_U0 start_for_v_mix_yuv2rgb_false_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_yuv2rgb_false_U0_din),
    .if_full_n(start_for_v_mix_yuv2rgb_false_U0_full_n),
    .if_write(v_mix_422_to_444_false_U0_start_write),
    .if_dout(start_for_v_mix_yuv2rgb_false_U0_dout),
    .if_empty_n(start_for_v_mix_yuv2rgb_false_U0_empty_n),
    .if_read(v_mix_yuv2rgb_false_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_upsample_false_U0 start_for_v_mix_upsample_false_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_upsample_false_U0_din),
    .if_full_n(start_for_v_mix_upsample_false_U0_full_n),
    .if_write(v_mix_yuv2rgb_false_U0_start_write),
    .if_dout(start_for_v_mix_upsample_false_U0_dout),
    .if_empty_n(start_for_v_mix_upsample_false_U0_empty_n),
    .if_read(v_mix_upsample_false_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_rgb2yuv_false_U0 start_for_v_mix_rgb2yuv_false_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_rgb2yuv_false_U0_din),
    .if_full_n(start_for_v_mix_rgb2yuv_false_U0_full_n),
    .if_write(v_mix_core_alpha_true_false_U0_start_write),
    .if_dout(start_for_v_mix_rgb2yuv_false_U0_dout),
    .if_empty_n(start_for_v_mix_rgb2yuv_false_U0_empty_n),
    .if_read(v_mix_rgb2yuv_false_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_444_to_422_false_U0 start_for_v_mix_444_to_422_false_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_444_to_422_false_U0_din),
    .if_full_n(start_for_v_mix_444_to_422_false_U0_full_n),
    .if_write(v_mix_rgb2yuv_false_U0_start_write),
    .if_dout(start_for_v_mix_444_to_422_false_U0_dout),
    .if_empty_n(start_for_v_mix_444_to_422_false_U0_empty_n),
    .if_read(v_mix_444_to_422_false_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_v_mix_422_to_420_false_U0 start_for_v_mix_422_to_420_false_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_v_mix_422_to_420_false_U0_din),
    .if_full_n(start_for_v_mix_422_to_420_false_U0_full_n),
    .if_write(v_mix_444_to_422_false_U0_start_write),
    .if_dout(start_for_v_mix_422_to_420_false_U0_dout),
    .if_empty_n(start_for_v_mix_422_to_420_false_U0_empty_n),
    .if_read(v_mix_422_to_420_false_U0_ap_ready)
);

design_1_v_mix_0_0_start_for_MultiPixStream2AXIvideo_U0 start_for_MultiPixStream2AXIvideo_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_MultiPixStream2AXIvideo_U0_din),
    .if_full_n(start_for_MultiPixStream2AXIvideo_U0_full_n),
    .if_write(v_mix_422_to_420_false_U0_start_write),
    .if_dout(start_for_MultiPixStream2AXIvideo_U0_dout),
    .if_empty_n(start_for_MultiPixStream2AXIvideo_U0_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_AXIvideo2MultiPixStream_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_AXIvideo2MultiPixStream_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_AXIvideo2MultiPixStream_1_U0_ap_ready <= ap_sync_AXIvideo2MultiPixStream_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_AXIvideo2MultiPixStream_5_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_AXIvideo2MultiPixStream_5_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_AXIvideo2MultiPixStream_5_U0_ap_ready <= ap_sync_AXIvideo2MultiPixStream_5_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_sync_ready <= (~ap_sync_ready & ap_sync_AXIvideo2MultiPixStream_U0_ap_ready & ap_sync_AXIvideo2MultiPixStream_5_U0_ap_ready & ap_sync_AXIvideo2MultiPixStream_1_U0_ap_ready & ap_start);
end

assign AXIvideo2MultiPixStream_1_U0_ap_continue = 1'b1;

assign AXIvideo2MultiPixStream_1_U0_ap_start = ((ap_sync_reg_AXIvideo2MultiPixStream_1_U0_ap_ready ^ 1'b1) & ~ap_sync_ready & ap_start);

assign AXIvideo2MultiPixStream_5_U0_HwReg_layerHeight_1_val = {{HwReg_layerHeight_1_val[(12 - 16'd1):0]}};

assign AXIvideo2MultiPixStream_5_U0_HwReg_layerWidth_1_val = {{HwReg_layerWidth_1_val[(12 - 16'd1):0]}};

assign AXIvideo2MultiPixStream_5_U0_ap_continue = 1'b1;

assign AXIvideo2MultiPixStream_5_U0_ap_start = ((ap_sync_reg_AXIvideo2MultiPixStream_5_U0_ap_ready ^ 1'b1) & ~ap_sync_ready & ap_start);

assign AXIvideo2MultiPixStream_U0_HwReg_layerHeight_2_val = {{HwReg_layerHeight_2_val[(12 - 16'd1):0]}};

assign AXIvideo2MultiPixStream_U0_HwReg_layerWidth_2_val = {{HwReg_layerWidth_2_val[(12 - 16'd1):0]}};

assign AXIvideo2MultiPixStream_U0_ap_continue = 1'b1;

assign AXIvideo2MultiPixStream_U0_ap_start = ((ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready ^ 1'b1) & ~ap_sync_ready & ap_start);

assign MultiPixStream2AXIvideo_U0_ap_continue = ap_continue;

assign MultiPixStream2AXIvideo_U0_ap_start = start_for_MultiPixStream2AXIvideo_U0_empty_n;

assign ap_done = MultiPixStream2AXIvideo_U0_ap_done;

assign ap_idle = (v_mix_yuv2rgb_true_U0_ap_idle & v_mix_yuv2rgb_false_U0_ap_idle & v_mix_yuv2rgb_false_4_U0_ap_idle & v_mix_upsample_false_U0_ap_idle & v_mix_upsample_false_7_U0_ap_idle & v_mix_rgb2yuv_false_U0_ap_idle & v_mix_core_alpha_true_false_U0_ap_idle & v_mix_core_alpha_false_false_U0_ap_idle & v_mix_444_to_422_false_U0_ap_idle & v_mix_422_to_444_true_U0_ap_idle & v_mix_422_to_444_false_U0_ap_idle & v_mix_422_to_444_false_3_U0_ap_idle & v_mix_422_to_420_false_U0_ap_idle & v_mix_420_to_422_false_U0_ap_idle & v_mix_420_to_422_false_6_U0_ap_idle & v_mix_420_to_422_false_2_U0_ap_idle & MultiPixStream2AXIvideo_U0_ap_idle & AXIvideo2MultiPixStream_U0_ap_idle & AXIvideo2MultiPixStream_5_U0_ap_idle & AXIvideo2MultiPixStream_1_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_AXIvideo2MultiPixStream_1_U0_ap_ready = (ap_sync_reg_AXIvideo2MultiPixStream_1_U0_ap_ready | AXIvideo2MultiPixStream_1_U0_ap_ready);

assign ap_sync_AXIvideo2MultiPixStream_5_U0_ap_ready = (ap_sync_reg_AXIvideo2MultiPixStream_5_U0_ap_ready | AXIvideo2MultiPixStream_5_U0_ap_ready);

assign ap_sync_AXIvideo2MultiPixStream_U0_ap_ready = (ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready | AXIvideo2MultiPixStream_U0_ap_ready);

assign m_axis_video_TDATA = MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;

assign m_axis_video_TDEST = MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;

assign m_axis_video_TID = MultiPixStream2AXIvideo_U0_m_axis_video_TID;

assign m_axis_video_TKEEP = MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;

assign m_axis_video_TLAST = MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;

assign m_axis_video_TSTRB = MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;

assign m_axis_video_TUSER = MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;

assign m_axis_video_TVALID = MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;

assign s_axis_video1_TREADY = AXIvideo2MultiPixStream_5_U0_s_axis_video1_TREADY;

assign s_axis_video2_TREADY = AXIvideo2MultiPixStream_U0_s_axis_video2_TREADY;

assign s_axis_video_TREADY = AXIvideo2MultiPixStream_1_U0_s_axis_video_TREADY;

assign start_for_MultiPixStream2AXIvideo_U0_din = 1'b1;

assign start_for_v_mix_420_to_422_false_2_U0_din = 1'b1;

assign start_for_v_mix_420_to_422_false_6_U0_din = 1'b1;

assign start_for_v_mix_420_to_422_false_U0_din = 1'b1;

assign start_for_v_mix_422_to_420_false_U0_din = 1'b1;

assign start_for_v_mix_422_to_444_false_3_U0_din = 1'b1;

assign start_for_v_mix_422_to_444_false_U0_din = 1'b1;

assign start_for_v_mix_422_to_444_true_U0_din = 1'b1;

assign start_for_v_mix_444_to_422_false_U0_din = 1'b1;

assign start_for_v_mix_core_alpha_false_false_U0_din = 1'b1;

assign start_for_v_mix_core_alpha_true_false_U0_din = 1'b1;

assign start_for_v_mix_rgb2yuv_false_U0_din = 1'b1;

assign start_for_v_mix_upsample_false_7_U0_din = 1'b1;

assign start_for_v_mix_upsample_false_U0_din = 1'b1;

assign start_for_v_mix_yuv2rgb_false_4_U0_din = 1'b1;

assign start_for_v_mix_yuv2rgb_false_U0_din = 1'b1;

assign start_for_v_mix_yuv2rgb_true_U0_din = 1'b1;

assign v_mix_420_to_422_false_2_U0_ap_continue = 1'b1;

assign v_mix_420_to_422_false_2_U0_ap_start = start_for_v_mix_420_to_422_false_2_U0_empty_n;

assign v_mix_420_to_422_false_2_U0_srcLayer0Yuv422_fifo_cap = srcLayer0Yuv422_fifo_cap;

assign v_mix_420_to_422_false_2_U0_srcLayer0Yuv422_num_data_valid = srcLayer0Yuv422_num_data_valid;

assign v_mix_420_to_422_false_6_U0_HwReg_layerHeight_1_val = {{HwReg_layerHeight_1_val[(12 - 16'd1):0]}};

assign v_mix_420_to_422_false_6_U0_HwReg_layerWidth_1_val = {{HwReg_layerWidth_1_val[(12 - 16'd1):0]}};

assign v_mix_420_to_422_false_6_U0_ap_continue = 1'b1;

assign v_mix_420_to_422_false_6_U0_ap_start = start_for_v_mix_420_to_422_false_6_U0_empty_n;

assign v_mix_420_to_422_false_6_U0_srcLayer1Yuv422_fifo_cap = srcLayer1Yuv422_fifo_cap;

assign v_mix_420_to_422_false_6_U0_srcLayer1Yuv422_num_data_valid = srcLayer1Yuv422_num_data_valid;

assign v_mix_420_to_422_false_U0_HwReg_layerHeight_2_val = {{HwReg_layerHeight_2_val[(12 - 16'd1):0]}};

assign v_mix_420_to_422_false_U0_HwReg_layerWidth_2_val = {{HwReg_layerWidth_2_val[(12 - 16'd1):0]}};

assign v_mix_420_to_422_false_U0_ap_continue = 1'b1;

assign v_mix_420_to_422_false_U0_ap_start = start_for_v_mix_420_to_422_false_U0_empty_n;

assign v_mix_420_to_422_false_U0_srcLayer2Yuv422_fifo_cap = srcLayer2Yuv422_fifo_cap;

assign v_mix_420_to_422_false_U0_srcLayer2Yuv422_num_data_valid = srcLayer2Yuv422_num_data_valid;

assign v_mix_422_to_420_false_U0_ap_continue = 1'b1;

assign v_mix_422_to_420_false_U0_ap_start = start_for_v_mix_422_to_420_false_U0_empty_n;

assign v_mix_422_to_420_false_U0_out420_fifo_cap = out420_fifo_cap;

assign v_mix_422_to_420_false_U0_out420_num_data_valid = out420_num_data_valid;

assign v_mix_422_to_444_false_3_U0_ap_continue = 1'b1;

assign v_mix_422_to_444_false_3_U0_ap_start = start_for_v_mix_422_to_444_false_3_U0_empty_n;

assign v_mix_422_to_444_false_3_U0_srcLayer0Yuv_fifo_cap = srcLayer0Yuv_fifo_cap;

assign v_mix_422_to_444_false_3_U0_srcLayer0Yuv_num_data_valid = srcLayer0Yuv_num_data_valid;

assign v_mix_422_to_444_false_U0_HwReg_layerHeight_2_val = {{HwReg_layerHeight_2_val[(12 - 16'd1):0]}};

assign v_mix_422_to_444_false_U0_HwReg_layerWidth_2_val = {{HwReg_layerWidth_2_val[(12 - 16'd1):0]}};

assign v_mix_422_to_444_false_U0_ap_continue = 1'b1;

assign v_mix_422_to_444_false_U0_ap_start = start_for_v_mix_422_to_444_false_U0_empty_n;

assign v_mix_422_to_444_false_U0_srcLayer2Yuv_fifo_cap = srcLayer2Yuv_fifo_cap;

assign v_mix_422_to_444_false_U0_srcLayer2Yuv_num_data_valid = srcLayer2Yuv_num_data_valid;

assign v_mix_422_to_444_true_U0_ap_continue = 1'b1;

assign v_mix_422_to_444_true_U0_ap_start = start_for_v_mix_422_to_444_true_U0_empty_n;

assign v_mix_422_to_444_true_U0_srcLayer1Yuv_fifo_cap = srcLayer1Yuv_fifo_cap;

assign v_mix_422_to_444_true_U0_srcLayer1Yuv_num_data_valid = srcLayer1Yuv_num_data_valid;

assign v_mix_444_to_422_false_U0_ap_continue = 1'b1;

assign v_mix_444_to_422_false_U0_ap_start = start_for_v_mix_444_to_422_false_U0_empty_n;

assign v_mix_444_to_422_false_U0_out422_fifo_cap = out422_fifo_cap;

assign v_mix_444_to_422_false_U0_out422_num_data_valid = out422_num_data_valid;

assign v_mix_core_alpha_false_false_U0_HwReg_layerEnable_val16 = {{HwReg_layerEnable_val16[(2 - 3'd1):0]}};

assign v_mix_core_alpha_false_false_U0_ap_continue = 1'b1;

assign v_mix_core_alpha_false_false_U0_ap_start = start_for_v_mix_core_alpha_false_false_U0_empty_n;

assign v_mix_core_alpha_false_false_U0_outLayer1_fifo_cap = outLayer1_fifo_cap;

assign v_mix_core_alpha_false_false_U0_outLayer1_num_data_valid = outLayer1_num_data_valid;

assign v_mix_core_alpha_true_false_U0_ap_continue = 1'b1;

assign v_mix_core_alpha_true_false_U0_ap_start = start_for_v_mix_core_alpha_true_false_U0_empty_n;

assign v_mix_core_alpha_true_false_U0_outLayer2_fifo_cap = outLayer2_fifo_cap;

assign v_mix_core_alpha_true_false_U0_outLayer2_num_data_valid = outLayer2_num_data_valid;

assign v_mix_rgb2yuv_false_U0_ap_continue = 1'b1;

assign v_mix_rgb2yuv_false_U0_ap_start = start_for_v_mix_rgb2yuv_false_U0_empty_n;

assign v_mix_rgb2yuv_false_U0_outYuv_fifo_cap = outYuv_fifo_cap;

assign v_mix_rgb2yuv_false_U0_outYuv_num_data_valid = outYuv_num_data_valid;

assign v_mix_upsample_false_7_U0_HwReg_layerHeight_1_val = {{HwReg_layerHeight_1_val[(12 - 16'd1):0]}};

assign v_mix_upsample_false_7_U0_HwReg_layerWidth_1_val = {{HwReg_layerWidth_1_val[(12 - 16'd1):0]}};

assign v_mix_upsample_false_7_U0_ap_continue = 1'b1;

assign v_mix_upsample_false_7_U0_ap_start = start_for_v_mix_upsample_false_7_U0_empty_n;

assign v_mix_upsample_false_7_U0_srcLayer1x_fifo_cap = srcLayer1x_fifo_cap;

assign v_mix_upsample_false_7_U0_srcLayer1x_num_data_valid = srcLayer1x_num_data_valid;

assign v_mix_upsample_false_U0_HwReg_layerHeight_2_val = {{HwReg_layerHeight_2_val[(12 - 16'd1):0]}};

assign v_mix_upsample_false_U0_HwReg_layerWidth_2_val = {{HwReg_layerWidth_2_val[(12 - 16'd1):0]}};

assign v_mix_upsample_false_U0_ap_continue = 1'b1;

assign v_mix_upsample_false_U0_ap_start = start_for_v_mix_upsample_false_U0_empty_n;

assign v_mix_upsample_false_U0_srcLayer2x_fifo_cap = srcLayer2x_fifo_cap;

assign v_mix_upsample_false_U0_srcLayer2x_num_data_valid = srcLayer2x_num_data_valid;

assign v_mix_yuv2rgb_false_4_U0_ap_continue = 1'b1;

assign v_mix_yuv2rgb_false_4_U0_ap_start = start_for_v_mix_yuv2rgb_false_4_U0_empty_n;

assign v_mix_yuv2rgb_false_4_U0_outLayer0_fifo_cap = outLayer0_fifo_cap;

assign v_mix_yuv2rgb_false_4_U0_outLayer0_num_data_valid = outLayer0_num_data_valid;

assign v_mix_yuv2rgb_false_U0_HwReg_layerHeight_2_val = {{HwReg_layerHeight_2_val[(12 - 16'd1):0]}};

assign v_mix_yuv2rgb_false_U0_HwReg_layerWidth_2_val = {{HwReg_layerWidth_2_val[(12 - 16'd1):0]}};

assign v_mix_yuv2rgb_false_U0_ap_continue = 1'b1;

assign v_mix_yuv2rgb_false_U0_ap_start = start_for_v_mix_yuv2rgb_false_U0_empty_n;

assign v_mix_yuv2rgb_false_U0_srcLayer2Rgb_fifo_cap = srcLayer2Rgb_fifo_cap;

assign v_mix_yuv2rgb_false_U0_srcLayer2Rgb_num_data_valid = srcLayer2Rgb_num_data_valid;

assign v_mix_yuv2rgb_true_U0_HwReg_layerHeight_1_val = {{HwReg_layerHeight_1_val[(12 - 16'd1):0]}};

assign v_mix_yuv2rgb_true_U0_HwReg_layerWidth_1_val = {{HwReg_layerWidth_1_val[(12 - 16'd1):0]}};

assign v_mix_yuv2rgb_true_U0_ap_continue = 1'b1;

assign v_mix_yuv2rgb_true_U0_ap_start = start_for_v_mix_yuv2rgb_true_U0_empty_n;

assign v_mix_yuv2rgb_true_U0_srcLayer1Rgb_fifo_cap = srcLayer1Rgb_fifo_cap;

assign v_mix_yuv2rgb_true_U0_srcLayer1Rgb_num_data_valid = srcLayer1Rgb_num_data_valid;

endmodule //design_1_v_mix_0_0_VMixHlsDataFlowFunction
