// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="design_1_v_mix_0_0_v_mix,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sfvc784-1-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=5497,HLS_SYN_LUT=8411,HLS_VERSION=2025_1}" *)

module design_1_v_mix_0_0_v_mix (
        ap_clk,
        ap_rst_n,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        s_axis_video1_TDATA,
        s_axis_video1_TVALID,
        s_axis_video1_TREADY,
        s_axis_video1_TKEEP,
        s_axis_video1_TSTRB,
        s_axis_video1_TUSER,
        s_axis_video1_TLAST,
        s_axis_video1_TID,
        s_axis_video1_TDEST,
        s_axis_video2_TDATA,
        s_axis_video2_TVALID,
        s_axis_video2_TREADY,
        s_axis_video2_TKEEP,
        s_axis_video2_TSTRB,
        s_axis_video2_TUSER,
        s_axis_video2_TLAST,
        s_axis_video2_TID,
        s_axis_video2_TDEST,
        layerAlpha_0,
        layerStartX_0,
        layerStartY_0,
        layerWidth_0,
        layerHeight_0,
        layerScaleFactor_0,
        layerVideoFormat_address0,
        layerVideoFormat_ce0,
        layerVideoFormat_we0,
        layerVideoFormat_d0,
        layerVideoFormat_q0,
        layerVideoFormat_address1,
        layerVideoFormat_ce1,
        layerVideoFormat_we1,
        layerVideoFormat_d1,
        layerVideoFormat_q1,
        layerStride_0,
        K11,
        K12,
        K13,
        K21,
        K22,
        K23,
        K31,
        K32,
        K33,
        ROffset,
        GOffset,
        BOffset,
        K11_2,
        K12_2,
        K13_2,
        K21_2,
        K22_2,
        K23_2,
        K31_2,
        K32_2,
        K33_2,
        YOffset,
        UOffset,
        VOffset,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 12;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [23:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [2:0] s_axis_video_TKEEP;
input  [2:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
input  [23:0] s_axis_video1_TDATA;
input   s_axis_video1_TVALID;
output   s_axis_video1_TREADY;
input  [2:0] s_axis_video1_TKEEP;
input  [2:0] s_axis_video1_TSTRB;
input  [0:0] s_axis_video1_TUSER;
input  [0:0] s_axis_video1_TLAST;
input  [0:0] s_axis_video1_TID;
input  [0:0] s_axis_video1_TDEST;
input  [23:0] s_axis_video2_TDATA;
input   s_axis_video2_TVALID;
output   s_axis_video2_TREADY;
input  [2:0] s_axis_video2_TKEEP;
input  [2:0] s_axis_video2_TSTRB;
input  [0:0] s_axis_video2_TUSER;
input  [0:0] s_axis_video2_TLAST;
input  [0:0] s_axis_video2_TID;
input  [0:0] s_axis_video2_TDEST;
input  [15:0] layerAlpha_0;
input  [15:0] layerStartX_0;
input  [15:0] layerStartY_0;
input  [15:0] layerWidth_0;
input  [15:0] layerHeight_0;
input  [7:0] layerScaleFactor_0;
output  [1:0] layerVideoFormat_address0;
output   layerVideoFormat_ce0;
output   layerVideoFormat_we0;
output  [7:0] layerVideoFormat_d0;
input  [7:0] layerVideoFormat_q0;
output  [1:0] layerVideoFormat_address1;
output   layerVideoFormat_ce1;
output   layerVideoFormat_we1;
output  [7:0] layerVideoFormat_d1;
input  [7:0] layerVideoFormat_q1;
input  [15:0] layerStride_0;
input  [31:0] K11;
input  [31:0] K12;
input  [31:0] K13;
input  [31:0] K21;
input  [31:0] K22;
input  [31:0] K23;
input  [31:0] K31;
input  [31:0] K32;
input  [31:0] K33;
input  [31:0] ROffset;
input  [31:0] GOffset;
input  [31:0] BOffset;
input  [31:0] K11_2;
input  [31:0] K12_2;
input  [31:0] K13_2;
input  [31:0] K21_2;
input  [31:0] K22_2;
input  [31:0] K23_2;
input  [31:0] K31_2;
input  [31:0] K32_2;
input  [31:0] K33_2;
input  [31:0] YOffset;
input  [31:0] UOffset;
input  [31:0] VOffset;
output  [23:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] width;
wire   [15:0] height;
wire   [15:0] video_format;
wire   [15:0] background_Y_R;
wire   [15:0] background_U_G;
wire   [15:0] background_V_B;
wire   [31:0] layerEnable;
wire   [15:0] layerAlpha_1;
wire   [15:0] layerAlpha_2;
wire   [15:0] layerStartX_1;
wire   [15:0] layerStartX_2;
wire   [15:0] layerStartY_1;
wire   [15:0] layerStartY_2;
wire   [15:0] layerWidth_1;
wire   [15:0] layerWidth_2;
wire   [15:0] layerHeight_1;
wire   [15:0] layerHeight_2;
wire   [7:0] layerScaleFactor_1;
wire   [7:0] layerScaleFactor_2;
wire   [15:0] layerStride_1;
wire   [15:0] layerStride_2;
wire   [15:0] reserve;
reg   [31:0] layerEnable_read_reg_967;
wire   [2:0] trunc_ln2034_fu_580_p1;
reg   [2:0] trunc_ln2034_reg_972;
wire   [7:0] trunc_ln2034_1_fu_584_p1;
reg   [7:0] trunc_ln2034_1_reg_977;
wire   [7:0] trunc_ln2034_2_fu_588_p1;
reg   [7:0] trunc_ln2034_2_reg_982;
wire   [7:0] trunc_ln2034_3_fu_592_p1;
reg   [7:0] trunc_ln2034_3_reg_987;
wire   [11:0] trunc_ln2034_4_fu_596_p1;
reg   [11:0] trunc_ln2034_4_reg_992;
wire   [11:0] trunc_ln2034_5_fu_600_p1;
reg   [11:0] trunc_ln2034_5_reg_997;
reg   [15:0] layerAlpha_0_read_reg_1002;
reg   [15:0] layerAlpha_1_read_reg_1007;
reg   [15:0] layerAlpha_2_read_reg_1012;
reg   [15:0] layerStartX_0_read_reg_1017;
reg   [15:0] layerStartX_1_read_reg_1022;
reg   [15:0] layerStartX_2_read_reg_1027;
reg   [15:0] layerStartY_0_read_reg_1032;
reg   [15:0] layerStartY_1_read_reg_1037;
reg   [15:0] layerStartY_2_read_reg_1042;
reg   [15:0] layerWidth_0_read_reg_1047;
reg   [15:0] layerWidth_1_read_reg_1052;
reg   [15:0] layerWidth_2_read_reg_1057;
reg   [15:0] layerHeight_0_read_reg_1062;
reg   [15:0] layerHeight_1_read_reg_1067;
reg   [15:0] layerHeight_2_read_reg_1072;
reg   [7:0] layerScaleFactor_0_read_reg_1077;
reg   [7:0] layerScaleFactor_1_read_reg_1082;
reg   [7:0] layerScaleFactor_2_read_reg_1087;
wire   [8:0] trunc_ln2912_fu_871_p1;
reg   [8:0] trunc_ln2912_reg_1137;
wire    ap_CS_fsm_state3;
wire   [23:0] grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TDATA;
wire   [2:0] grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TKEEP;
wire   [2:0] grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TSTRB;
wire   [0:0] grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TUSER;
wire   [0:0] grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TLAST;
wire   [0:0] grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TID;
wire   [0:0] grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TDEST;
wire    grp_VMixHlsDataFlowFunction_fu_500_s_axis_video_TREADY;
wire    grp_VMixHlsDataFlowFunction_fu_500_ap_start;
wire    grp_VMixHlsDataFlowFunction_fu_500_s_axis_video1_TREADY;
wire    grp_VMixHlsDataFlowFunction_fu_500_s_axis_video2_TREADY;
wire    grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID;
wire    grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TREADY;
wire    grp_VMixHlsDataFlowFunction_fu_500_ap_done;
wire    grp_VMixHlsDataFlowFunction_fu_500_ap_ready;
wire    grp_VMixHlsDataFlowFunction_fu_500_ap_idle;
reg    grp_VMixHlsDataFlowFunction_fu_500_ap_continue;
reg    grp_VMixHlsDataFlowFunction_fu_500_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_ready;
reg    ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_done;
reg    ap_block_state4_on_subcall_done;
wire    ap_sync_grp_VMixHlsDataFlowFunction_fu_500_ap_ready;
reg   [23:0] m_axis_video_TDATA_reg;
reg   [2:0] m_axis_video_TKEEP_reg;
reg   [2:0] m_axis_video_TSTRB_reg;
reg   [0:0] m_axis_video_TUSER_reg;
reg   [0:0] m_axis_video_TLAST_reg;
reg   [0:0] m_axis_video_TID_reg;
reg   [0:0] m_axis_video_TDEST_reg;
reg   [1:0] i7_fu_296;
wire   [1:0] i_fu_721_p2;
wire    ap_CS_fsm_state2;
wire   [1:0] i7_load_load_fu_609_p1;
reg   [0:0] tobool172_fu_300;
wire   [0:0] tobool_fu_714_p3;
reg   [7:0] empty_fu_304;
wire   [7:0] HwReg_layerScaleFactor_fu_697_p9;
reg   [15:0] empty_88_fu_308;
wire   [15:0] tmp_6_fu_680_p9;
reg   [15:0] empty_89_fu_312;
wire   [15:0] tmp_s_fu_663_p9;
reg   [15:0] empty_90_fu_316;
wire   [15:0] HwReg_layerStartY_fu_646_p9;
reg   [15:0] empty_91_fu_320;
wire   [15:0] HwReg_layerStartX_fu_629_p9;
reg   [15:0] empty_92_fu_324;
wire   [15:0] HwReg_layerAlpha_fu_612_p9;
reg   [0:0] tobool94_fu_328;
reg   [0:0] tobool56_fu_332;
reg   [7:0] empty_93_fu_336;
reg   [15:0] empty_94_fu_340;
reg   [15:0] empty_95_fu_344;
reg   [15:0] empty_96_fu_348;
reg   [15:0] empty_97_fu_352;
wire   [15:0] HwReg_layerAlpha_fu_612_p7;
wire   [15:0] HwReg_layerStartX_fu_629_p7;
wire   [15:0] HwReg_layerStartY_fu_646_p7;
wire   [15:0] tmp_s_fu_663_p7;
wire   [15:0] tmp_6_fu_680_p7;
wire   [7:0] HwReg_layerScaleFactor_fu_697_p7;
wire   [0:0] icmp_ln2912_fu_805_p2;
wire    ap_CS_fsm_state5;
wire    regslice_both_m_axis_video_V_data_V_U_apdone_blk;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_s_axis_video_V_data_V_U_apdone_blk;
wire   [23:0] s_axis_video_TDATA_int_regslice;
wire    s_axis_video_TVALID_int_regslice;
reg    s_axis_video_TREADY_int_regslice;
wire    regslice_both_s_axis_video_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video_V_keep_V_U_apdone_blk;
wire   [2:0] s_axis_video_TKEEP_int_regslice;
wire    regslice_both_s_axis_video_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video_V_strb_V_U_apdone_blk;
wire   [2:0] s_axis_video_TSTRB_int_regslice;
wire    regslice_both_s_axis_video_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video_TUSER_int_regslice;
wire    regslice_both_s_axis_video_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video_TLAST_int_regslice;
wire    regslice_both_s_axis_video_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video_TID_int_regslice;
wire    regslice_both_s_axis_video_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video_TDEST_int_regslice;
wire    regslice_both_s_axis_video_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video_V_dest_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_data_V_U_apdone_blk;
wire   [23:0] s_axis_video1_TDATA_int_regslice;
wire    s_axis_video1_TVALID_int_regslice;
reg    s_axis_video1_TREADY_int_regslice;
wire    regslice_both_s_axis_video1_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_keep_V_U_apdone_blk;
wire   [2:0] s_axis_video1_TKEEP_int_regslice;
wire    regslice_both_s_axis_video1_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video1_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_strb_V_U_apdone_blk;
wire   [2:0] s_axis_video1_TSTRB_int_regslice;
wire    regslice_both_s_axis_video1_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video1_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video1_TUSER_int_regslice;
wire    regslice_both_s_axis_video1_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video1_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video1_TLAST_int_regslice;
wire    regslice_both_s_axis_video1_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video1_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video1_TID_int_regslice;
wire    regslice_both_s_axis_video1_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video1_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video1_TDEST_int_regslice;
wire    regslice_both_s_axis_video1_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video1_V_dest_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_data_V_U_apdone_blk;
wire   [23:0] s_axis_video2_TDATA_int_regslice;
wire    s_axis_video2_TVALID_int_regslice;
reg    s_axis_video2_TREADY_int_regslice;
wire    regslice_both_s_axis_video2_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_keep_V_U_apdone_blk;
wire   [2:0] s_axis_video2_TKEEP_int_regslice;
wire    regslice_both_s_axis_video2_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video2_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_strb_V_U_apdone_blk;
wire   [2:0] s_axis_video2_TSTRB_int_regslice;
wire    regslice_both_s_axis_video2_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video2_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video2_TUSER_int_regslice;
wire    regslice_both_s_axis_video2_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video2_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video2_TLAST_int_regslice;
wire    regslice_both_s_axis_video2_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video2_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video2_TID_int_regslice;
wire    regslice_both_s_axis_video2_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video2_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video2_TDEST_int_regslice;
wire    regslice_both_s_axis_video2_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video2_V_dest_V_U_ack_in;
reg   [23:0] m_axis_video_TDATA_int_regslice;
wire    m_axis_video_TVALID_int_regslice;
wire    m_axis_video_TREADY_int_regslice;
wire    regslice_both_m_axis_video_V_data_V_U_vld_out;
wire    regslice_both_m_axis_video_V_keep_V_U_apdone_blk;
reg   [2:0] m_axis_video_TKEEP_int_regslice;
wire    regslice_both_m_axis_video_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_video_V_strb_V_U_apdone_blk;
reg   [2:0] m_axis_video_TSTRB_int_regslice;
wire    regslice_both_m_axis_video_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_video_V_user_V_U_apdone_blk;
reg   [0:0] m_axis_video_TUSER_int_regslice;
wire    regslice_both_m_axis_video_V_user_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_user_V_U_vld_out;
wire    regslice_both_m_axis_video_V_last_V_U_apdone_blk;
reg   [0:0] m_axis_video_TLAST_int_regslice;
wire    regslice_both_m_axis_video_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_last_V_U_vld_out;
wire    regslice_both_m_axis_video_V_id_V_U_apdone_blk;
reg   [0:0] m_axis_video_TID_int_regslice;
wire    regslice_both_m_axis_video_V_id_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_id_V_U_vld_out;
wire    regslice_both_m_axis_video_V_dest_V_U_apdone_blk;
reg   [0:0] m_axis_video_TDEST_int_regslice;
wire    regslice_both_m_axis_video_V_dest_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_dest_V_U_vld_out;
wire   [1:0] HwReg_layerAlpha_fu_612_p1;
wire   [1:0] HwReg_layerAlpha_fu_612_p3;
wire  signed [1:0] HwReg_layerAlpha_fu_612_p5;
wire   [1:0] HwReg_layerStartX_fu_629_p1;
wire   [1:0] HwReg_layerStartX_fu_629_p3;
wire  signed [1:0] HwReg_layerStartX_fu_629_p5;
wire   [1:0] HwReg_layerStartY_fu_646_p1;
wire   [1:0] HwReg_layerStartY_fu_646_p3;
wire  signed [1:0] HwReg_layerStartY_fu_646_p5;
wire   [1:0] tmp_s_fu_663_p1;
wire   [1:0] tmp_s_fu_663_p3;
wire  signed [1:0] tmp_s_fu_663_p5;
wire   [1:0] tmp_6_fu_680_p1;
wire   [1:0] tmp_6_fu_680_p3;
wire  signed [1:0] tmp_6_fu_680_p5;
wire   [1:0] HwReg_layerScaleFactor_fu_697_p1;
wire   [1:0] HwReg_layerScaleFactor_fu_697_p3;
wire  signed [1:0] HwReg_layerScaleFactor_fu_697_p5;
wire   [0:0] tobool_fu_714_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_VMixHlsDataFlowFunction_fu_500_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_ready = 1'b0;
#0 ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_done = 1'b0;
#0 i7_fu_296 = 2'd0;
#0 tobool172_fu_300 = 1'd0;
#0 empty_fu_304 = 8'd0;
#0 empty_88_fu_308 = 16'd0;
#0 empty_89_fu_312 = 16'd0;
#0 empty_90_fu_316 = 16'd0;
#0 empty_91_fu_320 = 16'd0;
#0 empty_92_fu_324 = 16'd0;
#0 tobool94_fu_328 = 1'd0;
#0 tobool56_fu_332 = 1'd0;
#0 empty_93_fu_336 = 8'd0;
#0 empty_94_fu_340 = 16'd0;
#0 empty_95_fu_344 = 16'd0;
#0 empty_96_fu_348 = 16'd0;
#0 empty_97_fu_352 = 16'd0;
end

design_1_v_mix_0_0_VMixHlsDataFlowFunction grp_VMixHlsDataFlowFunction_fu_500(
    .HwReg_width_val(trunc_ln2034_4_reg_992),
    .HwReg_height_val(trunc_ln2034_5_reg_997),
    .HwReg_background_Y_R_val12(trunc_ln2034_3_reg_987),
    .HwReg_background_U_G_val13(trunc_ln2034_2_reg_982),
    .HwReg_background_V_B_val14(trunc_ln2034_1_reg_977),
    .HwReg_layerEnable_val16(trunc_ln2034_reg_972),
    .HwReg_layerEnableFlag_0_val(tobool94_fu_328),
    .HwReg_layerEnableFlag_1_val(tobool56_fu_332),
    .HwReg_layerEnableFlag_2_val(tobool172_fu_300),
    .HwReg_layerAlpha_2_val17(trunc_ln2912_reg_1137),
    .HwReg_layerStartX_1_val18(empty_97_fu_352),
    .HwReg_layerStartX_2_val19(empty_91_fu_320),
    .HwReg_layerStartY_1_val20(empty_96_fu_348),
    .HwReg_layerStartY_2_val21(empty_90_fu_316),
    .HwReg_layerWidth_1_val(empty_95_fu_344),
    .HwReg_layerWidth_2_val(empty_89_fu_312),
    .HwReg_layerHeight_1_val(empty_94_fu_340),
    .HwReg_layerHeight_2_val(empty_88_fu_308),
    .HwReg_layerScaleFactor_1_val26(empty_93_fu_336),
    .HwReg_layerScaleFactor_2_val27(empty_fu_304),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .s_axis_video1_TDATA(s_axis_video1_TDATA_int_regslice),
    .s_axis_video1_TKEEP(s_axis_video1_TKEEP_int_regslice),
    .s_axis_video1_TSTRB(s_axis_video1_TSTRB_int_regslice),
    .s_axis_video1_TUSER(s_axis_video1_TUSER_int_regslice),
    .s_axis_video1_TLAST(s_axis_video1_TLAST_int_regslice),
    .s_axis_video1_TID(s_axis_video1_TID_int_regslice),
    .s_axis_video1_TDEST(s_axis_video1_TDEST_int_regslice),
    .s_axis_video2_TDATA(s_axis_video2_TDATA_int_regslice),
    .s_axis_video2_TKEEP(s_axis_video2_TKEEP_int_regslice),
    .s_axis_video2_TSTRB(s_axis_video2_TSTRB_int_regslice),
    .s_axis_video2_TUSER(s_axis_video2_TUSER_int_regslice),
    .s_axis_video2_TLAST(s_axis_video2_TLAST_int_regslice),
    .s_axis_video2_TID(s_axis_video2_TID_int_regslice),
    .s_axis_video2_TDEST(s_axis_video2_TDEST_int_regslice),
    .m_axis_video_TDATA(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TDATA),
    .m_axis_video_TKEEP(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TSTRB),
    .m_axis_video_TUSER(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TUSER),
    .m_axis_video_TLAST(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TLAST),
    .m_axis_video_TID(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TID),
    .m_axis_video_TDEST(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TDEST),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .s_axis_video_TREADY(grp_VMixHlsDataFlowFunction_fu_500_s_axis_video_TREADY),
    .HwReg_height_val_ap_vld(1'b1),
    .HwReg_width_val_ap_vld(1'b1),
    .HwReg_layerEnableFlag_0_val_ap_vld(1'b1),
    .ap_start(grp_VMixHlsDataFlowFunction_fu_500_ap_start),
    .s_axis_video1_TVALID(s_axis_video1_TVALID_int_regslice),
    .s_axis_video1_TREADY(grp_VMixHlsDataFlowFunction_fu_500_s_axis_video1_TREADY),
    .HwReg_layerHeight_1_val_ap_vld(1'b1),
    .HwReg_layerWidth_1_val_ap_vld(1'b1),
    .HwReg_layerEnableFlag_1_val_ap_vld(1'b1),
    .HwReg_background_Y_R_val12_ap_vld(1'b1),
    .HwReg_background_U_G_val13_ap_vld(1'b1),
    .HwReg_background_V_B_val14_ap_vld(1'b1),
    .HwReg_layerEnable_val16_ap_vld(1'b1),
    .HwReg_layerStartX_1_val18_ap_vld(1'b1),
    .HwReg_layerStartY_1_val20_ap_vld(1'b1),
    .HwReg_layerScaleFactor_1_val26_ap_vld(1'b1),
    .s_axis_video2_TVALID(s_axis_video2_TVALID_int_regslice),
    .s_axis_video2_TREADY(grp_VMixHlsDataFlowFunction_fu_500_s_axis_video2_TREADY),
    .HwReg_layerHeight_2_val_ap_vld(1'b1),
    .HwReg_layerWidth_2_val_ap_vld(1'b1),
    .HwReg_layerEnableFlag_2_val_ap_vld(1'b1),
    .HwReg_layerAlpha_2_val17_ap_vld(1'b1),
    .HwReg_layerStartX_2_val19_ap_vld(1'b1),
    .HwReg_layerStartY_2_val21_ap_vld(1'b1),
    .HwReg_layerScaleFactor_2_val27_ap_vld(1'b1),
    .m_axis_video_TVALID(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID),
    .m_axis_video_TREADY(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TREADY),
    .ap_done(grp_VMixHlsDataFlowFunction_fu_500_ap_done),
    .ap_ready(grp_VMixHlsDataFlowFunction_fu_500_ap_ready),
    .ap_idle(grp_VMixHlsDataFlowFunction_fu_500_ap_idle),
    .ap_continue(grp_VMixHlsDataFlowFunction_fu_500_ap_continue)
);

design_1_v_mix_0_0_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .width(width),
    .height(height),
    .video_format(video_format),
    .background_Y_R(background_Y_R),
    .background_U_G(background_U_G),
    .background_V_B(background_V_B),
    .layerEnable(layerEnable),
    .layerAlpha_1(layerAlpha_1),
    .layerStartX_1(layerStartX_1),
    .layerStartY_1(layerStartY_1),
    .layerWidth_1(layerWidth_1),
    .layerStride_1(layerStride_1),
    .layerHeight_1(layerHeight_1),
    .layerScaleFactor_1(layerScaleFactor_1),
    .layerAlpha_2(layerAlpha_2),
    .layerStartX_2(layerStartX_2),
    .layerStartY_2(layerStartY_2),
    .layerWidth_2(layerWidth_2),
    .layerStride_2(layerStride_2),
    .layerHeight_2(layerHeight_2),
    .layerScaleFactor_2(layerScaleFactor_2),
    .reserve(reserve),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

(* dissolve_hierarchy = "yes" *) design_1_v_mix_0_0_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U440(
    .din0(layerAlpha_0_read_reg_1002),
    .din1(layerAlpha_1_read_reg_1007),
    .din2(layerAlpha_2_read_reg_1012),
    .def(HwReg_layerAlpha_fu_612_p7),
    .sel(i7_fu_296),
    .dout(HwReg_layerAlpha_fu_612_p9)
);

(* dissolve_hierarchy = "yes" *) design_1_v_mix_0_0_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U441(
    .din0(layerStartX_0_read_reg_1017),
    .din1(layerStartX_1_read_reg_1022),
    .din2(layerStartX_2_read_reg_1027),
    .def(HwReg_layerStartX_fu_629_p7),
    .sel(i7_fu_296),
    .dout(HwReg_layerStartX_fu_629_p9)
);

(* dissolve_hierarchy = "yes" *) design_1_v_mix_0_0_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U442(
    .din0(layerStartY_0_read_reg_1032),
    .din1(layerStartY_1_read_reg_1037),
    .din2(layerStartY_2_read_reg_1042),
    .def(HwReg_layerStartY_fu_646_p7),
    .sel(i7_fu_296),
    .dout(HwReg_layerStartY_fu_646_p9)
);

(* dissolve_hierarchy = "yes" *) design_1_v_mix_0_0_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U443(
    .din0(layerWidth_0_read_reg_1047),
    .din1(layerWidth_1_read_reg_1052),
    .din2(layerWidth_2_read_reg_1057),
    .def(tmp_s_fu_663_p7),
    .sel(i7_fu_296),
    .dout(tmp_s_fu_663_p9)
);

(* dissolve_hierarchy = "yes" *) design_1_v_mix_0_0_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U444(
    .din0(layerHeight_0_read_reg_1062),
    .din1(layerHeight_1_read_reg_1067),
    .din2(layerHeight_2_read_reg_1072),
    .def(tmp_6_fu_680_p7),
    .sel(i7_fu_296),
    .dout(tmp_6_fu_680_p9)
);

(* dissolve_hierarchy = "yes" *) design_1_v_mix_0_0_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U445(
    .din0(layerScaleFactor_0_read_reg_1077),
    .din1(layerScaleFactor_1_read_reg_1082),
    .din2(layerScaleFactor_2_read_reg_1087),
    .def(HwReg_layerScaleFactor_fu_697_p7),
    .sel(i7_fu_296),
    .dout(HwReg_layerScaleFactor_fu_697_p9)
);

design_1_v_mix_0_0_bitselect_1ns_32ns_2ns_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 2 ))
bitselect_1ns_32ns_2ns_1_1_1_U446(
    .din(layerEnable_read_reg_967),
    .sel(i7_fu_296),
    .dout(tobool_fu_714_p3)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 24 ))
regslice_both_s_axis_video_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TDATA),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_data_V_U_ack_in),
    .data_out(s_axis_video_TDATA_int_regslice),
    .vld_out(s_axis_video_TVALID_int_regslice),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_data_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_s_axis_video_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TKEEP),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_keep_V_U_ack_in),
    .data_out(s_axis_video_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_keep_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_keep_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_s_axis_video_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TSTRB),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_strb_V_U_ack_in),
    .data_out(s_axis_video_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_strb_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_strb_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TUSER),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_user_V_U_ack_in),
    .data_out(s_axis_video_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_user_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_user_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TLAST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_last_V_U_ack_in),
    .data_out(s_axis_video_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_last_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_last_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TID),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_id_V_U_ack_in),
    .data_out(s_axis_video_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_id_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_id_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TDEST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_dest_V_U_ack_in),
    .data_out(s_axis_video_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_dest_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_dest_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 24 ))
regslice_both_s_axis_video1_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TDATA),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_data_V_U_ack_in),
    .data_out(s_axis_video1_TDATA_int_regslice),
    .vld_out(s_axis_video1_TVALID_int_regslice),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_data_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_s_axis_video1_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TKEEP),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_keep_V_U_ack_in),
    .data_out(s_axis_video1_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video1_V_keep_V_U_vld_out),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_keep_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_s_axis_video1_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TSTRB),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_strb_V_U_ack_in),
    .data_out(s_axis_video1_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video1_V_strb_V_U_vld_out),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_strb_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video1_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TUSER),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_user_V_U_ack_in),
    .data_out(s_axis_video1_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video1_V_user_V_U_vld_out),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_user_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video1_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TLAST),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_last_V_U_ack_in),
    .data_out(s_axis_video1_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video1_V_last_V_U_vld_out),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_last_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video1_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TID),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_id_V_U_ack_in),
    .data_out(s_axis_video1_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video1_V_id_V_U_vld_out),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_id_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video1_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TDEST),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_dest_V_U_ack_in),
    .data_out(s_axis_video1_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video1_V_dest_V_U_vld_out),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_dest_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 24 ))
regslice_both_s_axis_video2_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TDATA),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_data_V_U_ack_in),
    .data_out(s_axis_video2_TDATA_int_regslice),
    .vld_out(s_axis_video2_TVALID_int_regslice),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_data_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_s_axis_video2_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TKEEP),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_keep_V_U_ack_in),
    .data_out(s_axis_video2_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video2_V_keep_V_U_vld_out),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_keep_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_s_axis_video2_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TSTRB),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_strb_V_U_ack_in),
    .data_out(s_axis_video2_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video2_V_strb_V_U_vld_out),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_strb_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video2_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TUSER),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_user_V_U_ack_in),
    .data_out(s_axis_video2_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video2_V_user_V_U_vld_out),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_user_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video2_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TLAST),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_last_V_U_ack_in),
    .data_out(s_axis_video2_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video2_V_last_V_U_vld_out),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_last_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video2_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TID),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_id_V_U_ack_in),
    .data_out(s_axis_video2_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video2_V_id_V_U_vld_out),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_id_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video2_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TDEST),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_dest_V_U_ack_in),
    .data_out(s_axis_video2_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video2_V_dest_V_U_vld_out),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_dest_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 24 ))
regslice_both_m_axis_video_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TDATA_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID),
    .ack_in(m_axis_video_TREADY_int_regslice),
    .data_out(m_axis_video_TDATA),
    .vld_out(regslice_both_m_axis_video_V_data_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_data_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_m_axis_video_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TKEEP_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_video_TKEEP),
    .vld_out(regslice_both_m_axis_video_V_keep_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_keep_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_m_axis_video_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TSTRB_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_video_TSTRB),
    .vld_out(regslice_both_m_axis_video_V_strb_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_strb_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_video_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TUSER_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_user_V_U_ack_in_dummy),
    .data_out(m_axis_video_TUSER),
    .vld_out(regslice_both_m_axis_video_V_user_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_user_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_video_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TLAST_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_video_TLAST),
    .vld_out(regslice_both_m_axis_video_V_last_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_last_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_video_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TID_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_id_V_U_ack_in_dummy),
    .data_out(m_axis_video_TID),
    .vld_out(regslice_both_m_axis_video_V_id_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_id_V_U_apdone_blk)
);

design_1_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_video_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TDEST_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_dest_V_U_ack_in_dummy),
    .data_out(m_axis_video_TDEST),
    .vld_out(regslice_both_m_axis_video_V_dest_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_done <= 1'b0;
        end else if ((grp_VMixHlsDataFlowFunction_fu_500_ap_done == 1'b1)) begin
            ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_ready <= 1'b0;
        end else if ((grp_VMixHlsDataFlowFunction_fu_500_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_VMixHlsDataFlowFunction_fu_500_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) | ((ap_sync_grp_VMixHlsDataFlowFunction_fu_500_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state4)))) begin
            grp_VMixHlsDataFlowFunction_fu_500_ap_start_reg <= 1'b1;
        end else if ((grp_VMixHlsDataFlowFunction_fu_500_ap_ready == 1'b1)) begin
            grp_VMixHlsDataFlowFunction_fu_500_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i7_fu_296 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        i7_fu_296 <= i_fu_721_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i7_load_load_fu_609_p1 == 2'd1) & ~(i7_load_load_fu_609_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_88_fu_308 <= tmp_6_fu_680_p9;
        empty_89_fu_312 <= tmp_s_fu_663_p9;
        empty_90_fu_316 <= HwReg_layerStartY_fu_646_p9;
        empty_91_fu_320 <= HwReg_layerStartX_fu_629_p9;
        empty_92_fu_324 <= HwReg_layerAlpha_fu_612_p9;
        empty_fu_304 <= HwReg_layerScaleFactor_fu_697_p9;
        tobool172_fu_300 <= tobool_fu_714_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((i7_load_load_fu_609_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_93_fu_336 <= HwReg_layerScaleFactor_fu_697_p9;
        empty_94_fu_340 <= tmp_6_fu_680_p9;
        empty_95_fu_344 <= tmp_s_fu_663_p9;
        empty_96_fu_348 <= HwReg_layerStartY_fu_646_p9;
        empty_97_fu_352 <= HwReg_layerStartX_fu_629_p9;
        tobool56_fu_332 <= tobool_fu_714_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        layerAlpha_0_read_reg_1002 <= layerAlpha_0;
        layerAlpha_1_read_reg_1007 <= layerAlpha_1;
        layerAlpha_2_read_reg_1012 <= layerAlpha_2;
        layerEnable_read_reg_967 <= layerEnable;
        layerHeight_0_read_reg_1062 <= layerHeight_0;
        layerHeight_1_read_reg_1067 <= layerHeight_1;
        layerHeight_2_read_reg_1072 <= layerHeight_2;
        layerScaleFactor_0_read_reg_1077 <= layerScaleFactor_0;
        layerScaleFactor_1_read_reg_1082 <= layerScaleFactor_1;
        layerScaleFactor_2_read_reg_1087 <= layerScaleFactor_2;
        layerStartX_0_read_reg_1017 <= layerStartX_0;
        layerStartX_1_read_reg_1022 <= layerStartX_1;
        layerStartX_2_read_reg_1027 <= layerStartX_2;
        layerStartY_0_read_reg_1032 <= layerStartY_0;
        layerStartY_1_read_reg_1037 <= layerStartY_1;
        layerStartY_2_read_reg_1042 <= layerStartY_2;
        layerWidth_0_read_reg_1047 <= layerWidth_0;
        layerWidth_1_read_reg_1052 <= layerWidth_1;
        layerWidth_2_read_reg_1057 <= layerWidth_2;
        trunc_ln2034_1_reg_977 <= trunc_ln2034_1_fu_584_p1;
        trunc_ln2034_2_reg_982 <= trunc_ln2034_2_fu_588_p1;
        trunc_ln2034_3_reg_987 <= trunc_ln2034_3_fu_592_p1;
        trunc_ln2034_4_reg_992 <= trunc_ln2034_4_fu_596_p1;
        trunc_ln2034_5_reg_997 <= trunc_ln2034_5_fu_600_p1;
        trunc_ln2034_reg_972 <= trunc_ln2034_fu_580_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TDATA_reg <= grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TDATA;
        m_axis_video_TDEST_reg <= grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TDEST;
        m_axis_video_TID_reg <= grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TID;
        m_axis_video_TKEEP_reg <= grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TKEEP;
        m_axis_video_TLAST_reg <= grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TLAST;
        m_axis_video_TSTRB_reg <= grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TSTRB;
        m_axis_video_TUSER_reg <= grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if (((i7_load_load_fu_609_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tobool94_fu_328 <= tobool_fu_714_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        trunc_ln2912_reg_1137 <= trunc_ln2912_fu_871_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        grp_VMixHlsDataFlowFunction_fu_500_ap_continue = 1'b1;
    end else begin
        grp_VMixHlsDataFlowFunction_fu_500_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TDATA_int_regslice = grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TDATA;
    end else begin
        m_axis_video_TDATA_int_regslice = m_axis_video_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TDEST_int_regslice = grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TDEST;
    end else begin
        m_axis_video_TDEST_int_regslice = m_axis_video_TDEST_reg;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TID_int_regslice = grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TID;
    end else begin
        m_axis_video_TID_int_regslice = m_axis_video_TID_reg;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TKEEP_int_regslice = grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TKEEP;
    end else begin
        m_axis_video_TKEEP_int_regslice = m_axis_video_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TLAST_int_regslice = grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TLAST;
    end else begin
        m_axis_video_TLAST_int_regslice = m_axis_video_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TSTRB_int_regslice = grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TSTRB;
    end else begin
        m_axis_video_TSTRB_int_regslice = m_axis_video_TSTRB_reg;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TUSER_int_regslice = grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TUSER;
    end else begin
        m_axis_video_TUSER_int_regslice = m_axis_video_TUSER_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_axis_video1_TREADY_int_regslice = grp_VMixHlsDataFlowFunction_fu_500_s_axis_video1_TREADY;
    end else begin
        s_axis_video1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_axis_video2_TREADY_int_regslice = grp_VMixHlsDataFlowFunction_fu_500_s_axis_video2_TREADY;
    end else begin
        s_axis_video2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_axis_video_TREADY_int_regslice = grp_VMixHlsDataFlowFunction_fu_500_s_axis_video_TREADY;
    end else begin
        s_axis_video_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln2912_fu_805_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HwReg_layerAlpha_fu_612_p7 = 'bx;

assign HwReg_layerScaleFactor_fu_697_p7 = 'bx;

assign HwReg_layerStartX_fu_629_p7 = 'bx;

assign HwReg_layerStartY_fu_646_p7 = 'bx;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_ready & ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_done) == 1'b0);
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_grp_VMixHlsDataFlowFunction_fu_500_ap_ready = (grp_VMixHlsDataFlowFunction_fu_500_ap_ready | ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_500_ap_ready);

assign grp_VMixHlsDataFlowFunction_fu_500_ap_start = grp_VMixHlsDataFlowFunction_fu_500_ap_start_reg;

assign grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TREADY = (m_axis_video_TREADY_int_regslice & ap_CS_fsm_state4);

assign i7_load_load_fu_609_p1 = i7_fu_296;

assign i_fu_721_p2 = (i7_fu_296 + 2'd1);

assign icmp_ln2912_fu_805_p2 = ((i7_fu_296 == 2'd2) ? 1'b1 : 1'b0);

assign layerVideoFormat_address0 = 2'd0;

assign layerVideoFormat_address1 = 2'd0;

assign layerVideoFormat_ce0 = 1'b0;

assign layerVideoFormat_ce1 = 1'b0;

assign layerVideoFormat_d0 = 8'd0;

assign layerVideoFormat_d1 = 8'd0;

assign layerVideoFormat_we0 = 1'b0;

assign layerVideoFormat_we1 = 1'b0;

assign m_axis_video_TVALID = regslice_both_m_axis_video_V_data_V_U_vld_out;

assign m_axis_video_TVALID_int_regslice = grp_VMixHlsDataFlowFunction_fu_500_m_axis_video_TVALID;

assign s_axis_video1_TREADY = regslice_both_s_axis_video1_V_data_V_U_ack_in;

assign s_axis_video2_TREADY = regslice_both_s_axis_video2_V_data_V_U_ack_in;

assign s_axis_video_TREADY = regslice_both_s_axis_video_V_data_V_U_ack_in;

assign tmp_6_fu_680_p7 = 'bx;

assign tmp_s_fu_663_p7 = 'bx;

assign trunc_ln2034_1_fu_584_p1 = background_V_B[7:0];

assign trunc_ln2034_2_fu_588_p1 = background_U_G[7:0];

assign trunc_ln2034_3_fu_592_p1 = background_Y_R[7:0];

assign trunc_ln2034_4_fu_596_p1 = width[11:0];

assign trunc_ln2034_5_fu_600_p1 = height[11:0];

assign trunc_ln2034_fu_580_p1 = layerEnable[2:0];

assign trunc_ln2912_fu_871_p1 = empty_92_fu_324[8:0];

endmodule //design_1_v_mix_0_0_v_mix
