domain_path: /home/e/Documents/research/byotee_riscv/platform/export/platform/sw/microblaze_riscv_0
app_src_dir: /tools/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
